package aws.carddemo;

import com.tmax.openframe.online.service.api.AbendHandler;
import com.tmax.openframe.online.service.api.ProgramControl;
import aws.carddemo.dto.CocrdlicInputDto;
import aws.carddemo.mapper.CocrdslcMapperInterface.*;
import aws.carddemo.dto.Comen01cInputDto;
import com.tmax.openframe.online.service.api.TaskInvoker;
import com.tmax.openframe.online.service.dto.taskdto.TaskDto;
import com.tmax.openframe.online.service.dto.taskdto.Data;
import com.tmax.openframe.online.service.api.Task;
import aws.carddemo.dto.CocrdslcOutputDto;
import com.tmax.openframe.online.service.exception.ConditionException;
import aws.carddemo.dto.CocrdslcInputDto;
import aws.carddemo.dto.AwsM2CarddemoCarddataVsamKsdsDto;
import com.tmax.openframe.online.service.api.ReadPointManager;
import com.tmax.openframe.online.service.api.RecordKeyAccessor;
import com.tmax.openframe.online.service.exception.OnlineException;
import com.tmax.openframe.online.service.exception.AbendException;
import static aws.carddemo.variable.group.CocrdslcCarddemoCommarea.CocrdslcCdemoGeneralInfo.*;
import static aws.carddemo.variable.group.CocrdslcCcWorkAreas.CocrdslcCcWorkArea.*;
import static aws.carddemo.variable.group.CocrdslcWsMiscStorage.*;
import aws.carddemo.variable.CocrdslcVariableContainer;
import aws.carddemo.variable.group.*;
import com.tmax.openframe.DataConverter;
import com.tmax.openframe.runtime.cobol.CobStringUtils;
import com.tmax.openframe.runtime.cobol.IntrinsicFunction;
import com.tmax.openframe.runtime.context.OpenFrameContext;
import com.tmax.openframe.runtime.flow.ControlManager;
import java.math.*;
import java.util.*;
import java.util.function.Consumer;
import lombok.*;
import org.apache.commons.lang3.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/** 
 * <p>This source code was generated by T-Up OpenFrame COBOL to Java migrator</p>
 * <p>  Generation date : 2024/05/02 05:57:42 UTC</p>
 * <hr>
 * <p>Java class for defining logics of COBOL program</p>
 * <ul>
 * <li>The name of COBOL program: COCRDSLC.cbl</li>
 * <li>Variable container class: {@link CocrdslcVariableContainer}</li>
 * </ul>
 */
@Service
@RequiredArgsConstructor
@Transactional
public class Cocrdslc {
    private final ReadPointManager readPointManager;
    private final RecordKeyAccessor recordKeyAccessor;
    private final Task task;
    private final TaskInvoker taskInvoker;
    private final ProgramControl programControl;
    private final AbendHandler abendHandler;
    /** 
     * <p>Class that manages an execution flow of the program</p>
     */
    private final ControlManager controlManager;
    Consumer<OpenFrameContext> _0000Main = this::_0000Main;
    Consumer<OpenFrameContext> commonReturn = this::commonReturn;
    Consumer<OpenFrameContext> _0000MainExit = this::_0000MainExit;
    Consumer<OpenFrameContext> _1000SendMap = this::_1000SendMap;
    Consumer<OpenFrameContext> _1000SendMapExit = this::_1000SendMapExit;
    Consumer<OpenFrameContext> _1100ScreenInit = this::_1100ScreenInit;
    Consumer<OpenFrameContext> _1100ScreenInitExit = this::_1100ScreenInitExit;
    Consumer<OpenFrameContext> _1200SetupScreenVars = this::_1200SetupScreenVars;
    Consumer<OpenFrameContext> _1200SetupScreenVarsExit = this::_1200SetupScreenVarsExit;
    Consumer<OpenFrameContext> _1300SetupScreenAttrs = this::_1300SetupScreenAttrs;
    Consumer<OpenFrameContext> _1300SetupScreenAttrsExit = this::_1300SetupScreenAttrsExit;
    Consumer<OpenFrameContext> _1400SendScreen = this::_1400SendScreen;
    Consumer<OpenFrameContext> _1400SendScreenExit = this::_1400SendScreenExit;
    Consumer<OpenFrameContext> _2000ProcessInputs = this::_2000ProcessInputs;
    Consumer<OpenFrameContext> _2000ProcessInputsExit = this::_2000ProcessInputsExit;
    Consumer<OpenFrameContext> _2100ReceiveMap = this::_2100ReceiveMap;
    Consumer<OpenFrameContext> _2100ReceiveMapExit = this::_2100ReceiveMapExit;
    Consumer<OpenFrameContext> _2200EditMapInputs = this::_2200EditMapInputs;
    Consumer<OpenFrameContext> _2200EditMapInputsExit = this::_2200EditMapInputsExit;
    Consumer<OpenFrameContext> _2210EditAccount = this::_2210EditAccount;
    Consumer<OpenFrameContext> _2210EditAccountExit = this::_2210EditAccountExit;
    Consumer<OpenFrameContext> _2220EditCard = this::_2220EditCard;
    Consumer<OpenFrameContext> _2220EditCardExit = this::_2220EditCardExit;
    Consumer<OpenFrameContext> _9000ReadData = this::_9000ReadData;
    Consumer<OpenFrameContext> _9000ReadDataExit = this::_9000ReadDataExit;
    Consumer<OpenFrameContext> _9100GetcardByacctcard = this::_9100GetcardByacctcard;
    Consumer<OpenFrameContext> _9100GetcardByacctcardExit = this::_9100GetcardByacctcardExit;
    Consumer<OpenFrameContext> _9150GetcardByacct = this::_9150GetcardByacct;
    Consumer<OpenFrameContext> _9150GetcardByacctExit = this::_9150GetcardByacctExit;
    Consumer<OpenFrameContext> sendLongText = this::sendLongText;
    Consumer<OpenFrameContext> sendLongTextExit = this::sendLongTextExit;
    Consumer<OpenFrameContext> sendPlainText = this::sendPlainText;
    Consumer<OpenFrameContext> sendPlainTextExit = this::sendPlainTextExit;
    Consumer<OpenFrameContext> yyyyStorePfkey = this::yyyyStorePfkey;
    Consumer<OpenFrameContext> yyyyStorePfkeyExit = this::yyyyStorePfkeyExit;
    Consumer<OpenFrameContext> abendRoutine = this::abendRoutine;
    /** 
     * <p>execution flow of COBOL program that defined in the procedure division</p>
     */
    ArrayList<Consumer> methodList = new ArrayList<>();
    {
        methodList.add(_0000Main);
        methodList.add(commonReturn);
        methodList.add(_0000MainExit);
        methodList.add(_1000SendMap);
        methodList.add(_1000SendMapExit);
        methodList.add(_1100ScreenInit);
        methodList.add(_1100ScreenInitExit);
        methodList.add(_1200SetupScreenVars);
        methodList.add(_1200SetupScreenVarsExit);
        methodList.add(_1300SetupScreenAttrs);
        methodList.add(_1300SetupScreenAttrsExit);
        methodList.add(_1400SendScreen);
        methodList.add(_1400SendScreenExit);
        methodList.add(_2000ProcessInputs);
        methodList.add(_2000ProcessInputsExit);
        methodList.add(_2100ReceiveMap);
        methodList.add(_2100ReceiveMapExit);
        methodList.add(_2200EditMapInputs);
        methodList.add(_2200EditMapInputsExit);
        methodList.add(_2210EditAccount);
        methodList.add(_2210EditAccountExit);
        methodList.add(_2220EditCard);
        methodList.add(_2220EditCardExit);
        methodList.add(_9000ReadData);
        methodList.add(_9000ReadDataExit);
        methodList.add(_9100GetcardByacctcard);
        methodList.add(_9100GetcardByacctcardExit);
        methodList.add(_9150GetcardByacct);
        methodList.add(_9150GetcardByacctExit);
        methodList.add(sendLongText);
        methodList.add(sendLongTextExit);
        methodList.add(sendPlainText);
        methodList.add(sendPlainTextExit);
        methodList.add(yyyyStorePfkey);
        methodList.add(yyyyStorePfkeyExit);
        methodList.add(abendRoutine);
    }

    /** 
     * <p>method for executing a program logic that defined in the procedure division</p>
     * @param generalContext context that is necessary for executing program
     * @return return value of program
     */
    public int run(Map<String, Object> generalContext) {
        OpenFrameContext context = new OpenFrameContext(generalContext,
                methodList);
        if (context.getProgramVariableContainer("Cocrdslc") == null) {
            CocrdslcVariableContainer container = new CocrdslcVariableContainer();
            context.setProgramVariableContainer("Cocrdslc", container);
        }
        controlManager.run(context);
        return context.getReturnValue();
    }

    // ***************************************************************** 
    // * Program:     COCRDSLC.CBL                                     * 
    // * Layer:       Business logic                                   * 
    // * Function:    Accept and process credit card detail request    * 
    // ******************************************************************
    // * Copyright Amazon.com, Inc. or its affiliates.                   
    // * All Rights Reserved.                                            
    // *                                                                 
    // * Licensed under the Apache License, Version 2.0 (the "License"). 
    // * You may not use this file except in compliance with the License.
    // * You may obtain a copy of the License at                         
    // *                                                                 
    // *    http://www.apache.org/licenses/LICENSE-2.0                   
    // *                                                                 
    // * Unless required by applicable law or agreed to in writing,      
    // * software distributed under the License is distributed on an     
    // * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,    
    // * either express or implied. See the License for the specific     
    // * language governing permissions and limitations under the License
    // ******************************************************************
    // *      OCCURS 1 TO 32767 TIMES DEPENDING ON EIBCALEN.             

    void _0000Main(OpenFrameContext context) {
        CocrdslcVariableContainer container = (CocrdslcVariableContainer) context
                .getProgramVariableContainer("Cocrdslc");
        // [T-Up#INFO][COCRDSLC.cbl, LINE #250] EXEC_CICS statement
        /*
                       EXEC CICS HANDLE ABEND                                       
                                 LABEL(ABEND-ROUTINE)                               
                       END-EXEC
         */
        abendHandler.setLabel(abendRoutine);
        // [T-Up#INFO][COCRDSLC.cbl, LINE #254] INITIALIZE statement
        container.getCcWorkAreas().setCcWorkArea(
                CocrdslcCcWorkAreas.CocrdslcCcWorkArea
                        .createDefaultValueInstance());
        container.setWsMiscStorage(CocrdslcWsMiscStorage
                .createDefaultValueInstance());
        container.setWsCommarea(StringUtils.repeat(' ', 2000));
        // ***************************************************************** 
        // * Store our context                                               
        // ***************************************************************** 
        // [T-Up#INFO][COCRDSLC.cbl, LINE #260] MOVE statement
        container.getWsMiscStorage().getWsCicsProcessngVars()
                .setWsTranid(container.getWsLiterals().getLitThistranid());
        // ***************************************************************** 
        // * Ensure error message is cleared                               * 
        // ***************************************************************** 
        // [T-Up#INFO][COCRDSLC.cbl, LINE #264] SET statement
        container.getWsMiscStorage().setWsReturnMsg(WS_RETURN_MSG_OFF);
        // ***************************************************************** 
        // * Store passed data if  any                *                      
        // ***************************************************************** 
        // [T-Up#INFO][COCRDSLC.cbl, LINE #268] IF statement
        if (task.hasCommarea() == 0
                || CobStringUtils.compare(container.getCarddemoCommarea()
                        .getCdemoGeneralInfo().getCdemoFromProgram(), container
                        .getWsLiterals().getLitMenupgm()) == 0
                && !(container.getCarddemoCommarea().getCdemoGeneralInfo()
                        .getCdemoPgmContext() == CDEMO_PGM_REENTER)) {
            // [T-Up#INFO][COCRDSLC.cbl, LINE #271] INITIALIZE statement
            container.setCarddemoCommarea(CocrdslcCarddemoCommarea
                    .createDefaultValueInstance());
            container.setWsThisProgcommarea(CocrdslcWsThisProgcommarea
                    .createDefaultValueInstance());
        } else {
            // [T-Up#INFO][COCRDSLC.cbl, LINE #274] MOVE statement
            container.getCarddemoCommarea().set(
                    container.getDfhcommarea().get().substring(0, 160));
            // [T-Up#INFO][COCRDSLC.cbl, LINE #276] MOVE statement
            container.getWsThisProgcommarea().set(
                    container.getDfhcommarea().get().substring(160, 172));
        }
        // ***************************************************************** 
        // * Remap PFkeys as needed.                                         
        // * Store the Mapped PF Key                                         
        // ***************************************************************** 
        // [T-Up#INFO][COCRDSLC.cbl, LINE #284] PERFORM statement
        controlManager.run(context, yyyyStorePfkey, yyyyStorePfkeyExit);
        if (controlManager.isTerminate(context)) {
            return;
        }
        // ***************************************************************** 
        // * Check the AID to see if its valid at this point               * 
        // * F3 - Exit                                                       
        // * Enter show screen again                                         
        // ***************************************************************** 
        // [T-Up#INFO][COCRDSLC.cbl, LINE #291] SET statement
        container.getWsMiscStorage().setWsPfkFlag(PFK_INVALID);
        // [T-Up#INFO][COCRDSLC.cbl, LINE #292] IF statement
        if (CobStringUtils.compare(container.getCcWorkAreas().getCcWorkArea()
                .getCcardAid(), CCARD_AID_ENTER) == 0
                || CobStringUtils.compare(container.getCcWorkAreas()
                        .getCcWorkArea().getCcardAid(), CCARD_AID_PFK03) == 0) {
            // [T-Up#INFO][COCRDSLC.cbl, LINE #294] SET statement
            container.getWsMiscStorage().setWsPfkFlag(PFK_VALID);
        }
        // [T-Up#INFO][COCRDSLC.cbl, LINE #297] IF statement
        if (CobStringUtils.compare(container.getWsMiscStorage().getWsPfkFlag(),
                PFK_INVALID) == 0) {
            // [T-Up#INFO][COCRDSLC.cbl, LINE #298] SET statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcardAid(CCARD_AID_ENTER);
        }
        // ***************************************************************** 
        // * Decide what to do based on inputs received                      
        // ***************************************************************** 
        // [T-Up#INFO][COCRDSLC.cbl, LINE #304] EVALUATE statement
        if (CobStringUtils.compare(container.getCcWorkAreas().getCcWorkArea()
                .getCcardAid(), CCARD_AID_PFK03) == 0) {
            // ******************************************************************
            // *            XCTL TO CALLING PROGRAM OR MAIN MENU                 
            // ******************************************************************
            // [T-Up#INFO][COCRDSLC.cbl, LINE #309] IF statement
            if (CobStringUtils.compare(container.getCarddemoCommarea()
                    .getCdemoGeneralInfo().getCdemoFromTranid(),
                    StringUtils.repeat((char) 0x00, 4)) == 0
                    || CobStringUtils.compare(container.getCarddemoCommarea()
                            .getCdemoGeneralInfo().getCdemoFromTranid(),
                            StringUtils.repeat(' ', 4)) == 0) {
                // [T-Up#INFO][COCRDSLC.cbl, LINE #311] MOVE statement
                container
                        .getCarddemoCommarea()
                        .getCdemoGeneralInfo()
                        .setCdemoToTranid(
                                container.getWsLiterals().getLitMenutranid());
            } else {
                // [T-Up#INFO][COCRDSLC.cbl, LINE #313] MOVE statement
                container
                        .getCarddemoCommarea()
                        .getCdemoGeneralInfo()
                        .setCdemoToTranid(
                                container.getCarddemoCommarea()
                                        .getCdemoGeneralInfo()
                                        .getCdemoFromTranid());
            }
            // [T-Up#INFO][COCRDSLC.cbl, LINE #316] IF statement
            if (CobStringUtils.compare(container.getCarddemoCommarea()
                    .getCdemoGeneralInfo().getCdemoFromProgram(),
                    StringUtils.repeat((char) 0x00, 8)) == 0
                    || CobStringUtils.compare(container.getCarddemoCommarea()
                            .getCdemoGeneralInfo().getCdemoFromProgram(),
                            StringUtils.repeat(' ', 8)) == 0) {
                // [T-Up#INFO][COCRDSLC.cbl, LINE #318] MOVE statement
                container
                        .getCarddemoCommarea()
                        .getCdemoGeneralInfo()
                        .setCdemoToProgram(
                                container.getWsLiterals().getLitMenupgm());
            } else {
                // [T-Up#INFO][COCRDSLC.cbl, LINE #320] MOVE statement
                container
                        .getCarddemoCommarea()
                        .getCdemoGeneralInfo()
                        .setCdemoToProgram(
                                container.getCarddemoCommarea()
                                        .getCdemoGeneralInfo()
                                        .getCdemoFromProgram());
            }
            // [T-Up#INFO][COCRDSLC.cbl, LINE #323] MOVE statement
            container
                    .getCarddemoCommarea()
                    .getCdemoGeneralInfo()
                    .setCdemoFromTranid(
                            container.getWsLiterals().getLitThistranid());
            // [T-Up#INFO][COCRDSLC.cbl, LINE #324] MOVE statement
            container
                    .getCarddemoCommarea()
                    .getCdemoGeneralInfo()
                    .setCdemoFromProgram(
                            container.getWsLiterals().getLitThispgm());
            // [T-Up#INFO][COCRDSLC.cbl, LINE #326] SET statement
            container.getCarddemoCommarea().getCdemoGeneralInfo()
                    .setCdemoUserType(CDEMO_USRTYP_USER);
            // [T-Up#INFO][COCRDSLC.cbl, LINE #327] SET statement
            container.getCarddemoCommarea().getCdemoGeneralInfo()
                    .setCdemoPgmContext(CDEMO_PGM_ENTER);
            // [T-Up#INFO][COCRDSLC.cbl, LINE #328] MOVE statement
            container
                    .getCarddemoCommarea()
                    .getCdemoMoreInfo()
                    .setCdemoLastMapset(
                            container.getWsLiterals().getLitThismapset());
            // [T-Up#INFO][COCRDSLC.cbl, LINE #329] MOVE statement
            container.getCarddemoCommarea().getCdemoMoreInfo()
                    .setCdemoLastMap(container.getWsLiterals().getLitThismap());
            // [T-Up#INFO][COCRDSLC.cbl, LINE #330] IF statement
            if (CobStringUtils.compare(container.getCarddemoCommarea()
                    .getCdemoGeneralInfo().getCdemoToProgram(), "COCRDLIC") == 0) {
                // [T-Up#INFO][COCRDSLC.cbl, LINE #331] EXEC_CICS statement
                /*
                                           EXEC CICS                                        
                                           XCTL PROGRAM('COCRDLIC')                         
                                           COMMAREA(CARDDEMO-COMMAREA)                      
                                           END-EXEC
                 */
                CocrdlicInputDto cocrdlicInputDto = new CocrdlicInputDto();
                cocrdlicInputDto
                        .setDfhcommarea(CocrdslcCarddemoCommareaToCocrdlicDfhcommarea.INSTANCE
                                .toTarget(container.getCarddemoCommarea()));
                programControl.forward("CCLI", cocrdlicInputDto);
                context.setReturnFlag(true);
            } else {
                // [T-Up#INFO][COCRDSLC.cbl, LINE #335] IF statement
                if (CobStringUtils.compare(container.getCarddemoCommarea()
                        .getCdemoGeneralInfo().getCdemoToProgram(), "COMEN01C") == 0) {
                    // [T-Up#INFO][COCRDSLC.cbl, LINE #336] EXEC_CICS statement
                    /*
                                               EXEC CICS                                        
                                               XCTL PROGRAM('COMEN01C')                         
                                               COMMAREA(CARDDEMO-COMMAREA)                      
                                               END-EXEC
                     */
                    Comen01cInputDto comen01cInputDto = new Comen01cInputDto();
                    comen01cInputDto
                            .setDfhcommarea(CocrdslcCarddemoCommareaToComen01cDfhcommarea.INSTANCE
                                    .toTarget(container.getCarddemoCommarea()));
                    programControl.forward("CM00", comen01cInputDto);
                    context.setReturnFlag(true);
                }
            }
        } else if (container.getCarddemoCommarea().getCdemoGeneralInfo()
                .getCdemoPgmContext() == CDEMO_PGM_ENTER
                && CobStringUtils.compare(container.getCarddemoCommarea()
                        .getCdemoGeneralInfo().getCdemoFromProgram(), container
                        .getWsLiterals().getLitCclistpgm()) == 0) {
            // ******************************************************************
            // *            COMING FROM CREDIT CARD LIST SCREEN                  
            // *            SELECTION CRITERIA ALREADY VALIDATED                 
            // ******************************************************************
            // [T-Up#INFO][COCRDSLC.cbl, LINE #347] SET statement
            container.getWsMiscStorage().setWsInputFlag(INPUT_OK);
            // [T-Up#INFO][COCRDSLC.cbl, LINE #348] MOVE statement
            container
                    .getCcWorkAreas()
                    .getCcWorkArea()
                    .setCcAcctIdN(
                            container.getCarddemoCommarea()
                                    .getCdemoAccountInfo().getCdemoAcctId());
            // [T-Up#INFO][COCRDSLC.cbl, LINE #349] MOVE statement
            container
                    .getCcWorkAreas()
                    .getCcWorkArea()
                    .setCcCardNumN(
                            container.getCarddemoCommarea().getCdemoCardInfo()
                                    .getCdemoCardNum());
            // [T-Up#INFO][COCRDSLC.cbl, LINE #350] PERFORM statement
            controlManager.run(context, _9000ReadData, _9000ReadDataExit);
            if (controlManager.isTerminate(context)) {
                return;
            }
            // [T-Up#INFO][COCRDSLC.cbl, LINE #352] PERFORM statement
            controlManager.run(context, _1000SendMap, _1000SendMapExit);
            if (controlManager.isTerminate(context)) {
                return;
            }
            // [T-Up#INFO][COCRDSLC.cbl, LINE #354] GOTO statement
            context.setGotoTarget(commonReturn);
            return;
        } else if (container.getCarddemoCommarea().getCdemoGeneralInfo()
                .getCdemoPgmContext() == CDEMO_PGM_ENTER) {
            // ******************************************************************
            // *            COMING FROM SOME OTHER CONTEXT                       
            // *            SELECTION CRITERIA TO BE GATHERED                    
            // ******************************************************************
            // [T-Up#INFO][COCRDSLC.cbl, LINE #360] PERFORM statement
            controlManager.run(context, _1000SendMap, _1000SendMapExit);
            if (controlManager.isTerminate(context)) {
                return;
            }
            // [T-Up#INFO][COCRDSLC.cbl, LINE #362] GOTO statement
            context.setGotoTarget(commonReturn);
            return;
        } else if (container.getCarddemoCommarea().getCdemoGeneralInfo()
                .getCdemoPgmContext() == CDEMO_PGM_REENTER) {
            // [T-Up#INFO][COCRDSLC.cbl, LINE #364] PERFORM statement
            controlManager.run(context, _2000ProcessInputs,
                    _2000ProcessInputsExit);
            if (controlManager.isTerminate(context)) {
                return;
            }
            // [T-Up#INFO][COCRDSLC.cbl, LINE #366] IF statement
            if (CobStringUtils.compare(container.getWsMiscStorage()
                    .getWsInputFlag(), INPUT_ERROR) == 0) {
                // [T-Up#INFO][COCRDSLC.cbl, LINE #367] PERFORM statement
                controlManager.run(context, _1000SendMap, _1000SendMapExit);
                if (controlManager.isTerminate(context)) {
                    return;
                }
                // [T-Up#INFO][COCRDSLC.cbl, LINE #369] GOTO statement
                context.setGotoTarget(commonReturn);
                return;
            } else {
                // [T-Up#INFO][COCRDSLC.cbl, LINE #371] PERFORM statement
                controlManager.run(context, _9000ReadData, _9000ReadDataExit);
                if (controlManager.isTerminate(context)) {
                    return;
                }
                // [T-Up#INFO][COCRDSLC.cbl, LINE #373] PERFORM statement
                controlManager.run(context, _1000SendMap, _1000SendMapExit);
                if (controlManager.isTerminate(context)) {
                    return;
                }
                // [T-Up#INFO][COCRDSLC.cbl, LINE #375] GOTO statement
                context.setGotoTarget(commonReturn);
                return;
            }
        } else {
            // [T-Up#INFO][COCRDSLC.cbl, LINE #380] MOVE statement
            container.getAbendData().setAbendCulprit(
                    container.getWsLiterals().getLitThispgm());
            // [T-Up#INFO][COCRDSLC.cbl, LINE #381] MOVE statement
            container.getAbendData().setAbendCode("0001");
            // [T-Up#INFO][COCRDSLC.cbl, LINE #382] MOVE statement
            container.getAbendData()
                    .setAbendReason(StringUtils.repeat(' ', 50));
            // [T-Up#INFO][COCRDSLC.cbl, LINE #383] MOVE statement
            container.getWsMiscStorage().setWsReturnMsg(
                    "UNEXPECTED DATA SCENARIO");
            // [T-Up#INFO][COCRDSLC.cbl, LINE #385] PERFORM statement
            controlManager.run(context, sendPlainText, sendPlainTextExit);
            if (controlManager.isTerminate(context)) {
                return;
            }
        }
        // * If we had an error setup error message that slipped through     
        // * Display and return                                              
        // [T-Up#INFO][COCRDSLC.cbl, LINE #392] IF statement
        if (CobStringUtils.compare(container.getWsMiscStorage()
                .getWsInputFlag(), INPUT_ERROR) == 0) {
            // [T-Up#INFO][COCRDSLC.cbl, LINE #393] MOVE statement
            container
                    .getCcWorkAreas()
                    .getCcWorkArea()
                    .setCcardErrorMsg(
                            container.getWsMiscStorage().getWsReturnMsg());
            // [T-Up#INFO][COCRDSLC.cbl, LINE #394] PERFORM statement
            controlManager.run(context, _1000SendMap, _1000SendMapExit);
            if (controlManager.isTerminate(context)) {
                return;
            }
            // [T-Up#INFO][COCRDSLC.cbl, LINE #396] GOTO statement
            context.setGotoTarget(commonReturn);
            return;
        }
    }

    void commonReturn(OpenFrameContext context) {
        CocrdslcVariableContainer container = (CocrdslcVariableContainer) context
                .getProgramVariableContainer("Cocrdslc");
        // [T-Up#INFO][COCRDSLC.cbl, LINE #401] MOVE statement
        container
                .getCcWorkAreas()
                .getCcWorkArea()
                .setCcardErrorMsg(container.getWsMiscStorage().getWsReturnMsg());
        // [T-Up#INFO][COCRDSLC.cbl, LINE #403] MOVE statement
        container.setWsCommarea(container.getCarddemoCommarea().get());
        // [T-Up#INFO][COCRDSLC.cbl, LINE #404] MOVE statement
        container.setWsCommarea(StringUtils.overlay(container.getWsCommarea(),
                container.getWsThisProgcommarea().get(), 160, 172));
        // [T-Up#INFO][COCRDSLC.cbl, LINE #408] EXEC_CICS statement
        /*
                       EXEC CICS RETURN                                             
                            TRANSID (LIT-THISTRANID)                                
                            COMMAREA (WS-COMMAREA)                                  
                            LENGTH(LENGTH OF WS-COMMAREA)                           
                       END-EXEC
         */
        TaskDto taskDto = TaskDto.builder()
                .destination(container.getWsLiterals().getLitThistranid())
                .data(Data.session(container.getWsCommarea())).build();
        taskInvoker.setNextTask(taskDto);
        context.setReturnFlag(true);
    }

    void _0000MainExit(OpenFrameContext context) {
        // [T-Up#INFO][COCRDSLC.cbl, LINE #415] EXIT statement
    }

    void _1000SendMap(OpenFrameContext context) {
        // [T-Up#INFO][COCRDSLC.cbl, LINE #419] PERFORM statement
        controlManager.run(context, _1100ScreenInit, _1100ScreenInitExit);
        if (controlManager.isTerminate(context)) {
            return;
        }
        // [T-Up#INFO][COCRDSLC.cbl, LINE #421] PERFORM statement
        controlManager.run(context, _1200SetupScreenVars,
                _1200SetupScreenVarsExit);
        if (controlManager.isTerminate(context)) {
            return;
        }
        // [T-Up#INFO][COCRDSLC.cbl, LINE #423] PERFORM statement
        controlManager.run(context, _1300SetupScreenAttrs,
                _1300SetupScreenAttrsExit);
        if (controlManager.isTerminate(context)) {
            return;
        }
        // [T-Up#INFO][COCRDSLC.cbl, LINE #425] PERFORM statement
        controlManager.run(context, _1400SendScreen, _1400SendScreenExit);
        if (controlManager.isTerminate(context)) {
            return;
        }
    }

    void _1000SendMapExit(OpenFrameContext context) {
        // [T-Up#INFO][COCRDSLC.cbl, LINE #430] EXIT statement
    }

    void _1100ScreenInit(OpenFrameContext context) {
        CocrdslcVariableContainer container = (CocrdslcVariableContainer) context
                .getProgramVariableContainer("Cocrdslc");
        // [T-Up#INFO][COCRDSLC.cbl, LINE #434] MOVE statement
        container.setCcrdslao(CocrdslcCcrdslai.createDefaultValueInstance()
                .get());
        // [T-Up#INFO][COCRDSLC.cbl, LINE #436] MOVE statement
        container.getWsDateTime().getWsCurdateData()
                .set(IntrinsicFunction.functionCurrentDate());
        // [T-Up#INFO][COCRDSLC.cbl, LINE #438] MOVE statement
        container.setTitle01o(container.getCcdaScreenTitle().getCcdaTitle01());
        // [T-Up#INFO][COCRDSLC.cbl, LINE #439] MOVE statement
        container.setTitle02o(container.getCcdaScreenTitle().getCcdaTitle02());
        // [T-Up#INFO][COCRDSLC.cbl, LINE #440] MOVE statement
        container.setTrnnameo(container.getWsLiterals().getLitThistranid());
        // [T-Up#INFO][COCRDSLC.cbl, LINE #441] MOVE statement
        container.setPgmnameo(container.getWsLiterals().getLitThispgm());
        // [T-Up#INFO][COCRDSLC.cbl, LINE #443] MOVE statement
        container.getWsDateTime().getWsCurdateData()
                .set(IntrinsicFunction.functionCurrentDate());
        // [T-Up#INFO][COCRDSLC.cbl, LINE #445] MOVE statement
        container
                .getWsDateTime()
                .getWsCurdateMmDdYy()
                .setWsCurdateMm(
                        container.getWsDateTime().getWsCurdateData()
                                .getWsCurdate().getWsCurdateMonth());
        // [T-Up#INFO][COCRDSLC.cbl, LINE #446] MOVE statement
        container
                .getWsDateTime()
                .getWsCurdateMmDdYy()
                .setWsCurdateDd(
                        container.getWsDateTime().getWsCurdateData()
                                .getWsCurdate().getWsCurdateDay());
        // [T-Up#INFO][COCRDSLC.cbl, LINE #447] MOVE statement
        container
                .getWsDateTime()
                .getWsCurdateMmDdYy()
                .setWsCurdateYy(
                        Integer.parseInt(DataConverter
                                .convZonedLongToString(
                                        container.getWsDateTime()
                                                .getWsCurdateData()
                                                .getWsCurdate()
                                                .getWsCurdateYear(), 4)
                                .substring(2, 4).trim()));
        // [T-Up#INFO][COCRDSLC.cbl, LINE #449] MOVE statement
        container.setCurdateo(container.getWsDateTime().getWsCurdateMmDdYy()
                .get());
        // [T-Up#INFO][COCRDSLC.cbl, LINE #451] MOVE statement
        container
                .getWsDateTime()
                .getWsCurtimeHhMmSs()
                .setWsCurtimeHh(
                        container.getWsDateTime().getWsCurdateData()
                                .getWsCurtime().getWsCurtimeHours());
        // [T-Up#INFO][COCRDSLC.cbl, LINE #452] MOVE statement
        container
                .getWsDateTime()
                .getWsCurtimeHhMmSs()
                .setWsCurtimeMm(
                        container.getWsDateTime().getWsCurdateData()
                                .getWsCurtime().getWsCurtimeMinute());
        // [T-Up#INFO][COCRDSLC.cbl, LINE #453] MOVE statement
        container
                .getWsDateTime()
                .getWsCurtimeHhMmSs()
                .setWsCurtimeSs(
                        container.getWsDateTime().getWsCurdateData()
                                .getWsCurtime().getWsCurtimeSecond());
        // [T-Up#INFO][COCRDSLC.cbl, LINE #455] MOVE statement
        container.setCurtimeo(container.getWsDateTime().getWsCurtimeHhMmSs()
                .get());
    }

    void _1100ScreenInitExit(OpenFrameContext context) {
        // [T-Up#INFO][COCRDSLC.cbl, LINE #460] EXIT statement
    }

    void _1200SetupScreenVars(OpenFrameContext context) {
        CocrdslcVariableContainer container = (CocrdslcVariableContainer) context
                .getProgramVariableContainer("Cocrdslc");
        // *    INITIALIZE SEARCH CRITERIA                                   
        // [T-Up#INFO][COCRDSLC.cbl, LINE #465] IF statement
        if (task.hasCommarea() == 0) {
            // [T-Up#INFO][COCRDSLC.cbl, LINE #466] SET statement
            container.getWsMiscStorage().setWsInfoMsg(WS_PROMPT_FOR_INPUT);
        } else {
            // [T-Up#INFO][COCRDSLC.cbl, LINE #468] IF statement
            if (container.getCarddemoCommarea().getCdemoAccountInfo()
                    .getCdemoAcctId() == 0) {
                // [T-Up#INFO][COCRDSLC.cbl, LINE #469] MOVE statement
                container.setAcctsido(StringUtils.repeat((char) 0x00, 11));
            } else {
                // [T-Up#INFO][COCRDSLC.cbl, LINE #471] MOVE statement
                container.setAcctsido(container.getCcWorkAreas()
                        .getCcWorkArea().getCcAcctId());
            }
            // [T-Up#INFO][COCRDSLC.cbl, LINE #474] IF statement
            if (container.getCarddemoCommarea().getCdemoCardInfo()
                    .getCdemoCardNum() == 0) {
                // [T-Up#INFO][COCRDSLC.cbl, LINE #475] MOVE statement
                container.setCardsido(StringUtils.repeat((char) 0x00, 16));
            } else {
                // [T-Up#INFO][COCRDSLC.cbl, LINE #477] MOVE statement
                container.setCardsido(container.getCcWorkAreas()
                        .getCcWorkArea().getCcCardNum());
            }
            // [T-Up#INFO][COCRDSLC.cbl, LINE #480] IF statement
            if (CobStringUtils.compare(container.getWsMiscStorage()
                    .getWsInfoMsg(), FOUND_CARDS_FOR_ACCOUNT) == 0) {
                // [T-Up#INFO][COCRDSLC.cbl, LINE #481] MOVE statement
                container.setCrdnameo(container.getCardRecord()
                        .getCardEmbossedName());
                // [T-Up#INFO][COCRDSLC.cbl, LINE #483] MOVE statement
                container
                        .getWsMiscStorage()
                        .getCicsOutputEditVars()
                        .setCardExpiraionDateX(
                                container.getCardRecord()
                                        .getCardExpiraionDate());
                // [T-Up#INFO][COCRDSLC.cbl, LINE #486] MOVE statement
                container.setExpmono(container.getWsMiscStorage()
                        .getCicsOutputEditVars().getCardExpiryMonth());
                // [T-Up#INFO][COCRDSLC.cbl, LINE #488] MOVE statement
                container.setExpyearo(container.getWsMiscStorage()
                        .getCicsOutputEditVars().getCardExpiryYear());
                // [T-Up#INFO][COCRDSLC.cbl, LINE #490] MOVE statement
                container.setCrdstcdo(container.getCardRecord()
                        .getCardActiveStatus());
            }
        }
        // *    SETUP MESSAGE                                                
        // [T-Up#INFO][COCRDSLC.cbl, LINE #496] IF statement
        if (CobStringUtils.compare(container.getWsMiscStorage().getWsInfoMsg(),
                WS_NO_INFO_MESSAGE_1) == 0
                || CobStringUtils.compare(container.getWsMiscStorage()
                        .getWsInfoMsg(), WS_NO_INFO_MESSAGE_2) == 0) {
            // [T-Up#INFO][COCRDSLC.cbl, LINE #497] SET statement
            container.getWsMiscStorage().setWsInfoMsg(WS_PROMPT_FOR_INPUT);
        }
        // [T-Up#INFO][COCRDSLC.cbl, LINE #500] MOVE statement
        container.setErrmsgo(container.getWsMiscStorage().getWsReturnMsg());
        // [T-Up#INFO][COCRDSLC.cbl, LINE #502] MOVE statement
        container.setInfomsgo(container.getWsMiscStorage().getWsInfoMsg());
    }

    void _1200SetupScreenVarsExit(OpenFrameContext context) {
        // [T-Up#INFO][COCRDSLC.cbl, LINE #506] EXIT statement
    }

    void _1300SetupScreenAttrs(OpenFrameContext context) {
        CocrdslcVariableContainer container = (CocrdslcVariableContainer) context
                .getProgramVariableContainer("Cocrdslc");
        // *    PROTECT OR UNPROTECT BASED ON CONTEXT                        
        // [T-Up#INFO][COCRDSLC.cbl, LINE #511] IF statement
        if (CobStringUtils.compare(container.getCarddemoCommarea()
                .getCdemoMoreInfo().getCdemoLastMapset(), container
                .getWsLiterals().getLitCclistmapset()) == 0
                && CobStringUtils.compare(container.getCarddemoCommarea()
                        .getCdemoGeneralInfo().getCdemoFromProgram(), container
                        .getWsLiterals().getLitCclistpgm()) == 0) {
            // [T-Up#INFO][COCRDSLC.cbl, LINE #513] MOVE statement
            container.getCcrdslai().setAcctsida(
                    container.getDfhbmsca().getDfhbmprf());
            // [T-Up#INFO][COCRDSLC.cbl, LINE #514] MOVE statement
            container.getCcrdslai().setCardsida(
                    container.getDfhbmsca().getDfhbmprf());
        } else {
            // [T-Up#INFO][COCRDSLC.cbl, LINE #516] MOVE statement
            container.getCcrdslai().setAcctsida(
                    container.getDfhbmsca().getDfhbmfse());
            // [T-Up#INFO][COCRDSLC.cbl, LINE #517] MOVE statement
            container.getCcrdslai().setCardsida(
                    container.getDfhbmsca().getDfhbmfse());
        }
        // *    POSITION CURSOR                                              
        // [T-Up#INFO][COCRDSLC.cbl, LINE #521] EVALUATE statement
        if ((CobStringUtils.compare(container.getWsMiscStorage()
                .getWsEditAcctFlag(), FLG_ACCTFILTER_NOT_OK) == 0)
                || (CobStringUtils.compare(container.getWsMiscStorage()
                        .getWsEditAcctFlag(), FLG_ACCTFILTER_BLANK) == 0)) {
            // [T-Up#INFO][COCRDSLC.cbl, LINE #524] MOVE statement
            container.getCcrdslai().setAcctsidl(-1);
        } else if ((CobStringUtils.compare(container.getWsMiscStorage()
                .getWsEditCardFlag(), FLG_CARDFILTER_NOT_OK) == 0)
                || (CobStringUtils.compare(container.getWsMiscStorage()
                        .getWsEditCardFlag(), FLG_CARDFILTER_BLANK) == 0)) {
            // [T-Up#INFO][COCRDSLC.cbl, LINE #527] MOVE statement
            container.getCcrdslai().setCardsidl(-1);
        } else {
            // [T-Up#INFO][COCRDSLC.cbl, LINE #529] MOVE statement
            container.getCcrdslai().setAcctsidl(-1);
        }
        // *    SETUP COLOR                                                  
        // [T-Up#INFO][COCRDSLC.cbl, LINE #533] IF statement
        if (CobStringUtils.compare(container.getCarddemoCommarea()
                .getCdemoMoreInfo().getCdemoLastMapset(), container
                .getWsLiterals().getLitCclistmapset()) == 0
                && CobStringUtils.compare(container.getCarddemoCommarea()
                        .getCdemoGeneralInfo().getCdemoFromProgram(), container
                        .getWsLiterals().getLitCclistpgm()) == 0) {
            // [T-Up#INFO][COCRDSLC.cbl, LINE #535] MOVE statement
            container.setAcctsidc(container.getDfhbmsca().getDfhdfcol());
            // [T-Up#INFO][COCRDSLC.cbl, LINE #536] MOVE statement
            container.setCardsidc(container.getDfhbmsca().getDfhdfcol());
        }
        // [T-Up#INFO][COCRDSLC.cbl, LINE #539] IF statement
        if (CobStringUtils.compare(container.getWsMiscStorage()
                .getWsEditAcctFlag(), FLG_ACCTFILTER_NOT_OK) == 0) {
            // [T-Up#INFO][COCRDSLC.cbl, LINE #540] MOVE statement
            container.setAcctsidc(container.getDfhbmsca().getDfhred());
        }
        // [T-Up#INFO][COCRDSLC.cbl, LINE #543] IF statement
        if (CobStringUtils.compare(container.getWsMiscStorage()
                .getWsEditCardFlag(), FLG_CARDFILTER_NOT_OK) == 0) {
            // [T-Up#INFO][COCRDSLC.cbl, LINE #544] MOVE statement
            container.setCardsidc(container.getDfhbmsca().getDfhred());
        }
        // [T-Up#INFO][COCRDSLC.cbl, LINE #547] IF statement
        if (CobStringUtils.compare(container.getWsMiscStorage()
                .getWsEditAcctFlag(), FLG_ACCTFILTER_BLANK) == 0
                && container.getCarddemoCommarea().getCdemoGeneralInfo()
                        .getCdemoPgmContext() == CDEMO_PGM_REENTER) {
            // [T-Up#INFO][COCRDSLC.cbl, LINE #549] MOVE statement
            container.setAcctsido("*");
            // [T-Up#INFO][COCRDSLC.cbl, LINE #550] MOVE statement
            container.setAcctsidc(container.getDfhbmsca().getDfhred());
        }
        // [T-Up#INFO][COCRDSLC.cbl, LINE #553] IF statement
        if (CobStringUtils.compare(container.getWsMiscStorage()
                .getWsEditCardFlag(), FLG_CARDFILTER_BLANK) == 0
                && container.getCarddemoCommarea().getCdemoGeneralInfo()
                        .getCdemoPgmContext() == CDEMO_PGM_REENTER) {
            // [T-Up#INFO][COCRDSLC.cbl, LINE #555] MOVE statement
            container.setCardsido("*");
            // [T-Up#INFO][COCRDSLC.cbl, LINE #556] MOVE statement
            container.setCardsidc(container.getDfhbmsca().getDfhred());
        }
        // [T-Up#INFO][COCRDSLC.cbl, LINE #559] IF statement
        if (CobStringUtils.compare(container.getWsMiscStorage().getWsInfoMsg(),
                WS_NO_INFO_MESSAGE_1) == 0
                || CobStringUtils.compare(container.getWsMiscStorage()
                        .getWsInfoMsg(), WS_NO_INFO_MESSAGE_2) == 0) {
            // [T-Up#INFO][COCRDSLC.cbl, LINE #560] MOVE statement
            container.setInfomsgc(container.getDfhbmsca().getDfhbmdar());
        } else {
            // [T-Up#INFO][COCRDSLC.cbl, LINE #562] MOVE statement
            container.setInfomsgc(container.getDfhbmsca().getDfhneutr());
        }
    }

    void _1300SetupScreenAttrsExit(OpenFrameContext context) {
        // [T-Up#INFO][COCRDSLC.cbl, LINE #566] EXIT statement
    }

    void _1400SendScreen(OpenFrameContext context) {
        CocrdslcVariableContainer container = (CocrdslcVariableContainer) context
                .getProgramVariableContainer("Cocrdslc");
        // [T-Up#INFO][COCRDSLC.cbl, LINE #571] MOVE statement
        container
                .getCcWorkAreas()
                .getCcWorkArea()
                .setCcardNextMapset(
                        container.getWsLiterals().getLitThismapset());
        // [T-Up#INFO][COCRDSLC.cbl, LINE #572] MOVE statement
        container.getCcWorkAreas().getCcWorkArea()
                .setCcardNextMap(container.getWsLiterals().getLitThismap());
        // [T-Up#INFO][COCRDSLC.cbl, LINE #573] SET statement
        container.getCarddemoCommarea().getCdemoGeneralInfo()
                .setCdemoPgmContext(CDEMO_PGM_REENTER);
        // [T-Up#INFO][COCRDSLC.cbl, LINE #575] EXEC_CICS statement
        /*
                       EXEC CICS SEND MAP('CCRDSLA')                                
                                      MAPSET('COCRDSL')                             
                                      FROM(CCRDSLAO)                                
                                      CURSOR                                        
                                      ERASE                                         
                                      FREEKB                                        
                                      RESP(WS-RESP-CD)                              
                       END-EXEC
         */
        try {
            ((CocrdslcOutputDto) task.getOutputDto())
                    .setPageName("COCRDSL_CCRDSLA");
            ((CocrdslcOutputDto) task.getOutputDto()).setCcrdslao(container
                    .getCcrdslao());
        } catch (ConditionException e) {
        } finally {
            container.getWsMiscStorage().getWsCicsProcessngVars()
                    .setWsRespCd(task.getLastResp());
        }
    }

    void _1400SendScreenExit(OpenFrameContext context) {
        // [T-Up#INFO][COCRDSLC.cbl, LINE #585] EXIT statement
    }

    void _2000ProcessInputs(OpenFrameContext context) {
        CocrdslcVariableContainer container = (CocrdslcVariableContainer) context
                .getProgramVariableContainer("Cocrdslc");
        // [T-Up#INFO][COCRDSLC.cbl, LINE #589] PERFORM statement
        controlManager.run(context, _2100ReceiveMap, _2100ReceiveMapExit);
        if (controlManager.isTerminate(context)) {
            return;
        }
        // [T-Up#INFO][COCRDSLC.cbl, LINE #591] PERFORM statement
        controlManager.run(context, _2200EditMapInputs, _2200EditMapInputsExit);
        if (controlManager.isTerminate(context)) {
            return;
        }
        // [T-Up#INFO][COCRDSLC.cbl, LINE #593] MOVE statement
        container
                .getCcWorkAreas()
                .getCcWorkArea()
                .setCcardErrorMsg(container.getWsMiscStorage().getWsReturnMsg());
        // [T-Up#INFO][COCRDSLC.cbl, LINE #594] MOVE statement
        container.getCcWorkAreas().getCcWorkArea()
                .setCcardNextProg(container.getWsLiterals().getLitThispgm());
        // [T-Up#INFO][COCRDSLC.cbl, LINE #595] MOVE statement
        container
                .getCcWorkAreas()
                .getCcWorkArea()
                .setCcardNextMapset(
                        container.getWsLiterals().getLitThismapset());
        // [T-Up#INFO][COCRDSLC.cbl, LINE #596] MOVE statement
        container.getCcWorkAreas().getCcWorkArea()
                .setCcardNextMap(container.getWsLiterals().getLitThismap());
    }

    void _2000ProcessInputsExit(OpenFrameContext context) {
        // [T-Up#INFO][COCRDSLC.cbl, LINE #600] EXIT statement
    }

    void _2100ReceiveMap(OpenFrameContext context) {
        CocrdslcVariableContainer container = (CocrdslcVariableContainer) context
                .getProgramVariableContainer("Cocrdslc");
        // [T-Up#INFO][COCRDSLC.cbl, LINE #603] EXEC_CICS statement
        /*
                       EXEC CICS RECEIVE MAP('CCRDSLA')                             
                                 MAPSET('COCRDSL')                                  
                                 INTO(CCRDSLAI)                                     
                                 RESP(WS-RESP-CD)                                   
                                 RESP2(WS-REAS-CD)                                  
                       END-EXEC
         */
        try {
            container.setCcrdslai(((CocrdslcInputDto) task.getInputDto())
                    .getCcrdslai());
        } catch (ConditionException e) {
        } finally {
            container.getWsMiscStorage().getWsCicsProcessngVars()
                    .setWsRespCd(task.getLastResp());
            container.getWsMiscStorage().getWsCicsProcessngVars()
                    .setWsReasCd(task.getLastResp2());
        }
    }

    void _2100ReceiveMapExit(OpenFrameContext context) {
        // [T-Up#INFO][COCRDSLC.cbl, LINE #612] EXIT statement
    }

    void _2200EditMapInputs(OpenFrameContext context) {
        CocrdslcVariableContainer container = (CocrdslcVariableContainer) context
                .getProgramVariableContainer("Cocrdslc");
        // [T-Up#INFO][COCRDSLC.cbl, LINE #616] SET statement
        container.getWsMiscStorage().setWsInputFlag(INPUT_OK);
        // [T-Up#INFO][COCRDSLC.cbl, LINE #617] SET statement
        container.getWsMiscStorage().setWsEditCardFlag(FLG_CARDFILTER_ISVALID);
        // [T-Up#INFO][COCRDSLC.cbl, LINE #618] SET statement
        container.getWsMiscStorage().setWsEditAcctFlag(FLG_ACCTFILTER_ISVALID);
        // *    REPLACE * WITH LOW-VALUES                                    
        // [T-Up#INFO][COCRDSLC.cbl, LINE #621] IF statement
        if (CobStringUtils.compare(container.getCcrdslai().getAcctsidi(), "*") == 0
                || CobStringUtils.compare(
                        container.getCcrdslai().getAcctsidi(),
                        StringUtils.repeat(' ', 11)) == 0) {
            // [T-Up#INFO][COCRDSLC.cbl, LINE #623] MOVE statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcAcctId(StringUtils.repeat((char) 0x00, 11));
        } else {
            // [T-Up#INFO][COCRDSLC.cbl, LINE #625] MOVE statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcAcctId(container.getCcrdslai().getAcctsidi());
        }
        // [T-Up#INFO][COCRDSLC.cbl, LINE #628] IF statement
        if (CobStringUtils.compare(container.getCcrdslai().getCardsidi(), "*") == 0
                || CobStringUtils.compare(
                        container.getCcrdslai().getCardsidi(),
                        StringUtils.repeat(' ', 16)) == 0) {
            // [T-Up#INFO][COCRDSLC.cbl, LINE #630] MOVE statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcCardNum(StringUtils.repeat((char) 0x00, 16));
        } else {
            // [T-Up#INFO][COCRDSLC.cbl, LINE #632] MOVE statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcCardNum(container.getCcrdslai().getCardsidi());
        }
        // *    INDIVIDUAL FIELD EDITS                                       
        // [T-Up#INFO][COCRDSLC.cbl, LINE #636] PERFORM statement
        controlManager.run(context, _2210EditAccount, _2210EditAccountExit);
        if (controlManager.isTerminate(context)) {
            return;
        }
        // [T-Up#INFO][COCRDSLC.cbl, LINE #639] PERFORM statement
        controlManager.run(context, _2220EditCard, _2220EditCardExit);
        if (controlManager.isTerminate(context)) {
            return;
        }
        // *    CROSS FIELD EDITS                                            
        // [T-Up#INFO][COCRDSLC.cbl, LINE #643] IF statement
        if (CobStringUtils.compare(container.getWsMiscStorage()
                .getWsEditAcctFlag(), FLG_ACCTFILTER_BLANK) == 0
                && CobStringUtils.compare(container.getWsMiscStorage()
                        .getWsEditCardFlag(), FLG_CARDFILTER_BLANK) == 0) {
            // [T-Up#INFO][COCRDSLC.cbl, LINE #645] SET statement
            container.getWsMiscStorage().setWsReturnMsg(
                    NO_SEARCH_CRITERIA_RECEIVED);
        }
    }

    void _2200EditMapInputsExit(OpenFrameContext context) {
        // [T-Up#INFO][COCRDSLC.cbl, LINE #650] EXIT statement
    }

    void _2210EditAccount(OpenFrameContext context) {
        CocrdslcVariableContainer container = (CocrdslcVariableContainer) context
                .getProgramVariableContainer("Cocrdslc");
        // [T-Up#INFO][COCRDSLC.cbl, LINE #654] SET statement
        container.getWsMiscStorage().setWsEditAcctFlag(FLG_ACCTFILTER_NOT_OK);
        // *    Not supplied                                                 
        // [T-Up#INFO][COCRDSLC.cbl, LINE #657] IF statement
        if ((CobStringUtils.compare(container.getCcWorkAreas().getCcWorkArea()
                .getCcAcctId(), StringUtils.repeat((char) 0x00, 11)) == 0 || CobStringUtils
                .compare(container.getCcWorkAreas().getCcWorkArea()
                        .getCcAcctId(), StringUtils.repeat(' ', 11)) == 0)
                || container.getCcWorkAreas().getCcWorkArea().getCcAcctIdN() == 0) {
            // [T-Up#INFO][COCRDSLC.cbl, LINE #660] SET statement
            container.getWsMiscStorage().setWsInputFlag(INPUT_ERROR);
            // [T-Up#INFO][COCRDSLC.cbl, LINE #661] SET statement
            container.getWsMiscStorage()
                    .setWsEditAcctFlag(FLG_ACCTFILTER_BLANK);
            // [T-Up#INFO][COCRDSLC.cbl, LINE #662] IF statement
            if (CobStringUtils.compare(container.getWsMiscStorage()
                    .getWsReturnMsg(), WS_RETURN_MSG_OFF) == 0) {
                // [T-Up#INFO][COCRDSLC.cbl, LINE #663] SET statement
                container.getWsMiscStorage().setWsReturnMsg(WS_PROMPT_FOR_ACCT);
            }
            // [T-Up#INFO][COCRDSLC.cbl, LINE #665] MOVE statement
            container.getCarddemoCommarea().getCdemoAccountInfo()
                    .setCdemoAcctId((long) 0);
            // [T-Up#INFO][COCRDSLC.cbl, LINE #666] GOTO statement
            context.setGotoTarget(_2210EditAccountExit);
            return;
        }
        // *                                                                 
        // *    Not numeric                                                  
        // *    Not 11 characters                                            
        // [T-Up#INFO][COCRDSLC.cbl, LINE #671] IF statement
        if (!StringUtils.isNumeric(container.getCcWorkAreas().getCcWorkArea()
                .getCcAcctId())) {
            // [T-Up#INFO][COCRDSLC.cbl, LINE #672] SET statement
            container.getWsMiscStorage().setWsInputFlag(INPUT_ERROR);
            // [T-Up#INFO][COCRDSLC.cbl, LINE #673] SET statement
            container.getWsMiscStorage().setWsEditAcctFlag(
                    FLG_ACCTFILTER_NOT_OK);
            // [T-Up#INFO][COCRDSLC.cbl, LINE #674] IF statement
            if (CobStringUtils.compare(container.getWsMiscStorage()
                    .getWsReturnMsg(), WS_RETURN_MSG_OFF) == 0) {
                // [T-Up#INFO][COCRDSLC.cbl, LINE #675] MOVE statement
                container.getWsMiscStorage().setWsReturnMsg(
                        "ACCOUNT FILTER,IF SUPPLIED MUST BE A 11 DIGIT NUMBER");
            }
            // [T-Up#INFO][COCRDSLC.cbl, LINE #679] MOVE statement
            container.getCarddemoCommarea().getCdemoAccountInfo()
                    .setCdemoAcctId((long) 0);
            // [T-Up#INFO][COCRDSLC.cbl, LINE #680] GOTO statement
            context.setGotoTarget(_2210EditAccountExit);
            return;
        } else {
            // [T-Up#INFO][COCRDSLC.cbl, LINE #682] MOVE statement
            container
                    .getCarddemoCommarea()
                    .getCdemoAccountInfo()
                    .setCdemoAcctId(
                            Long.parseLong(container.getCcWorkAreas()
                                    .getCcWorkArea().getCcAcctId().trim()));
            // [T-Up#INFO][COCRDSLC.cbl, LINE #683] SET statement
            container.getWsMiscStorage().setWsEditAcctFlag(
                    FLG_ACCTFILTER_ISVALID);
        }
    }

    void _2210EditAccountExit(OpenFrameContext context) {
        // [T-Up#INFO][COCRDSLC.cbl, LINE #688] EXIT statement
    }

    void _2220EditCard(OpenFrameContext context) {
        CocrdslcVariableContainer container = (CocrdslcVariableContainer) context
                .getProgramVariableContainer("Cocrdslc");
        // *    Not numeric                                                  
        // *    Not 16 characters                                            
        // [T-Up#INFO][COCRDSLC.cbl, LINE #694] SET statement
        container.getWsMiscStorage().setWsEditCardFlag(FLG_CARDFILTER_NOT_OK);
        // *    Not supplied                                                 
        // [T-Up#INFO][COCRDSLC.cbl, LINE #697] IF statement
        if ((CobStringUtils.compare(container.getCcWorkAreas().getCcWorkArea()
                .getCcCardNum(), StringUtils.repeat((char) 0x00, 16)) == 0 || CobStringUtils
                .compare(container.getCcWorkAreas().getCcWorkArea()
                        .getCcCardNum(), StringUtils.repeat(' ', 16)) == 0)
                || container.getCcWorkAreas().getCcWorkArea().getCcCardNumN() == 0) {
            // [T-Up#INFO][COCRDSLC.cbl, LINE #700] SET statement
            container.getWsMiscStorage().setWsInputFlag(INPUT_ERROR);
            // [T-Up#INFO][COCRDSLC.cbl, LINE #701] SET statement
            container.getWsMiscStorage()
                    .setWsEditCardFlag(FLG_CARDFILTER_BLANK);
            // [T-Up#INFO][COCRDSLC.cbl, LINE #702] IF statement
            if (CobStringUtils.compare(container.getWsMiscStorage()
                    .getWsReturnMsg(), WS_RETURN_MSG_OFF) == 0) {
                // [T-Up#INFO][COCRDSLC.cbl, LINE #703] SET statement
                container.getWsMiscStorage().setWsReturnMsg(WS_PROMPT_FOR_CARD);
            }
            // [T-Up#INFO][COCRDSLC.cbl, LINE #706] MOVE statement
            container.getCarddemoCommarea().getCdemoCardInfo()
                    .setCdemoCardNum((long) 0);
            // [T-Up#INFO][COCRDSLC.cbl, LINE #707] GOTO statement
            context.setGotoTarget(_2220EditCardExit);
            return;
        }
        // *                                                                 
        // *    Not numeric                                                  
        // *    Not 16 characters                                            
        // [T-Up#INFO][COCRDSLC.cbl, LINE #712] IF statement
        if (!StringUtils.isNumeric(container.getCcWorkAreas().getCcWorkArea()
                .getCcCardNum())) {
            // [T-Up#INFO][COCRDSLC.cbl, LINE #713] SET statement
            container.getWsMiscStorage().setWsInputFlag(INPUT_ERROR);
            // [T-Up#INFO][COCRDSLC.cbl, LINE #714] SET statement
            container.getWsMiscStorage().setWsEditCardFlag(
                    FLG_CARDFILTER_NOT_OK);
            // [T-Up#INFO][COCRDSLC.cbl, LINE #715] IF statement
            if (CobStringUtils.compare(container.getWsMiscStorage()
                    .getWsReturnMsg(), WS_RETURN_MSG_OFF) == 0) {
                // [T-Up#INFO][COCRDSLC.cbl, LINE #716] MOVE statement
                container.getWsMiscStorage().setWsReturnMsg(
                        "CARD ID FILTER,IF SUPPLIED MUST BE A 16 DIGIT NUMBER");
            }
            // [T-Up#INFO][COCRDSLC.cbl, LINE #720] MOVE statement
            container.getCarddemoCommarea().getCdemoCardInfo()
                    .setCdemoCardNum((long) 0);
            // [T-Up#INFO][COCRDSLC.cbl, LINE #721] GOTO statement
            context.setGotoTarget(_2220EditCardExit);
            return;
        } else {
            // [T-Up#INFO][COCRDSLC.cbl, LINE #723] MOVE statement
            container
                    .getCarddemoCommarea()
                    .getCdemoCardInfo()
                    .setCdemoCardNum(
                            container.getCcWorkAreas().getCcWorkArea()
                                    .getCcCardNumN());
            // [T-Up#INFO][COCRDSLC.cbl, LINE #724] SET statement
            container.getWsMiscStorage().setWsEditCardFlag(
                    FLG_CARDFILTER_ISVALID);
        }
    }

    void _2220EditCardExit(OpenFrameContext context) {
        // [T-Up#INFO][COCRDSLC.cbl, LINE #729] EXIT statement
    }

    void _9000ReadData(OpenFrameContext context) {
        // [T-Up#INFO][COCRDSLC.cbl, LINE #734] PERFORM statement
        controlManager.run(context, _9100GetcardByacctcard,
                _9100GetcardByacctcardExit);
        if (controlManager.isTerminate(context)) {
            return;
        }
    }

    void _9000ReadDataExit(OpenFrameContext context) {
        // [T-Up#INFO][COCRDSLC.cbl, LINE #739] EXIT statement
    }

    void _9100GetcardByacctcard(OpenFrameContext context) {
        CocrdslcVariableContainer container = (CocrdslcVariableContainer) context
                .getProgramVariableContainer("Cocrdslc");
        // *    Read the Card file                                           
        // *                                                                 
        // *    MOVE CC-ACCT-ID-N      TO WS-CARD-RID-ACCT-ID                
        // [T-Up#INFO][COCRDSLC.cbl, LINE #746] MOVE statement
        container
                .getWsMiscStorage()
                .getWsCardRid()
                .setWsCardRidCardnum(
                        container.getCcWorkAreas().getCcWorkArea()
                                .getCcCardNum());
        // [T-Up#INFO][COCRDSLC.cbl, LINE #748] EXEC_CICS statement
        /*
                       EXEC CICS READ                                               
                            FILE      (LIT-CARDFILENAME)                            
                            RIDFLD    (WS-CARD-RID-CARDNUM)                         
                            KEYLENGTH (LENGTH OF WS-CARD-RID-CARDNUM)               
                            INTO      (CARD-RECORD)                                 
                            LENGTH    (LENGTH OF CARD-RECORD)                       
                            RESP      (WS-RESP-CD)                                  
                            RESP2     (WS-REAS-CD)                                  
                       END-EXEC
         */
        try {
            AwsM2CarddemoCarddataVsamKsdsDto awsM2CarddemoCarddataVsamKsdsDto = recordKeyAccessor
                    .read("awsM2CarddemoCarddataVsamKsdsDao", container
                            .getWsMiscStorage().getWsCardRid()
                            .getWsCardRidCardnum());
            container
                    .setCardRecord(CocrdslcCardRecordToAwsM2CarddemoCarddataVsamKsdsDto.INSTANCE
                            .toSource(awsM2CarddemoCarddataVsamKsdsDto));
        } catch (ConditionException e) {
        } finally {
            container.getWsMiscStorage().getWsCicsProcessngVars()
                    .setWsRespCd(task.getLastResp());
            container.getWsMiscStorage().getWsCicsProcessngVars()
                    .setWsReasCd(task.getLastResp2());
        }
        // [T-Up#INFO][COCRDSLC.cbl, LINE #758] EVALUATE statement
        if (container.getWsMiscStorage().getWsCicsProcessngVars().getWsRespCd() == 0) {
            // [T-Up#INFO][COCRDSLC.cbl, LINE #760] SET statement
            container.getWsMiscStorage().setWsInfoMsg(FOUND_CARDS_FOR_ACCOUNT);
        } else if (container.getWsMiscStorage().getWsCicsProcessngVars()
                .getWsRespCd() == 13) {
            // [T-Up#INFO][COCRDSLC.cbl, LINE #762] SET statement
            container.getWsMiscStorage().setWsInputFlag(INPUT_ERROR);
            // [T-Up#INFO][COCRDSLC.cbl, LINE #763] SET statement
            container.getWsMiscStorage().setWsEditAcctFlag(
                    FLG_ACCTFILTER_NOT_OK);
            // [T-Up#INFO][COCRDSLC.cbl, LINE #764] SET statement
            container.getWsMiscStorage().setWsEditCardFlag(
                    FLG_CARDFILTER_NOT_OK);
            // [T-Up#INFO][COCRDSLC.cbl, LINE #765] IF statement
            if (CobStringUtils.compare(container.getWsMiscStorage()
                    .getWsReturnMsg(), WS_RETURN_MSG_OFF) == 0) {
                // [T-Up#INFO][COCRDSLC.cbl, LINE #766] SET statement
                container.getWsMiscStorage().setWsReturnMsg(
                        DID_NOT_FIND_ACCTCARD_COMBO);
            }
        } else {
            // [T-Up#INFO][COCRDSLC.cbl, LINE #769] SET statement
            container.getWsMiscStorage().setWsInputFlag(INPUT_ERROR);
            // [T-Up#INFO][COCRDSLC.cbl, LINE #770] IF statement
            if (CobStringUtils.compare(container.getWsMiscStorage()
                    .getWsReturnMsg(), WS_RETURN_MSG_OFF) == 0) {
                // [T-Up#INFO][COCRDSLC.cbl, LINE #771] SET statement
                container.getWsMiscStorage().setWsEditAcctFlag(
                        FLG_ACCTFILTER_NOT_OK);
            }
            // [T-Up#INFO][COCRDSLC.cbl, LINE #773] MOVE statement
            container.getWsMiscStorage().getWsFileErrorMessage()
                    .setErrorOpname("READ");
            // [T-Up#INFO][COCRDSLC.cbl, LINE #774] MOVE statement
            container
                    .getWsMiscStorage()
                    .getWsFileErrorMessage()
                    .setErrorFile(
                            container.getWsLiterals().getLitCardfilename());
            // [T-Up#INFO][COCRDSLC.cbl, LINE #775] MOVE statement
            container
                    .getWsMiscStorage()
                    .getWsFileErrorMessage()
                    .setErrorResp(
                            StringUtils.leftPad(
                                    String.valueOf(Math.abs(container
                                            .getWsMiscStorage()
                                            .getWsCicsProcessngVars()
                                            .getWsRespCd())), 9, '0'));
            // [T-Up#INFO][COCRDSLC.cbl, LINE #776] MOVE statement
            container
                    .getWsMiscStorage()
                    .getWsFileErrorMessage()
                    .setErrorResp2(
                            StringUtils.leftPad(
                                    String.valueOf(Math.abs(container
                                            .getWsMiscStorage()
                                            .getWsCicsProcessngVars()
                                            .getWsReasCd())), 9, '0'));
            // [T-Up#INFO][COCRDSLC.cbl, LINE #777] MOVE statement
            container.getWsMiscStorage().setWsReturnMsg(
                    container.getWsMiscStorage().getWsFileErrorMessage().get());
        }
    }

    void _9100GetcardByacctcardExit(OpenFrameContext context) {
        // [T-Up#INFO][COCRDSLC.cbl, LINE #782] EXIT statement
    }

    void _9150GetcardByacct(OpenFrameContext context) {
        CocrdslcVariableContainer container = (CocrdslcVariableContainer) context
                .getProgramVariableContainer("Cocrdslc");
        // *    Read the Card file. Access via alternate index ACCTID        
        // *                                                                 
        // [T-Up#INFO][COCRDSLC.cbl, LINE #789] EXEC_CICS statement
        /*
                       EXEC CICS READ                                               
                            FILE      (LIT-CARDFILENAME-ACCT-PATH)                  
                            RIDFLD    (WS-CARD-RID-ACCT-ID)                         
                            KEYLENGTH (LENGTH OF WS-CARD-RID-ACCT-ID)               
                            INTO      (CARD-RECORD)                                 
                            LENGTH    (LENGTH OF CARD-RECORD)                       
                            RESP      (WS-RESP-CD)                                  
                            RESP2     (WS-REAS-CD)                                  
                       END-EXEC
         */
        try {
            AwsM2CarddemoCarddataVsamKsdsDto awsM2CarddemoCarddataVsamKsdsDto = recordKeyAccessor
                    .alternateIndex().read(
                            "awsM2CarddemoCarddataVsamKsdsDao",
                            "Aix11",
                            BigDecimal.valueOf(container.getWsMiscStorage()
                                    .getWsCardRid().getWsCardRidAcctId()));
            container
                    .setCardRecord(CocrdslcCardRecordToAwsM2CarddemoCarddataVsamKsdsDto.INSTANCE
                            .toSource(awsM2CarddemoCarddataVsamKsdsDto));
        } catch (ConditionException e) {
        } finally {
            container.getWsMiscStorage().getWsCicsProcessngVars()
                    .setWsRespCd(task.getLastResp());
            container.getWsMiscStorage().getWsCicsProcessngVars()
                    .setWsReasCd(task.getLastResp2());
        }
        // [T-Up#INFO][COCRDSLC.cbl, LINE #799] EVALUATE statement
        if (container.getWsMiscStorage().getWsCicsProcessngVars().getWsRespCd() == 0) {
            // [T-Up#INFO][COCRDSLC.cbl, LINE #801] SET statement
            container.getWsMiscStorage().setWsInfoMsg(FOUND_CARDS_FOR_ACCOUNT);
        } else if (container.getWsMiscStorage().getWsCicsProcessngVars()
                .getWsRespCd() == 13) {
            // [T-Up#INFO][COCRDSLC.cbl, LINE #803] SET statement
            container.getWsMiscStorage().setWsInputFlag(INPUT_ERROR);
            // [T-Up#INFO][COCRDSLC.cbl, LINE #804] SET statement
            container.getWsMiscStorage().setWsEditAcctFlag(
                    FLG_ACCTFILTER_NOT_OK);
            // [T-Up#INFO][COCRDSLC.cbl, LINE #805] SET statement
            container.getWsMiscStorage().setWsReturnMsg(
                    DID_NOT_FIND_ACCT_IN_CARDXREF);
        } else {
            // [T-Up#INFO][COCRDSLC.cbl, LINE #807] SET statement
            container.getWsMiscStorage().setWsInputFlag(INPUT_ERROR);
            // [T-Up#INFO][COCRDSLC.cbl, LINE #808] SET statement
            container.getWsMiscStorage().setWsEditAcctFlag(
                    FLG_ACCTFILTER_NOT_OK);
            // [T-Up#INFO][COCRDSLC.cbl, LINE #809] MOVE statement
            container.getWsMiscStorage().getWsFileErrorMessage()
                    .setErrorOpname("READ");
            // [T-Up#INFO][COCRDSLC.cbl, LINE #810] MOVE statement
            container
                    .getWsMiscStorage()
                    .getWsFileErrorMessage()
                    .setErrorFile(
                            container.getWsLiterals()
                                    .getLitCardfilenameAcctPath());
            // [T-Up#INFO][COCRDSLC.cbl, LINE #811] MOVE statement
            container
                    .getWsMiscStorage()
                    .getWsFileErrorMessage()
                    .setErrorResp(
                            StringUtils.leftPad(
                                    String.valueOf(Math.abs(container
                                            .getWsMiscStorage()
                                            .getWsCicsProcessngVars()
                                            .getWsRespCd())), 9, '0'));
            // [T-Up#INFO][COCRDSLC.cbl, LINE #812] MOVE statement
            container
                    .getWsMiscStorage()
                    .getWsFileErrorMessage()
                    .setErrorResp2(
                            StringUtils.leftPad(
                                    String.valueOf(Math.abs(container
                                            .getWsMiscStorage()
                                            .getWsCicsProcessngVars()
                                            .getWsReasCd())), 9, '0'));
            // [T-Up#INFO][COCRDSLC.cbl, LINE #813] MOVE statement
            container.getWsMiscStorage().setWsReturnMsg(
                    container.getWsMiscStorage().getWsFileErrorMessage().get());
        }
    }

    void _9150GetcardByacctExit(OpenFrameContext context) {
        // [T-Up#INFO][COCRDSLC.cbl, LINE #817] EXIT statement
    }

    // ***************************************************************** 
    // * Display Long text and exit                                    * 
    // * This is primarily for debugging and should not be used in     * 
    // * regular course                                                * 
    // ***************************************************************** 

    void sendLongText(OpenFrameContext context) {
        CocrdslcVariableContainer container = (CocrdslcVariableContainer) context
                .getProgramVariableContainer("Cocrdslc");
        // [T-Up#INFO][COCRDSLC.cbl, LINE #827] EXEC_CICS statement
        /*
                       EXEC CICS SEND TEXT                                          
                                 FROM(WS-LONG-MSG)                                  
                                 LENGTH(LENGTH OF WS-LONG-MSG)                      
                                 ERASE                                              
                                 FREEKB                                             
                       END-EXEC
         */
        task.getOutputDto().getSystemDto()
                .setNotification(container.getWsMiscStorage().getWsLongMsg());
        // [T-Up#INFO][COCRDSLC.cbl, LINE #834] EXEC_CICS statement
        /*
                       EXEC CICS RETURN                                             
                       END-EXEC
         */
        context.setReturnFlag(true);
    }

    void sendLongTextExit(OpenFrameContext context) {
        // [T-Up#INFO][COCRDSLC.cbl, LINE #838] EXIT statement
    }

    // ***************************************************************** 
    // * Plain text exit - Dont use in production                      * 
    // ***************************************************************** 

    void sendPlainText(OpenFrameContext context) {
        CocrdslcVariableContainer container = (CocrdslcVariableContainer) context
                .getProgramVariableContainer("Cocrdslc");
        // [T-Up#INFO][COCRDSLC.cbl, LINE #845] EXEC_CICS statement
        /*
                       EXEC CICS SEND TEXT                                          
                                 FROM(WS-RETURN-MSG)                                
                                 LENGTH(LENGTH OF WS-RETURN-MSG)                    
                                 ERASE                                              
                                 FREEKB                                             
                       END-EXEC
         */
        task.getOutputDto().getSystemDto()
                .setNotification(container.getWsMiscStorage().getWsReturnMsg());
        // [T-Up#INFO][COCRDSLC.cbl, LINE #852] EXEC_CICS statement
        /*
                       EXEC CICS RETURN                                             
                       END-EXEC
         */
        context.setReturnFlag(true);
    }

    void sendPlainTextExit(OpenFrameContext context) {
        // [T-Up#INFO][COCRDSLC.cbl, LINE #856] EXIT statement
    }

    // ******************************************************************
    // *Common code to store PFKey                                       
    // ******************************************************************
    //       *COPY 'CSSTRPFY'                                                  
    //       *    .                                                            
    // *(/home/oflab/repository/ref/COBOL_COPYBOOK/CARDDEMO/CSSTRPFY.cpy)
    // ******************************************************************
    // * Copyright Amazon.com, Inc. or its affiliates.                   
    // * All Rights Reserved.                                            
    // *                                                                 
    // * Licensed under the Apache License, Version 2.0 (the "License"). 
    // * You may not use this file except in compliance with the License.
    // * You may obtain a copy of the License at                         
    // *                                                                 
    // *    http://www.apache.org/licenses/LICENSE-2.0                   
    // *                                                                 
    // * Unless required by applicable law or agreed to in writing,      
    // * software distributed under the License is distributed on an     
    // * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,    
    // * either express or implied. See the License for the specific     
    // * language governing permissions and limitations under the License
    // ******************************************************************

    void yyyyStorePfkey(OpenFrameContext context) {
        CocrdslcVariableContainer container = (CocrdslcVariableContainer) context
                .getProgramVariableContainer("Cocrdslc");
        // ***************************************************************** 
        // * Map AID to PFKey in COMMON Area                                 
        // ***************************************************************** 
        // [T-Up#INFO][CSSTRPFY.cpy, LINE #22] EVALUATE statement
        if (CobStringUtils.compare(task.getPressedKey(), container.getDfhaid()
                .getDfhenter()) == 0) {
            // [T-Up#INFO][CSSTRPFY.cpy, LINE #24] SET statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcardAid(CCARD_AID_ENTER);
        } else if (CobStringUtils.compare(task.getPressedKey(), container
                .getDfhaid().getDfhclear()) == 0) {
            // [T-Up#INFO][CSSTRPFY.cpy, LINE #26] SET statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcardAid(CCARD_AID_CLEAR);
        } else if (CobStringUtils.compare(task.getPressedKey(), container
                .getDfhaid().getDfhpa1()) == 0) {
            // [T-Up#INFO][CSSTRPFY.cpy, LINE #28] SET statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcardAid(CCARD_AID_PA1);
        } else if (CobStringUtils.compare(task.getPressedKey(), container
                .getDfhaid().getDfhpa2()) == 0) {
            // [T-Up#INFO][CSSTRPFY.cpy, LINE #30] SET statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcardAid(CCARD_AID_PA2);
        } else if (CobStringUtils.compare(task.getPressedKey(), container
                .getDfhaid().getDfhpf1()) == 0) {
            // [T-Up#INFO][CSSTRPFY.cpy, LINE #32] SET statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcardAid(CCARD_AID_PFK01);
        } else if (CobStringUtils.compare(task.getPressedKey(), container
                .getDfhaid().getDfhpf2()) == 0) {
            // [T-Up#INFO][CSSTRPFY.cpy, LINE #34] SET statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcardAid(CCARD_AID_PFK02);
        } else if (CobStringUtils.compare(task.getPressedKey(), container
                .getDfhaid().getDfhpf3()) == 0) {
            // [T-Up#INFO][CSSTRPFY.cpy, LINE #36] SET statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcardAid(CCARD_AID_PFK03);
        } else if (CobStringUtils.compare(task.getPressedKey(), container
                .getDfhaid().getDfhpf4()) == 0) {
            // [T-Up#INFO][CSSTRPFY.cpy, LINE #38] SET statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcardAid(CCARD_AID_PFK04);
        } else if (CobStringUtils.compare(task.getPressedKey(), container
                .getDfhaid().getDfhpf5()) == 0) {
            // [T-Up#INFO][CSSTRPFY.cpy, LINE #40] SET statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcardAid(CCARD_AID_PFK05);
        } else if (CobStringUtils.compare(task.getPressedKey(), container
                .getDfhaid().getDfhpf6()) == 0) {
            // [T-Up#INFO][CSSTRPFY.cpy, LINE #42] SET statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcardAid(CCARD_AID_PFK06);
        } else if (CobStringUtils.compare(task.getPressedKey(), container
                .getDfhaid().getDfhpf7()) == 0) {
            // [T-Up#INFO][CSSTRPFY.cpy, LINE #44] SET statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcardAid(CCARD_AID_PFK07);
        } else if (CobStringUtils.compare(task.getPressedKey(), container
                .getDfhaid().getDfhpf8()) == 0) {
            // [T-Up#INFO][CSSTRPFY.cpy, LINE #46] SET statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcardAid(CCARD_AID_PFK08);
        } else if (CobStringUtils.compare(task.getPressedKey(), container
                .getDfhaid().getDfhpf9()) == 0) {
            // [T-Up#INFO][CSSTRPFY.cpy, LINE #48] SET statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcardAid(CCARD_AID_PFK09);
        } else if (CobStringUtils.compare(task.getPressedKey(), container
                .getDfhaid().getDfhpf10()) == 0) {
            // [T-Up#INFO][CSSTRPFY.cpy, LINE #50] SET statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcardAid(CCARD_AID_PFK10);
        } else if (CobStringUtils.compare(task.getPressedKey(), container
                .getDfhaid().getDfhpf11()) == 0) {
            // [T-Up#INFO][CSSTRPFY.cpy, LINE #52] SET statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcardAid(CCARD_AID_PFK11);
        } else if (CobStringUtils.compare(task.getPressedKey(), container
                .getDfhaid().getDfhpf12()) == 0) {
            // [T-Up#INFO][CSSTRPFY.cpy, LINE #54] SET statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcardAid(CCARD_AID_PFK12);
        } else if (CobStringUtils.compare(task.getPressedKey(), container
                .getDfhaid().getDfhpf13()) == 0) {
            // [T-Up#INFO][CSSTRPFY.cpy, LINE #56] SET statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcardAid(CCARD_AID_PFK01);
        } else if (CobStringUtils.compare(task.getPressedKey(), container
                .getDfhaid().getDfhpf14()) == 0) {
            // [T-Up#INFO][CSSTRPFY.cpy, LINE #58] SET statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcardAid(CCARD_AID_PFK02);
        } else if (CobStringUtils.compare(task.getPressedKey(), container
                .getDfhaid().getDfhpf15()) == 0) {
            // [T-Up#INFO][CSSTRPFY.cpy, LINE #60] SET statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcardAid(CCARD_AID_PFK03);
        } else if (CobStringUtils.compare(task.getPressedKey(), container
                .getDfhaid().getDfhpf16()) == 0) {
            // [T-Up#INFO][CSSTRPFY.cpy, LINE #62] SET statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcardAid(CCARD_AID_PFK04);
        } else if (CobStringUtils.compare(task.getPressedKey(), container
                .getDfhaid().getDfhpf17()) == 0) {
            // [T-Up#INFO][CSSTRPFY.cpy, LINE #64] SET statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcardAid(CCARD_AID_PFK05);
        } else if (CobStringUtils.compare(task.getPressedKey(), container
                .getDfhaid().getDfhpf18()) == 0) {
            // [T-Up#INFO][CSSTRPFY.cpy, LINE #66] SET statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcardAid(CCARD_AID_PFK06);
        } else if (CobStringUtils.compare(task.getPressedKey(), container
                .getDfhaid().getDfhpf19()) == 0) {
            // [T-Up#INFO][CSSTRPFY.cpy, LINE #68] SET statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcardAid(CCARD_AID_PFK07);
        } else if (CobStringUtils.compare(task.getPressedKey(), container
                .getDfhaid().getDfhpf20()) == 0) {
            // [T-Up#INFO][CSSTRPFY.cpy, LINE #70] SET statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcardAid(CCARD_AID_PFK08);
        } else if (CobStringUtils.compare(task.getPressedKey(), container
                .getDfhaid().getDfhpf21()) == 0) {
            // [T-Up#INFO][CSSTRPFY.cpy, LINE #72] SET statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcardAid(CCARD_AID_PFK09);
        } else if (CobStringUtils.compare(task.getPressedKey(), container
                .getDfhaid().getDfhpf22()) == 0) {
            // [T-Up#INFO][CSSTRPFY.cpy, LINE #74] SET statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcardAid(CCARD_AID_PFK10);
        } else if (CobStringUtils.compare(task.getPressedKey(), container
                .getDfhaid().getDfhpf23()) == 0) {
            // [T-Up#INFO][CSSTRPFY.cpy, LINE #76] SET statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcardAid(CCARD_AID_PFK11);
        } else if (CobStringUtils.compare(task.getPressedKey(), container
                .getDfhaid().getDfhpf24()) == 0) {
            // [T-Up#INFO][CSSTRPFY.cpy, LINE #78] SET statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcardAid(CCARD_AID_PFK12);
        }
    }

    void yyyyStorePfkeyExit(OpenFrameContext context) {
        // [T-Up#INFO][CSSTRPFY.cpy, LINE #82] EXIT statement
    }

    // *                                                                 
    // * Ver: CardDemo_v1.0-15-g27d6c6f-68 Date: 2022-07-19 23:15:59 CDT 
    // *                                                                 

    void abendRoutine(OpenFrameContext context) {
        CocrdslcVariableContainer container = (CocrdslcVariableContainer) context
                .getProgramVariableContainer("Cocrdslc");
        // [T-Up#INFO][COCRDSLC.cbl, LINE #865] IF statement
        if (CobStringUtils.compare(container.getAbendData().getAbendMsg(),
                StringUtils.repeat((char) 0x00, 72)) == 0) {
            // [T-Up#INFO][COCRDSLC.cbl, LINE #866] MOVE statement
            container.getAbendData().setAbendMsg("UNEXPECTED ABEND OCCURRED.");
        }
        // [T-Up#INFO][COCRDSLC.cbl, LINE #869] MOVE statement
        container.getAbendData().setAbendCulprit(
                container.getWsLiterals().getLitThispgm());
        // [T-Up#INFO][COCRDSLC.cbl, LINE #871] EXEC_CICS statement
        /*
                       EXEC CICS SEND                                               
                                        FROM (ABEND-DATA)                           
                                        LENGTH(LENGTH OF ABEND-DATA)                
                                        NOHANDLE                                    
                       END-EXEC
         */
        try {
            task.getOutputDto().getSystemDto()
                    .setNotification(container.getAbendData());
        } catch (OnlineException e) {
        }
        // [T-Up#INFO][COCRDSLC.cbl, LINE #877] EXEC_CICS statement
        /*
                       EXEC CICS HANDLE ABEND                                       
                            CANCEL                                                  
                       END-EXEC
         */
        abendHandler.cancel();
        // [T-Up#INFO][COCRDSLC.cbl, LINE #881] EXEC_CICS statement
        /*
                       EXEC CICS ABEND                                              
                            ABCODE('9999')                                          
                       END-EXEC
         */
        throw new AbendException();
    }

    // *                                                                 
    // * Ver: CardDemo_v1.0-15-g27d6c6f-68 Date: 2022-07-19 23:12:33 CDT 
    // *                                                                 
}
