spring:
  main:
    allow-bean-definition-overriding: true
mybatis:
  mapper-locations: aws.carddemo.mapper
openframe:
  batch:
    datasource:
      password: tmax
      driver-class-name: com.tmax.tibero.jdbc.TbDriver
      url: jdbc:tibero:thin:@192.168.103.151:8629:tb_oflab
      username: tibero
