package aws.carddemo.file;

import aws.carddemo.dao.*;
import aws.carddemo.dto.*;
import aws.carddemo.mapper.*;
import aws.carddemo.variable.group.Cbact03cFdXreffileRec;
import com.tmax.openframe.runtime.context.OpenFrameContext;
import com.tmax.openframe.runtime.file.FileStatus;
import com.tmax.openframe.runtime.file.KeyOperationType;
import com.tmax.openframe.runtime.file.RecordCommitter;
import java.math.*;
import java.util.*;
import lombok.*;
import org.apache.ibatis.executor.BatchResult;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

/** 
 * <p>This source code was generated by T-Up OpenFrame COBOL to Java migrator</p>
 * <p>  Generation date : 2024/05/02 05:55:56 UTC</p>
 * <hr>
 * <p>Class for processing file I/O operations</p>
 * <ul>
 * <li>target dataset: AwsM2CarddemoCardxrefVsamKsds</li>
 * <li>file operation class: {@link Cbact03cFileOpXreffileFile}</li>
 * <li>DAO class: {@link AwsM2CarddemoCardxrefVsamKsdsDao}</li>
 * <li>DTO class: {@link AwsM2CarddemoCardxrefVsamKsdsDto}</li>
 * </ul>
 */
@Repository
public class Cbact03cFdXreffileFile extends Cbact03cFileOpXreffileFile {
    @Autowired
    private AwsM2CarddemoCardxrefVsamKsdsDao dao;
    @Autowired
    private RecordCommitter<AwsM2CarddemoCardxrefVsamKsdsDto> committer;

    public void open(OpenFrameContext context) {
        setIterator(context, dao.readAllAsc().iterator());
        setFileStatus(context, FileStatus.NORMAL);
        context.initFileWriteBuffer("Cbact03c", "XreffileFile");
        committer.setThreshold(5000);
    }

    public void start(OpenFrameContext context, String key,
            KeyOperationType type) {
        Cbact03cFdXreffileRec startPoint = new Cbact03cFdXreffileRec();
        startPoint.setFdXrefCardNum(key);
        AwsM2CarddemoCardxrefVsamKsdsDto dto = Cbact03cMapperInterface.Cbact03cFdXreffileRecKeyToAwsM2CarddemoCardxrefVsamKsdsDto.INSTANCE
                .toTarget(startPoint);
        switch (type) {
        case EQ:
        case GTEQ: {
            setIterator(context, dao.readGeDto(dto).iterator());
            break;
        }
        case GT: {
            setIterator(context, dao.readGtDto(dto).iterator());
            break;
        }
        default: {
            throw new RuntimeException(
                    "not supported operation for start method");
        }
        }
        if (!getIterator(context).hasNext()) {
            setFileStatus(context, FileStatus.INVALID_KEY_READ);
        } else {
            setFileStatus(context, FileStatus.NORMAL);
        }
    }

    public Cbact03cFdXreffileRec readNextRecord(OpenFrameContext context) {
        Iterator<AwsM2CarddemoCardxrefVsamKsdsDto> iterator = getIterator(context);
        if (iterator.hasNext()) {
            AwsM2CarddemoCardxrefVsamKsdsDto nextRecord = iterator.next();
            if (nextRecord == null) {
                setFileStatus(context, FileStatus.AT_END_CONDITION_SEQ_READ);
                return null;
            }
            setFileStatus(context, FileStatus.NORMAL);
            return Cbact03cMapperInterface.Cbact03cFdXreffileRecToAwsM2CarddemoCardxrefVsamKsdsDto.INSTANCE
                    .toSource(nextRecord);
        } else {
            setFileStatus(context, FileStatus.AT_END_CONDITION_SEQ_READ);
            return null;
        }
    }

    public Cbact03cFdXreffileRec readKey(OpenFrameContext context, String key) {
        commit(context);
        Cbact03cFdXreffileRec readKeyPoint = new Cbact03cFdXreffileRec();
        readKeyPoint.setFdXrefCardNum(key);
        AwsM2CarddemoCardxrefVsamKsdsDto dto = Cbact03cMapperInterface.Cbact03cFdXreffileRecKeyToAwsM2CarddemoCardxrefVsamKsdsDto.INSTANCE
                .toTarget(readKeyPoint);
        Iterator<AwsM2CarddemoCardxrefVsamKsdsDto> iterator = dao
                .readEqDto(dto).iterator();
        setIterator(context, iterator);
        if (iterator.hasNext()) {
            setFileStatus(context, FileStatus.NORMAL);
            return Cbact03cMapperInterface.Cbact03cFdXreffileRecToAwsM2CarddemoCardxrefVsamKsdsDto.INSTANCE
                    .toSource(iterator.next());
        } else {
            setFileStatus(context, FileStatus.INVALID_KEY_READ);
            return null;
        }
    }

    public void write(OpenFrameContext context, Cbact03cFdXreffileRec data) {
        List<AwsM2CarddemoCardxrefVsamKsdsDto> writeBuffer = getWriteBuffer(context);
        writeBuffer
                .add(Cbact03cMapperInterface.Cbact03cFdXreffileRecToAwsM2CarddemoCardxrefVsamKsdsDto.INSTANCE
                        .toTarget(data));
        if (writeBuffer.size() >= committer.getThreshold()) {
            committer.commit(dao::writeDto, writeBuffer);
            writeBuffer.clear();
        }
        setFileStatus(context, FileStatus.NORMAL);
    }

    public void rewrite(OpenFrameContext context, Cbact03cFdXreffileRec data,
            String key) {
        commit(context);
        data.setFdXrefCardNum(key);
        AwsM2CarddemoCardxrefVsamKsdsDto updateDto = Cbact03cMapperInterface.Cbact03cFdXreffileRecToAwsM2CarddemoCardxrefVsamKsdsDto.INSTANCE
                .toTarget(data);
        dao.flush();
        dao.rewriteDto(updateDto);
        List<BatchResult> resultList = dao.flush();
        if (resultList.get(0).getUpdateCounts()[0] > 0) {
            setFileStatus(context, FileStatus.NORMAL);
        } else {
            setFileStatus(context, FileStatus.INVALID_KEY_CREATE);
        }
    }

    public void delete(OpenFrameContext context, String key) {
        if (getIterator(context) == null) {
            return;
        }
        commit(context);
        Cbact03cFdXreffileRec deletePoint = new Cbact03cFdXreffileRec();
        deletePoint.setFdXrefCardNum(key);
        AwsM2CarddemoCardxrefVsamKsdsDto dto = Cbact03cMapperInterface.Cbact03cFdXreffileRecKeyToAwsM2CarddemoCardxrefVsamKsdsDto.INSTANCE
                .toTarget(deletePoint);
        dao.flush();
        dao.deleteDto(dto);
        List<BatchResult> resultList = dao.flush();
        if (resultList.get(0).getUpdateCounts()[0] > 0) {
            setFileStatus(context, FileStatus.NORMAL);
        } else {
            setFileStatus(context, FileStatus.INVALID_KEY_READ);
        }
    }

    public void close(OpenFrameContext context) {
        commit(context);
        setIterator(context, null);
        setFileStatus(context, FileStatus.NORMAL);
    }

    public void commit(OpenFrameContext context) {
        List<AwsM2CarddemoCardxrefVsamKsdsDto> writeBuffer = getWriteBuffer(context);
        if (writeBuffer != null && writeBuffer.size() > 0) {
            committer.commit(dao::writeDto, writeBuffer);
            writeBuffer.clear();
        }
    }

    private void setIterator(OpenFrameContext context,
            Iterator<AwsM2CarddemoCardxrefVsamKsdsDto> iterator) {
        context.setFileIterator("Cbact03c", "XreffileFile", iterator);
    }

    private Iterator<AwsM2CarddemoCardxrefVsamKsdsDto> getIterator(
            OpenFrameContext context) {
        return context.getFileIterator("Cbact03c", "XreffileFile");
    }

    private List<AwsM2CarddemoCardxrefVsamKsdsDto> getWriteBuffer(
            OpenFrameContext context) {
        return context.getFileWriteBuffer("Cbact03c", "XreffileFile");
    }
}
