package aws.carddemo.mapper;

import com.tmax.openframe.DataConverter;
import org.apache.commons.lang3.StringUtils;
import org.mapstruct.*;
import org.mapstruct.factory.*;
import aws.carddemo.variable.group.CoactupcWsMiscStorage.CoactupcAcctUpdateRecord;
import aws.carddemo.dto.AwsM2CarddemoAcctdataVsamKsdsDto;
import aws.carddemo.variable.group.CoactupcWsMiscStorage.CoactupcCustUpdateRecord;
import aws.carddemo.dto.AwsM2CarddemoCustdataVsamKsdsDto;
import aws.carddemo.variable.group.CoactupcCustomerRecord;
import aws.carddemo.variable.group.CoactupcCardXrefRecord;
import aws.carddemo.dto.AwsM2CarddemoCardxrefVsamKsdsDto;
import aws.carddemo.variable.group.CoactupcAccountRecord;
import aws.carddemo.variable.group.CoactupcCarddemoCommarea;
import aws.carddemo.variable.group.Comen01cDfhcommarea;
import lombok.*;
import java.math.*;
import java.util.*;

/** 
 * <p>This source code was generated by T-Up OpenFrame COBOL to Java migrator</p>
 * <p>  Generation date : 2024/05/02 05:57:52 UTC</p>
 * <hr>
 * <p>Mapper class for converting data between different classes</p>
 */
public interface CoactupcMapperInterface {
    /** 
     * <p>Mapper class to convert data for CICS processing</p>
     * <ul>
     * <li>source class: {@link CoactupcAcctUpdateRecord}</li>
     * <li>target class: {@link AwsM2CarddemoAcctdataVsamKsdsDto}</li>
     * </ul>
     */
    @Mapper(unmappedTargetPolicy = ReportingPolicy.IGNORE)
    public interface CoactupcAcctUpdateRecordToAwsM2CarddemoAcctdataVsamKsdsDto {
        CoactupcAcctUpdateRecordToAwsM2CarddemoAcctdataVsamKsdsDto INSTANCE = Mappers
                .getMapper(CoactupcAcctUpdateRecordToAwsM2CarddemoAcctdataVsamKsdsDto.class);

        @Mapping(source = "acctUpdateId", target = "acctId")
        @Mapping(source = "acctUpdateActiveStatus", target = "acctActiveStatus")
        @Mapping(source = "acctUpdateCurrBal", target = "acctCurrBal")
        @Mapping(source = "acctUpdateCreditLimit", target = "acctCreditLimit")
        @Mapping(source = "acctUpdateCashCreditLimit", target = "acctCashCreditLimit")
        @Mapping(source = "acctUpdateOpenDate", target = "acctOpenDate")
        @Mapping(source = "acctUpdateExpiraionDate", target = "acctExpiraionDate")
        @Mapping(source = "acctUpdateReissueDate", target = "acctReissueDate")
        @Mapping(source = "acctUpdateCurrCycCredit", target = "acctCurrCycCredit")
        @Mapping(source = "acctUpdateCurrCycDebit", target = "acctCurrCycDebit")
        @Mapping(source = "acctUpdateGroupId", target = "acctAddrZip")
        AwsM2CarddemoAcctdataVsamKsdsDto toTarget(
                CoactupcAcctUpdateRecord source);

        @Mapping(source = "acctId", target = "acctUpdateId")
        @Mapping(source = "acctActiveStatus", target = "acctUpdateActiveStatus")
        @Mapping(source = "acctCurrBal", target = "acctUpdateCurrBal")
        @Mapping(source = "acctCreditLimit", target = "acctUpdateCreditLimit")
        @Mapping(source = "acctCashCreditLimit", target = "acctUpdateCashCreditLimit")
        @Mapping(source = "acctOpenDate", target = "acctUpdateOpenDate")
        @Mapping(source = "acctExpiraionDate", target = "acctUpdateExpiraionDate")
        @Mapping(source = "acctReissueDate", target = "acctUpdateReissueDate")
        @Mapping(source = "acctCurrCycCredit", target = "acctUpdateCurrCycCredit")
        @Mapping(source = "acctCurrCycDebit", target = "acctUpdateCurrCycDebit")
        @Mapping(source = "acctAddrZip", target = "acctUpdateGroupId")
        CoactupcAcctUpdateRecord toSource(
                AwsM2CarddemoAcctdataVsamKsdsDto source);

        @AfterMapping
        default void makeTarget(CoactupcAcctUpdateRecord source,
                @MappingTarget AwsM2CarddemoAcctdataVsamKsdsDto target) {
            target.setAcctGroupId(source.getOFFILLER21().substring(0, 10));
            target.setFiller(source.getOFFILLER21().substring(10));
        }

        @AfterMapping
        default void makeSource(AwsM2CarddemoAcctdataVsamKsdsDto source,
                @MappingTarget CoactupcAcctUpdateRecord target) {
            target.setOFFILLER21(source.getAcctGroupId() + source.getFiller());
        }
    }

    /** 
     * <p>Mapper class to convert data for CICS processing</p>
     * <ul>
     * <li>source class: {@link CoactupcCustUpdateRecord}</li>
     * <li>target class: {@link AwsM2CarddemoCustdataVsamKsdsDto}</li>
     * </ul>
     */
    @Mapper(unmappedTargetPolicy = ReportingPolicy.IGNORE)
    public interface CoactupcCustUpdateRecordToAwsM2CarddemoCustdataVsamKsdsDto {
        CoactupcCustUpdateRecordToAwsM2CarddemoCustdataVsamKsdsDto INSTANCE = Mappers
                .getMapper(CoactupcCustUpdateRecordToAwsM2CarddemoCustdataVsamKsdsDto.class);

        @Mapping(source = "custUpdateId", target = "custId")
        @Mapping(source = "custUpdateFirstName", target = "custFirstName")
        @Mapping(source = "custUpdateMiddleName", target = "custMiddleName")
        @Mapping(source = "custUpdateLastName", target = "custLastName")
        @Mapping(source = "custUpdateAddrLine1", target = "custAddrLine1")
        @Mapping(source = "custUpdateAddrLine2", target = "custAddrLine2")
        @Mapping(source = "custUpdateAddrLine3", target = "custAddrLine3")
        @Mapping(source = "custUpdateAddrStateCd", target = "custAddrStateCd")
        @Mapping(source = "custUpdateAddrCountryCd", target = "custAddrCountryCd")
        @Mapping(source = "custUpdateAddrZip", target = "custAddrZip")
        @Mapping(source = "custUpdatePhoneNum1", target = "custPhoneNum1")
        @Mapping(source = "custUpdatePhoneNum2", target = "custPhoneNum2")
        @Mapping(source = "custUpdateSsn", target = "custSsn")
        @Mapping(source = "custUpdateGovtIssuedId", target = "custGovtIssuedId")
        @Mapping(source = "custUpdateDobYyyyMmDd", target = "custDobYyyymmdd")
        @Mapping(source = "custUpdateEftAccountId", target = "custEftAccountId")
        @Mapping(source = "custUpdatePriCardInd", target = "custPriCardHolderInd")
        @Mapping(source = "custUpdateFicoCreditScore", target = "custFicoCreditScore")
        @Mapping(source = "OFFILLER22", target = "filler")
        AwsM2CarddemoCustdataVsamKsdsDto toTarget(
                CoactupcCustUpdateRecord source);

        @Mapping(source = "custId", target = "custUpdateId")
        @Mapping(source = "custFirstName", target = "custUpdateFirstName")
        @Mapping(source = "custMiddleName", target = "custUpdateMiddleName")
        @Mapping(source = "custLastName", target = "custUpdateLastName")
        @Mapping(source = "custAddrLine1", target = "custUpdateAddrLine1")
        @Mapping(source = "custAddrLine2", target = "custUpdateAddrLine2")
        @Mapping(source = "custAddrLine3", target = "custUpdateAddrLine3")
        @Mapping(source = "custAddrStateCd", target = "custUpdateAddrStateCd")
        @Mapping(source = "custAddrCountryCd", target = "custUpdateAddrCountryCd")
        @Mapping(source = "custAddrZip", target = "custUpdateAddrZip")
        @Mapping(source = "custPhoneNum1", target = "custUpdatePhoneNum1")
        @Mapping(source = "custPhoneNum2", target = "custUpdatePhoneNum2")
        @Mapping(source = "custSsn", target = "custUpdateSsn")
        @Mapping(source = "custGovtIssuedId", target = "custUpdateGovtIssuedId")
        @Mapping(source = "custDobYyyymmdd", target = "custUpdateDobYyyyMmDd")
        @Mapping(source = "custEftAccountId", target = "custUpdateEftAccountId")
        @Mapping(source = "custPriCardHolderInd", target = "custUpdatePriCardInd")
        @Mapping(source = "custFicoCreditScore", target = "custUpdateFicoCreditScore")
        @Mapping(source = "filler", target = "OFFILLER22")
        CoactupcCustUpdateRecord toSource(
                AwsM2CarddemoCustdataVsamKsdsDto source);
    }

    /** 
     * <p>Mapper class to convert data for CICS processing</p>
     * <ul>
     * <li>source class: {@link CoactupcCustomerRecord}</li>
     * <li>target class: {@link AwsM2CarddemoCustdataVsamKsdsDto}</li>
     * </ul>
     */
    @Mapper(unmappedTargetPolicy = ReportingPolicy.IGNORE)
    public interface CoactupcCustomerRecordToAwsM2CarddemoCustdataVsamKsdsDto {
        CoactupcCustomerRecordToAwsM2CarddemoCustdataVsamKsdsDto INSTANCE = Mappers
                .getMapper(CoactupcCustomerRecordToAwsM2CarddemoCustdataVsamKsdsDto.class);

        @Mapping(source = "custId", target = "custId")
        @Mapping(source = "custFirstName", target = "custFirstName")
        @Mapping(source = "custMiddleName", target = "custMiddleName")
        @Mapping(source = "custLastName", target = "custLastName")
        @Mapping(source = "custAddrLine1", target = "custAddrLine1")
        @Mapping(source = "custAddrLine2", target = "custAddrLine2")
        @Mapping(source = "custAddrLine3", target = "custAddrLine3")
        @Mapping(source = "custAddrStateCd", target = "custAddrStateCd")
        @Mapping(source = "custAddrCountryCd", target = "custAddrCountryCd")
        @Mapping(source = "custAddrZip", target = "custAddrZip")
        @Mapping(source = "custPhoneNum1", target = "custPhoneNum1")
        @Mapping(source = "custPhoneNum2", target = "custPhoneNum2")
        @Mapping(source = "custSsn", target = "custSsn")
        @Mapping(source = "custGovtIssuedId", target = "custGovtIssuedId")
        @Mapping(source = "custDobYyyyMmDd", target = "custDobYyyymmdd")
        @Mapping(source = "custEftAccountId", target = "custEftAccountId")
        @Mapping(source = "custPriCardHolderInd", target = "custPriCardHolderInd")
        @Mapping(source = "custFicoCreditScore", target = "custFicoCreditScore")
        @Mapping(source = "OFFILLER1", target = "filler")
        AwsM2CarddemoCustdataVsamKsdsDto toTarget(CoactupcCustomerRecord source);

        @Mapping(source = "custId", target = "custId")
        @Mapping(source = "custFirstName", target = "custFirstName")
        @Mapping(source = "custMiddleName", target = "custMiddleName")
        @Mapping(source = "custLastName", target = "custLastName")
        @Mapping(source = "custAddrLine1", target = "custAddrLine1")
        @Mapping(source = "custAddrLine2", target = "custAddrLine2")
        @Mapping(source = "custAddrLine3", target = "custAddrLine3")
        @Mapping(source = "custAddrStateCd", target = "custAddrStateCd")
        @Mapping(source = "custAddrCountryCd", target = "custAddrCountryCd")
        @Mapping(source = "custAddrZip", target = "custAddrZip")
        @Mapping(source = "custPhoneNum1", target = "custPhoneNum1")
        @Mapping(source = "custPhoneNum2", target = "custPhoneNum2")
        @Mapping(source = "custSsn", target = "custSsn")
        @Mapping(source = "custGovtIssuedId", target = "custGovtIssuedId")
        @Mapping(source = "custDobYyyymmdd", target = "custDobYyyyMmDd")
        @Mapping(source = "custEftAccountId", target = "custEftAccountId")
        @Mapping(source = "custPriCardHolderInd", target = "custPriCardHolderInd")
        @Mapping(source = "custFicoCreditScore", target = "custFicoCreditScore")
        @Mapping(source = "filler", target = "OFFILLER1")
        CoactupcCustomerRecord toSource(AwsM2CarddemoCustdataVsamKsdsDto source);
    }

    /** 
     * <p>Mapper class to convert data for CICS processing</p>
     * <ul>
     * <li>source class: {@link CoactupcCardXrefRecord}</li>
     * <li>target class: {@link AwsM2CarddemoCardxrefVsamKsdsDto}</li>
     * </ul>
     */
    @Mapper(unmappedTargetPolicy = ReportingPolicy.IGNORE)
    public interface CoactupcCardXrefRecordToAwsM2CarddemoCardxrefVsamKsdsDto {
        CoactupcCardXrefRecordToAwsM2CarddemoCardxrefVsamKsdsDto INSTANCE = Mappers
                .getMapper(CoactupcCardXrefRecordToAwsM2CarddemoCardxrefVsamKsdsDto.class);

        @Mapping(source = "xrefCardNum", target = "xrefCardNum")
        @Mapping(source = "xrefCustId", target = "xrefCustId")
        @Mapping(source = "xrefAcctId", target = "xrefAcctId")
        @Mapping(source = "OFFILLER1", target = "filler")
        AwsM2CarddemoCardxrefVsamKsdsDto toTarget(CoactupcCardXrefRecord source);

        @Mapping(source = "xrefCardNum", target = "xrefCardNum")
        @Mapping(source = "xrefCustId", target = "xrefCustId")
        @Mapping(source = "xrefAcctId", target = "xrefAcctId")
        @Mapping(source = "filler", target = "OFFILLER1")
        CoactupcCardXrefRecord toSource(AwsM2CarddemoCardxrefVsamKsdsDto source);
    }

    /** 
     * <p>Mapper class to convert data for CICS processing</p>
     * <ul>
     * <li>source class: {@link CoactupcAccountRecord}</li>
     * <li>target class: {@link AwsM2CarddemoAcctdataVsamKsdsDto}</li>
     * </ul>
     */
    @Mapper(unmappedTargetPolicy = ReportingPolicy.IGNORE)
    public interface CoactupcAccountRecordToAwsM2CarddemoAcctdataVsamKsdsDto {
        CoactupcAccountRecordToAwsM2CarddemoAcctdataVsamKsdsDto INSTANCE = Mappers
                .getMapper(CoactupcAccountRecordToAwsM2CarddemoAcctdataVsamKsdsDto.class);

        @Mapping(source = "acctId", target = "acctId")
        @Mapping(source = "acctActiveStatus", target = "acctActiveStatus")
        @Mapping(source = "acctCurrBal", target = "acctCurrBal")
        @Mapping(source = "acctCreditLimit", target = "acctCreditLimit")
        @Mapping(source = "acctCashCreditLimit", target = "acctCashCreditLimit")
        @Mapping(source = "acctOpenDate", target = "acctOpenDate")
        @Mapping(source = "acctExpiraionDate", target = "acctExpiraionDate")
        @Mapping(source = "acctReissueDate", target = "acctReissueDate")
        @Mapping(source = "acctCurrCycCredit", target = "acctCurrCycCredit")
        @Mapping(source = "acctCurrCycDebit", target = "acctCurrCycDebit")
        @Mapping(source = "acctAddrZip", target = "acctAddrZip")
        @Mapping(source = "acctGroupId", target = "acctGroupId")
        @Mapping(source = "OFFILLER1", target = "filler")
        AwsM2CarddemoAcctdataVsamKsdsDto toTarget(CoactupcAccountRecord source);

        @Mapping(source = "acctId", target = "acctId")
        @Mapping(source = "acctActiveStatus", target = "acctActiveStatus")
        @Mapping(source = "acctCurrBal", target = "acctCurrBal")
        @Mapping(source = "acctCreditLimit", target = "acctCreditLimit")
        @Mapping(source = "acctCashCreditLimit", target = "acctCashCreditLimit")
        @Mapping(source = "acctOpenDate", target = "acctOpenDate")
        @Mapping(source = "acctExpiraionDate", target = "acctExpiraionDate")
        @Mapping(source = "acctReissueDate", target = "acctReissueDate")
        @Mapping(source = "acctCurrCycCredit", target = "acctCurrCycCredit")
        @Mapping(source = "acctCurrCycDebit", target = "acctCurrCycDebit")
        @Mapping(source = "acctAddrZip", target = "acctAddrZip")
        @Mapping(source = "acctGroupId", target = "acctGroupId")
        @Mapping(source = "filler", target = "OFFILLER1")
        CoactupcAccountRecord toSource(AwsM2CarddemoAcctdataVsamKsdsDto source);
    }

    /** 
     * <p>Mapper class to convert data for CICS processing</p>
     * <ul>
     * <li>source class: {@link CoactupcCarddemoCommarea}</li>
     * <li>target class: {@link Comen01cDfhcommarea}</li>
     * </ul>
     */
    @Mapper(unmappedTargetPolicy = ReportingPolicy.IGNORE)
    public interface CoactupcCarddemoCommareaToComen01cDfhcommarea {
        CoactupcCarddemoCommareaToComen01cDfhcommarea INSTANCE = Mappers
                .getMapper(CoactupcCarddemoCommareaToComen01cDfhcommarea.class);

        Comen01cDfhcommarea toTarget(CoactupcCarddemoCommarea source);

        CoactupcCarddemoCommarea toSource(Comen01cDfhcommarea source);

        @AfterMapping
        default void makeTarget(CoactupcCarddemoCommarea source,
                @MappingTarget Comen01cDfhcommarea target) {
            target.setLkCommarea(source.getCdemoGeneralInfo()
                    .getCdemoFromTranid()
                    + source.getCdemoGeneralInfo().getCdemoFromProgram()
                    + source.getCdemoGeneralInfo().getCdemoToTranid()
                    + source.getCdemoGeneralInfo().getCdemoToProgram()
                    + source.getCdemoGeneralInfo().getCdemoUserId()
                    + source.getCdemoGeneralInfo().getCdemoUserType()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoGeneralInfo().getCdemoPgmContext(), 1)
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCustomerInfo().getCdemoCustId(), 9)
                    + source.getCdemoCustomerInfo().getCdemoCustFname()
                    + source.getCdemoCustomerInfo().getCdemoCustMname()
                    + source.getCdemoCustomerInfo().getCdemoCustLname()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoAccountInfo().getCdemoAcctId(), 11)
                    + source.getCdemoAccountInfo().getCdemoAcctStatus()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCardInfo().getCdemoCardNum(), 16)
                    + source.getCdemoMoreInfo().getCdemoLastMap()
                    + source.getCdemoMoreInfo().getCdemoLastMapset());
        }

        @AfterMapping
        default void makeSource(Comen01cDfhcommarea source,
                @MappingTarget CoactupcCarddemoCommarea target) {
            target.getCdemoGeneralInfo().setCdemoFromTranid(
                    source.getLkCommarea().substring(0, 4));
            target.getCdemoGeneralInfo().setCdemoFromProgram(
                    source.getLkCommarea().substring(4, 12));
            target.getCdemoGeneralInfo().setCdemoToTranid(
                    source.getLkCommarea().substring(12, 16));
            target.getCdemoGeneralInfo().setCdemoToProgram(
                    source.getLkCommarea().substring(16, 24));
            target.getCdemoGeneralInfo().setCdemoUserId(
                    source.getLkCommarea().substring(24, 32));
            target.getCdemoGeneralInfo().setCdemoUserType(
                    source.getLkCommarea().substring(32, 33));
            target.getCdemoGeneralInfo().setCdemoPgmContext(
                    ((int) DataConverter.convZonedStringToLong(source
                            .getLkCommarea().substring(33, 34), 1)));
            target.getCdemoCustomerInfo().setCdemoCustId(
                    ((int) DataConverter.convZonedStringToLong(source
                            .getLkCommarea().substring(34, 43), 9)));
            target.getCdemoCustomerInfo().setCdemoCustFname(
                    source.getLkCommarea().substring(43, 68));
            target.getCdemoCustomerInfo().setCdemoCustMname(
                    source.getLkCommarea().substring(68, 93));
            target.getCdemoCustomerInfo().setCdemoCustLname(
                    source.getLkCommarea().substring(93, 118));
            target.getCdemoAccountInfo().setCdemoAcctId(
                    DataConverter.convZonedStringToLong(source.getLkCommarea()
                            .substring(118, 129), 11));
            target.getCdemoAccountInfo().setCdemoAcctStatus(
                    source.getLkCommarea().substring(129, 130));
            target.getCdemoCardInfo().setCdemoCardNum(
                    DataConverter.convZonedStringToLong(source.getLkCommarea()
                            .substring(130, 146), 16));
            target.getCdemoMoreInfo().setCdemoLastMap(
                    source.getLkCommarea().substring(146, 153));
            target.getCdemoMoreInfo().setCdemoLastMapset(
                    source.getLkCommarea().substring(153, 160));
        }
    }
}
