package aws.carddemo.mapper;

import com.tmax.openframe.DataConverter;
import org.apache.commons.lang3.StringUtils;
import org.mapstruct.*;
import org.mapstruct.factory.*;
import aws.carddemo.variable.group.Cosgn00cCarddemoCommarea;
import aws.carddemo.variable.group.Cosgn00cDfhcommarea;
import aws.carddemo.variable.group.Cosgn00cSecUserData;
import aws.carddemo.dto.AwsM2CarddemoUsrsecVsamKsdsDto;
import aws.carddemo.variable.group.Coadm01cDfhcommarea;
import aws.carddemo.variable.group.Comen01cDfhcommarea;
import lombok.*;
import java.math.*;
import java.util.*;

/** 
 * <p>This source code was generated by T-Up OpenFrame COBOL to Java migrator</p>
 * <p>  Generation date : 2024/05/02 05:57:45 UTC</p>
 * <hr>
 * <p>Mapper class for converting data between different classes</p>
 */
public interface Cosgn00cMapperInterface {
    /** 
     * <p>Mapper class to convert data for CICS processing</p>
     * <ul>
     * <li>source class: {@link Cosgn00cCarddemoCommarea}</li>
     * <li>target class: {@link Cosgn00cDfhcommarea}</li>
     * </ul>
     */
    @Mapper(unmappedTargetPolicy = ReportingPolicy.IGNORE)
    public interface Cosgn00cCarddemoCommareaToCosgn00cDfhcommarea {
        Cosgn00cCarddemoCommareaToCosgn00cDfhcommarea INSTANCE = Mappers
                .getMapper(Cosgn00cCarddemoCommareaToCosgn00cDfhcommarea.class);

        Cosgn00cDfhcommarea toTarget(Cosgn00cCarddemoCommarea source);

        Cosgn00cCarddemoCommarea toSource(Cosgn00cDfhcommarea source);

        @AfterMapping
        default void makeTarget(Cosgn00cCarddemoCommarea source,
                @MappingTarget Cosgn00cDfhcommarea target) {
            target.setLkCommarea(source.getCdemoGeneralInfo()
                    .getCdemoFromTranid()
                    + source.getCdemoGeneralInfo().getCdemoFromProgram()
                    + source.getCdemoGeneralInfo().getCdemoToTranid()
                    + source.getCdemoGeneralInfo().getCdemoToProgram()
                    + source.getCdemoGeneralInfo().getCdemoUserId()
                    + source.getCdemoGeneralInfo().getCdemoUserType()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoGeneralInfo().getCdemoPgmContext(), 1)
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCustomerInfo().getCdemoCustId(), 9)
                    + source.getCdemoCustomerInfo().getCdemoCustFname()
                    + source.getCdemoCustomerInfo().getCdemoCustMname()
                    + source.getCdemoCustomerInfo().getCdemoCustLname()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoAccountInfo().getCdemoAcctId(), 11)
                    + source.getCdemoAccountInfo().getCdemoAcctStatus()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCardInfo().getCdemoCardNum(), 16)
                    + source.getCdemoMoreInfo().getCdemoLastMap()
                    + source.getCdemoMoreInfo().getCdemoLastMapset());
        }

        @AfterMapping
        default void makeSource(Cosgn00cDfhcommarea source,
                @MappingTarget Cosgn00cCarddemoCommarea target) {
            target.getCdemoGeneralInfo().setCdemoFromTranid(
                    source.getLkCommarea().substring(0, 4));
            target.getCdemoGeneralInfo().setCdemoFromProgram(
                    source.getLkCommarea().substring(4, 12));
            target.getCdemoGeneralInfo().setCdemoToTranid(
                    source.getLkCommarea().substring(12, 16));
            target.getCdemoGeneralInfo().setCdemoToProgram(
                    source.getLkCommarea().substring(16, 24));
            target.getCdemoGeneralInfo().setCdemoUserId(
                    source.getLkCommarea().substring(24, 32));
            target.getCdemoGeneralInfo().setCdemoUserType(
                    source.getLkCommarea().substring(32, 33));
            target.getCdemoGeneralInfo().setCdemoPgmContext(
                    ((int) DataConverter.convZonedStringToLong(source
                            .getLkCommarea().substring(33, 34), 1)));
            target.getCdemoCustomerInfo().setCdemoCustId(
                    ((int) DataConverter.convZonedStringToLong(source
                            .getLkCommarea().substring(34, 43), 9)));
            target.getCdemoCustomerInfo().setCdemoCustFname(
                    source.getLkCommarea().substring(43, 68));
            target.getCdemoCustomerInfo().setCdemoCustMname(
                    source.getLkCommarea().substring(68, 93));
            target.getCdemoCustomerInfo().setCdemoCustLname(
                    source.getLkCommarea().substring(93, 118));
            target.getCdemoAccountInfo().setCdemoAcctId(
                    DataConverter.convZonedStringToLong(source.getLkCommarea()
                            .substring(118, 129), 11));
            target.getCdemoAccountInfo().setCdemoAcctStatus(
                    source.getLkCommarea().substring(129, 130));
            target.getCdemoCardInfo().setCdemoCardNum(
                    DataConverter.convZonedStringToLong(source.getLkCommarea()
                            .substring(130, 146), 16));
            target.getCdemoMoreInfo().setCdemoLastMap(
                    source.getLkCommarea().substring(146, 153));
            target.getCdemoMoreInfo().setCdemoLastMapset(
                    source.getLkCommarea().substring(153, 160));
        }
    }

    /** 
     * <p>Mapper class to convert data for CICS processing</p>
     * <ul>
     * <li>source class: {@link Cosgn00cSecUserData}</li>
     * <li>target class: {@link AwsM2CarddemoUsrsecVsamKsdsDto}</li>
     * </ul>
     */
    @Mapper(unmappedTargetPolicy = ReportingPolicy.IGNORE)
    public interface Cosgn00cSecUserDataToAwsM2CarddemoUsrsecVsamKsdsDto {
        Cosgn00cSecUserDataToAwsM2CarddemoUsrsecVsamKsdsDto INSTANCE = Mappers
                .getMapper(Cosgn00cSecUserDataToAwsM2CarddemoUsrsecVsamKsdsDto.class);

        @Mapping(source = "secUsrId", target = "secUsrId")
        @Mapping(source = "secUsrFname", target = "secUsrFname")
        @Mapping(source = "secUsrLname", target = "secUsrLname")
        @Mapping(source = "secUsrPwd", target = "secUsrPwd")
        @Mapping(source = "secUsrType", target = "secUsrType")
        @Mapping(source = "secUsrFiller", target = "secUsrFiller")
        AwsM2CarddemoUsrsecVsamKsdsDto toTarget(Cosgn00cSecUserData source);

        @Mapping(source = "secUsrId", target = "secUsrId")
        @Mapping(source = "secUsrFname", target = "secUsrFname")
        @Mapping(source = "secUsrLname", target = "secUsrLname")
        @Mapping(source = "secUsrPwd", target = "secUsrPwd")
        @Mapping(source = "secUsrType", target = "secUsrType")
        @Mapping(source = "secUsrFiller", target = "secUsrFiller")
        Cosgn00cSecUserData toSource(AwsM2CarddemoUsrsecVsamKsdsDto source);
    }

    /** 
     * <p>Mapper class to convert data for CICS processing</p>
     * <ul>
     * <li>source class: {@link Cosgn00cCarddemoCommarea}</li>
     * <li>target class: {@link Coadm01cDfhcommarea}</li>
     * </ul>
     */
    @Mapper(unmappedTargetPolicy = ReportingPolicy.IGNORE)
    public interface Cosgn00cCarddemoCommareaToCoadm01cDfhcommarea {
        Cosgn00cCarddemoCommareaToCoadm01cDfhcommarea INSTANCE = Mappers
                .getMapper(Cosgn00cCarddemoCommareaToCoadm01cDfhcommarea.class);

        Coadm01cDfhcommarea toTarget(Cosgn00cCarddemoCommarea source);

        Cosgn00cCarddemoCommarea toSource(Coadm01cDfhcommarea source);

        @AfterMapping
        default void makeTarget(Cosgn00cCarddemoCommarea source,
                @MappingTarget Coadm01cDfhcommarea target) {
            target.setLkCommarea(source.getCdemoGeneralInfo()
                    .getCdemoFromTranid()
                    + source.getCdemoGeneralInfo().getCdemoFromProgram()
                    + source.getCdemoGeneralInfo().getCdemoToTranid()
                    + source.getCdemoGeneralInfo().getCdemoToProgram()
                    + source.getCdemoGeneralInfo().getCdemoUserId()
                    + source.getCdemoGeneralInfo().getCdemoUserType()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoGeneralInfo().getCdemoPgmContext(), 1)
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCustomerInfo().getCdemoCustId(), 9)
                    + source.getCdemoCustomerInfo().getCdemoCustFname()
                    + source.getCdemoCustomerInfo().getCdemoCustMname()
                    + source.getCdemoCustomerInfo().getCdemoCustLname()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoAccountInfo().getCdemoAcctId(), 11)
                    + source.getCdemoAccountInfo().getCdemoAcctStatus()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCardInfo().getCdemoCardNum(), 16)
                    + source.getCdemoMoreInfo().getCdemoLastMap()
                    + source.getCdemoMoreInfo().getCdemoLastMapset());
        }

        @AfterMapping
        default void makeSource(Coadm01cDfhcommarea source,
                @MappingTarget Cosgn00cCarddemoCommarea target) {
            target.getCdemoGeneralInfo().setCdemoFromTranid(
                    source.getLkCommarea().substring(0, 4));
            target.getCdemoGeneralInfo().setCdemoFromProgram(
                    source.getLkCommarea().substring(4, 12));
            target.getCdemoGeneralInfo().setCdemoToTranid(
                    source.getLkCommarea().substring(12, 16));
            target.getCdemoGeneralInfo().setCdemoToProgram(
                    source.getLkCommarea().substring(16, 24));
            target.getCdemoGeneralInfo().setCdemoUserId(
                    source.getLkCommarea().substring(24, 32));
            target.getCdemoGeneralInfo().setCdemoUserType(
                    source.getLkCommarea().substring(32, 33));
            target.getCdemoGeneralInfo().setCdemoPgmContext(
                    ((int) DataConverter.convZonedStringToLong(source
                            .getLkCommarea().substring(33, 34), 1)));
            target.getCdemoCustomerInfo().setCdemoCustId(
                    ((int) DataConverter.convZonedStringToLong(source
                            .getLkCommarea().substring(34, 43), 9)));
            target.getCdemoCustomerInfo().setCdemoCustFname(
                    source.getLkCommarea().substring(43, 68));
            target.getCdemoCustomerInfo().setCdemoCustMname(
                    source.getLkCommarea().substring(68, 93));
            target.getCdemoCustomerInfo().setCdemoCustLname(
                    source.getLkCommarea().substring(93, 118));
            target.getCdemoAccountInfo().setCdemoAcctId(
                    DataConverter.convZonedStringToLong(source.getLkCommarea()
                            .substring(118, 129), 11));
            target.getCdemoAccountInfo().setCdemoAcctStatus(
                    source.getLkCommarea().substring(129, 130));
            target.getCdemoCardInfo().setCdemoCardNum(
                    DataConverter.convZonedStringToLong(source.getLkCommarea()
                            .substring(130, 146), 16));
            target.getCdemoMoreInfo().setCdemoLastMap(
                    source.getLkCommarea().substring(146, 153));
            target.getCdemoMoreInfo().setCdemoLastMapset(
                    source.getLkCommarea().substring(153, 160));
        }
    }

    /** 
     * <p>Mapper class to convert data for CICS processing</p>
     * <ul>
     * <li>source class: {@link Cosgn00cCarddemoCommarea}</li>
     * <li>target class: {@link Comen01cDfhcommarea}</li>
     * </ul>
     */
    @Mapper(unmappedTargetPolicy = ReportingPolicy.IGNORE)
    public interface Cosgn00cCarddemoCommareaToComen01cDfhcommarea {
        Cosgn00cCarddemoCommareaToComen01cDfhcommarea INSTANCE = Mappers
                .getMapper(Cosgn00cCarddemoCommareaToComen01cDfhcommarea.class);

        Comen01cDfhcommarea toTarget(Cosgn00cCarddemoCommarea source);

        Cosgn00cCarddemoCommarea toSource(Comen01cDfhcommarea source);

        @AfterMapping
        default void makeTarget(Cosgn00cCarddemoCommarea source,
                @MappingTarget Comen01cDfhcommarea target) {
            target.setLkCommarea(source.getCdemoGeneralInfo()
                    .getCdemoFromTranid()
                    + source.getCdemoGeneralInfo().getCdemoFromProgram()
                    + source.getCdemoGeneralInfo().getCdemoToTranid()
                    + source.getCdemoGeneralInfo().getCdemoToProgram()
                    + source.getCdemoGeneralInfo().getCdemoUserId()
                    + source.getCdemoGeneralInfo().getCdemoUserType()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoGeneralInfo().getCdemoPgmContext(), 1)
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCustomerInfo().getCdemoCustId(), 9)
                    + source.getCdemoCustomerInfo().getCdemoCustFname()
                    + source.getCdemoCustomerInfo().getCdemoCustMname()
                    + source.getCdemoCustomerInfo().getCdemoCustLname()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoAccountInfo().getCdemoAcctId(), 11)
                    + source.getCdemoAccountInfo().getCdemoAcctStatus()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCardInfo().getCdemoCardNum(), 16)
                    + source.getCdemoMoreInfo().getCdemoLastMap()
                    + source.getCdemoMoreInfo().getCdemoLastMapset());
        }

        @AfterMapping
        default void makeSource(Comen01cDfhcommarea source,
                @MappingTarget Cosgn00cCarddemoCommarea target) {
            target.getCdemoGeneralInfo().setCdemoFromTranid(
                    source.getLkCommarea().substring(0, 4));
            target.getCdemoGeneralInfo().setCdemoFromProgram(
                    source.getLkCommarea().substring(4, 12));
            target.getCdemoGeneralInfo().setCdemoToTranid(
                    source.getLkCommarea().substring(12, 16));
            target.getCdemoGeneralInfo().setCdemoToProgram(
                    source.getLkCommarea().substring(16, 24));
            target.getCdemoGeneralInfo().setCdemoUserId(
                    source.getLkCommarea().substring(24, 32));
            target.getCdemoGeneralInfo().setCdemoUserType(
                    source.getLkCommarea().substring(32, 33));
            target.getCdemoGeneralInfo().setCdemoPgmContext(
                    ((int) DataConverter.convZonedStringToLong(source
                            .getLkCommarea().substring(33, 34), 1)));
            target.getCdemoCustomerInfo().setCdemoCustId(
                    ((int) DataConverter.convZonedStringToLong(source
                            .getLkCommarea().substring(34, 43), 9)));
            target.getCdemoCustomerInfo().setCdemoCustFname(
                    source.getLkCommarea().substring(43, 68));
            target.getCdemoCustomerInfo().setCdemoCustMname(
                    source.getLkCommarea().substring(68, 93));
            target.getCdemoCustomerInfo().setCdemoCustLname(
                    source.getLkCommarea().substring(93, 118));
            target.getCdemoAccountInfo().setCdemoAcctId(
                    DataConverter.convZonedStringToLong(source.getLkCommarea()
                            .substring(118, 129), 11));
            target.getCdemoAccountInfo().setCdemoAcctStatus(
                    source.getLkCommarea().substring(129, 130));
            target.getCdemoCardInfo().setCdemoCardNum(
                    DataConverter.convZonedStringToLong(source.getLkCommarea()
                            .substring(130, 146), 16));
            target.getCdemoMoreInfo().setCdemoLastMap(
                    source.getLkCommarea().substring(146, 153));
            target.getCdemoMoreInfo().setCdemoLastMapset(
                    source.getLkCommarea().substring(153, 160));
        }
    }
}
