package aws.carddemo.mapper;

import com.tmax.openframe.DataConverter;
import org.apache.commons.lang3.StringUtils;
import org.mapstruct.*;
import org.mapstruct.factory.*;
import aws.carddemo.variable.group.Cotrn01cCarddemoCommarea;
import aws.carddemo.variable.group.Cosgn00cDfhcommarea;
import aws.carddemo.variable.group.Comen01cDfhcommarea;
import aws.carddemo.variable.group.Cotrn01cTranRecord;
import aws.carddemo.dto.AwsM2CarddemoTransactVsamKsdsDto;
import aws.carddemo.variable.group.Cotrn01cDfhcommarea;
import aws.carddemo.variable.group.Cotrn00cDfhcommarea;
import lombok.*;
import java.math.*;
import java.util.*;

/** 
 * <p>This source code was generated by T-Up OpenFrame COBOL to Java migrator</p>
 * <p>  Generation date : 2024/05/02 05:57:43 UTC</p>
 * <hr>
 * <p>Mapper class for converting data between different classes</p>
 */
public interface Cotrn01cMapperInterface {
    /** 
     * <p>Mapper class to convert data for CICS processing</p>
     * <ul>
     * <li>source class: {@link Cotrn01cCarddemoCommarea}</li>
     * <li>target class: {@link Cosgn00cDfhcommarea}</li>
     * </ul>
     */
    @Mapper(unmappedTargetPolicy = ReportingPolicy.IGNORE)
    public interface Cotrn01cCarddemoCommareaToCosgn00cDfhcommarea {
        Cotrn01cCarddemoCommareaToCosgn00cDfhcommarea INSTANCE = Mappers
                .getMapper(Cotrn01cCarddemoCommareaToCosgn00cDfhcommarea.class);

        Cosgn00cDfhcommarea toTarget(Cotrn01cCarddemoCommarea source);

        Cotrn01cCarddemoCommarea toSource(Cosgn00cDfhcommarea source);

        @AfterMapping
        default void makeTarget(Cotrn01cCarddemoCommarea source,
                @MappingTarget Cosgn00cDfhcommarea target) {
            target.setLkCommarea(source.getCdemoGeneralInfo()
                    .getCdemoFromTranid()
                    + source.getCdemoGeneralInfo().getCdemoFromProgram()
                    + source.getCdemoGeneralInfo().getCdemoToTranid()
                    + source.getCdemoGeneralInfo().getCdemoToProgram()
                    + source.getCdemoGeneralInfo().getCdemoUserId()
                    + source.getCdemoGeneralInfo().getCdemoUserType()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoGeneralInfo().getCdemoPgmContext(), 1)
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCustomerInfo().getCdemoCustId(), 9)
                    + source.getCdemoCustomerInfo().getCdemoCustFname()
                    + source.getCdemoCustomerInfo().getCdemoCustMname()
                    + source.getCdemoCustomerInfo().getCdemoCustLname()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoAccountInfo().getCdemoAcctId(), 11)
                    + source.getCdemoAccountInfo().getCdemoAcctStatus()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCardInfo().getCdemoCardNum(), 16)
                    + source.getCdemoMoreInfo().getCdemoLastMap()
                    + source.getCdemoMoreInfo().getCdemoLastMapset()
                    + source.getCdemoCt01Info().getCdemoCt01TrnidFirst()
                    + source.getCdemoCt01Info().getCdemoCt01TrnidLast()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCt01Info().getCdemoCt01PageNum(), 8)
                    + source.getCdemoCt01Info().getCdemoCt01NextPageFlg()
                    + source.getCdemoCt01Info().getCdemoCt01TrnSelFlg()
                    + source.getCdemoCt01Info().getCdemoCt01TrnSelected());
        }

        @AfterMapping
        default void makeSource(Cosgn00cDfhcommarea source,
                @MappingTarget Cotrn01cCarddemoCommarea target) {
            target.getCdemoGeneralInfo().setCdemoFromTranid(
                    source.getLkCommarea().substring(0, 4));
            target.getCdemoGeneralInfo().setCdemoFromProgram(
                    source.getLkCommarea().substring(4, 12));
            target.getCdemoGeneralInfo().setCdemoToTranid(
                    source.getLkCommarea().substring(12, 16));
            target.getCdemoGeneralInfo().setCdemoToProgram(
                    source.getLkCommarea().substring(16, 24));
            target.getCdemoGeneralInfo().setCdemoUserId(
                    source.getLkCommarea().substring(24, 32));
            target.getCdemoGeneralInfo().setCdemoUserType(
                    source.getLkCommarea().substring(32, 33));
            target.getCdemoGeneralInfo().setCdemoPgmContext(
                    ((int) DataConverter.convZonedStringToLong(source
                            .getLkCommarea().substring(33, 34), 1)));
            target.getCdemoCustomerInfo().setCdemoCustId(
                    ((int) DataConverter.convZonedStringToLong(source
                            .getLkCommarea().substring(34, 43), 9)));
            target.getCdemoCustomerInfo().setCdemoCustFname(
                    source.getLkCommarea().substring(43, 68));
            target.getCdemoCustomerInfo().setCdemoCustMname(
                    source.getLkCommarea().substring(68, 93));
            target.getCdemoCustomerInfo().setCdemoCustLname(
                    source.getLkCommarea().substring(93, 118));
            target.getCdemoAccountInfo().setCdemoAcctId(
                    DataConverter.convZonedStringToLong(source.getLkCommarea()
                            .substring(118, 129), 11));
            target.getCdemoAccountInfo().setCdemoAcctStatus(
                    source.getLkCommarea().substring(129, 130));
            target.getCdemoCardInfo().setCdemoCardNum(
                    DataConverter.convZonedStringToLong(source.getLkCommarea()
                            .substring(130, 146), 16));
            target.getCdemoMoreInfo().setCdemoLastMap(
                    source.getLkCommarea().substring(146, 153));
            target.getCdemoMoreInfo().setCdemoLastMapset(
                    source.getLkCommarea().substring(153, 160));
            target.getCdemoCt01Info().setCdemoCt01TrnidFirst(
                    source.getLkCommarea().substring(160, 176));
            target.getCdemoCt01Info().setCdemoCt01TrnidLast(
                    source.getLkCommarea().substring(176, 192));
            target.getCdemoCt01Info().setCdemoCt01PageNum(
                    ((int) DataConverter.convZonedStringToLong(source
                            .getLkCommarea().substring(192, 200), 8)));
            target.getCdemoCt01Info().setCdemoCt01NextPageFlg(
                    source.getLkCommarea().substring(200, 201));
            target.getCdemoCt01Info().setCdemoCt01TrnSelFlg(
                    source.getLkCommarea().substring(201, 202));
            target.getCdemoCt01Info().setCdemoCt01TrnSelected(
                    source.getLkCommarea().substring(202, 218));
        }
    }

    /** 
     * <p>Mapper class to convert data for CICS processing</p>
     * <ul>
     * <li>source class: {@link Cotrn01cCarddemoCommarea}</li>
     * <li>target class: {@link Comen01cDfhcommarea}</li>
     * </ul>
     */
    @Mapper(unmappedTargetPolicy = ReportingPolicy.IGNORE)
    public interface Cotrn01cCarddemoCommareaToComen01cDfhcommarea {
        Cotrn01cCarddemoCommareaToComen01cDfhcommarea INSTANCE = Mappers
                .getMapper(Cotrn01cCarddemoCommareaToComen01cDfhcommarea.class);

        Comen01cDfhcommarea toTarget(Cotrn01cCarddemoCommarea source);

        Cotrn01cCarddemoCommarea toSource(Comen01cDfhcommarea source);

        @AfterMapping
        default void makeTarget(Cotrn01cCarddemoCommarea source,
                @MappingTarget Comen01cDfhcommarea target) {
            target.setLkCommarea(source.getCdemoGeneralInfo()
                    .getCdemoFromTranid()
                    + source.getCdemoGeneralInfo().getCdemoFromProgram()
                    + source.getCdemoGeneralInfo().getCdemoToTranid()
                    + source.getCdemoGeneralInfo().getCdemoToProgram()
                    + source.getCdemoGeneralInfo().getCdemoUserId()
                    + source.getCdemoGeneralInfo().getCdemoUserType()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoGeneralInfo().getCdemoPgmContext(), 1)
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCustomerInfo().getCdemoCustId(), 9)
                    + source.getCdemoCustomerInfo().getCdemoCustFname()
                    + source.getCdemoCustomerInfo().getCdemoCustMname()
                    + source.getCdemoCustomerInfo().getCdemoCustLname()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoAccountInfo().getCdemoAcctId(), 11)
                    + source.getCdemoAccountInfo().getCdemoAcctStatus()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCardInfo().getCdemoCardNum(), 16)
                    + source.getCdemoMoreInfo().getCdemoLastMap()
                    + source.getCdemoMoreInfo().getCdemoLastMapset()
                    + source.getCdemoCt01Info().getCdemoCt01TrnidFirst()
                    + source.getCdemoCt01Info().getCdemoCt01TrnidLast()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCt01Info().getCdemoCt01PageNum(), 8)
                    + source.getCdemoCt01Info().getCdemoCt01NextPageFlg()
                    + source.getCdemoCt01Info().getCdemoCt01TrnSelFlg()
                    + source.getCdemoCt01Info().getCdemoCt01TrnSelected());
        }

        @AfterMapping
        default void makeSource(Comen01cDfhcommarea source,
                @MappingTarget Cotrn01cCarddemoCommarea target) {
            target.getCdemoGeneralInfo().setCdemoFromTranid(
                    source.getLkCommarea().substring(0, 4));
            target.getCdemoGeneralInfo().setCdemoFromProgram(
                    source.getLkCommarea().substring(4, 12));
            target.getCdemoGeneralInfo().setCdemoToTranid(
                    source.getLkCommarea().substring(12, 16));
            target.getCdemoGeneralInfo().setCdemoToProgram(
                    source.getLkCommarea().substring(16, 24));
            target.getCdemoGeneralInfo().setCdemoUserId(
                    source.getLkCommarea().substring(24, 32));
            target.getCdemoGeneralInfo().setCdemoUserType(
                    source.getLkCommarea().substring(32, 33));
            target.getCdemoGeneralInfo().setCdemoPgmContext(
                    ((int) DataConverter.convZonedStringToLong(source
                            .getLkCommarea().substring(33, 34), 1)));
            target.getCdemoCustomerInfo().setCdemoCustId(
                    ((int) DataConverter.convZonedStringToLong(source
                            .getLkCommarea().substring(34, 43), 9)));
            target.getCdemoCustomerInfo().setCdemoCustFname(
                    source.getLkCommarea().substring(43, 68));
            target.getCdemoCustomerInfo().setCdemoCustMname(
                    source.getLkCommarea().substring(68, 93));
            target.getCdemoCustomerInfo().setCdemoCustLname(
                    source.getLkCommarea().substring(93, 118));
            target.getCdemoAccountInfo().setCdemoAcctId(
                    DataConverter.convZonedStringToLong(source.getLkCommarea()
                            .substring(118, 129), 11));
            target.getCdemoAccountInfo().setCdemoAcctStatus(
                    source.getLkCommarea().substring(129, 130));
            target.getCdemoCardInfo().setCdemoCardNum(
                    DataConverter.convZonedStringToLong(source.getLkCommarea()
                            .substring(130, 146), 16));
            target.getCdemoMoreInfo().setCdemoLastMap(
                    source.getLkCommarea().substring(146, 153));
            target.getCdemoMoreInfo().setCdemoLastMapset(
                    source.getLkCommarea().substring(153, 160));
            target.getCdemoCt01Info().setCdemoCt01TrnidFirst(
                    source.getLkCommarea().substring(160, 176));
            target.getCdemoCt01Info().setCdemoCt01TrnidLast(
                    source.getLkCommarea().substring(176, 192));
            target.getCdemoCt01Info().setCdemoCt01PageNum(
                    ((int) DataConverter.convZonedStringToLong(source
                            .getLkCommarea().substring(192, 200), 8)));
            target.getCdemoCt01Info().setCdemoCt01NextPageFlg(
                    source.getLkCommarea().substring(200, 201));
            target.getCdemoCt01Info().setCdemoCt01TrnSelFlg(
                    source.getLkCommarea().substring(201, 202));
            target.getCdemoCt01Info().setCdemoCt01TrnSelected(
                    source.getLkCommarea().substring(202, 218));
        }
    }

    /** 
     * <p>Mapper class to convert data for CICS processing</p>
     * <ul>
     * <li>source class: {@link Cotrn01cTranRecord}</li>
     * <li>target class: {@link AwsM2CarddemoTransactVsamKsdsDto}</li>
     * </ul>
     */
    @Mapper(unmappedTargetPolicy = ReportingPolicy.IGNORE)
    public interface Cotrn01cTranRecordToAwsM2CarddemoTransactVsamKsdsDto {
        Cotrn01cTranRecordToAwsM2CarddemoTransactVsamKsdsDto INSTANCE = Mappers
                .getMapper(Cotrn01cTranRecordToAwsM2CarddemoTransactVsamKsdsDto.class);

        @Mapping(source = "tranId", target = "tranId")
        @Mapping(source = "tranTypeCd", target = "tranTypeCd")
        @Mapping(source = "tranCatCd", target = "tranCatCd")
        @Mapping(source = "tranSource", target = "tranSource")
        @Mapping(source = "tranDesc", target = "tranDesc")
        @Mapping(source = "tranAmt", target = "tranAmt")
        @Mapping(source = "tranMerchantId", target = "tranMerchantId")
        @Mapping(source = "tranMerchantName", target = "tranMerchantName")
        @Mapping(source = "tranMerchantCity", target = "tranMerchantCity")
        @Mapping(source = "tranMerchantZip", target = "tranMerchantZip")
        @Mapping(source = "tranCardNum", target = "tranCardNum")
        @Mapping(source = "tranOrigTs", target = "tranOrigTs")
        @Mapping(source = "tranProcTs", target = "tranProcTs")
        @Mapping(source = "OFFILLER1", target = "filler")
        AwsM2CarddemoTransactVsamKsdsDto toTarget(Cotrn01cTranRecord source);

        @Mapping(source = "tranId", target = "tranId")
        @Mapping(source = "tranTypeCd", target = "tranTypeCd")
        @Mapping(source = "tranCatCd", target = "tranCatCd")
        @Mapping(source = "tranSource", target = "tranSource")
        @Mapping(source = "tranDesc", target = "tranDesc")
        @Mapping(source = "tranAmt", target = "tranAmt")
        @Mapping(source = "tranMerchantId", target = "tranMerchantId")
        @Mapping(source = "tranMerchantName", target = "tranMerchantName")
        @Mapping(source = "tranMerchantCity", target = "tranMerchantCity")
        @Mapping(source = "tranMerchantZip", target = "tranMerchantZip")
        @Mapping(source = "tranCardNum", target = "tranCardNum")
        @Mapping(source = "tranOrigTs", target = "tranOrigTs")
        @Mapping(source = "tranProcTs", target = "tranProcTs")
        @Mapping(source = "filler", target = "OFFILLER1")
        Cotrn01cTranRecord toSource(AwsM2CarddemoTransactVsamKsdsDto source);
    }

    /** 
     * <p>Mapper class to convert data for CICS processing</p>
     * <ul>
     * <li>source class: {@link Cotrn01cCarddemoCommarea}</li>
     * <li>target class: {@link Cotrn01cDfhcommarea}</li>
     * </ul>
     */
    @Mapper(unmappedTargetPolicy = ReportingPolicy.IGNORE)
    public interface Cotrn01cCarddemoCommareaToCotrn01cDfhcommarea {
        Cotrn01cCarddemoCommareaToCotrn01cDfhcommarea INSTANCE = Mappers
                .getMapper(Cotrn01cCarddemoCommareaToCotrn01cDfhcommarea.class);

        Cotrn01cDfhcommarea toTarget(Cotrn01cCarddemoCommarea source);

        Cotrn01cCarddemoCommarea toSource(Cotrn01cDfhcommarea source);

        @AfterMapping
        default void makeTarget(Cotrn01cCarddemoCommarea source,
                @MappingTarget Cotrn01cDfhcommarea target) {
            target.setLkCommarea(source.getCdemoGeneralInfo()
                    .getCdemoFromTranid()
                    + source.getCdemoGeneralInfo().getCdemoFromProgram()
                    + source.getCdemoGeneralInfo().getCdemoToTranid()
                    + source.getCdemoGeneralInfo().getCdemoToProgram()
                    + source.getCdemoGeneralInfo().getCdemoUserId()
                    + source.getCdemoGeneralInfo().getCdemoUserType()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoGeneralInfo().getCdemoPgmContext(), 1)
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCustomerInfo().getCdemoCustId(), 9)
                    + source.getCdemoCustomerInfo().getCdemoCustFname()
                    + source.getCdemoCustomerInfo().getCdemoCustMname()
                    + source.getCdemoCustomerInfo().getCdemoCustLname()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoAccountInfo().getCdemoAcctId(), 11)
                    + source.getCdemoAccountInfo().getCdemoAcctStatus()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCardInfo().getCdemoCardNum(), 16)
                    + source.getCdemoMoreInfo().getCdemoLastMap()
                    + source.getCdemoMoreInfo().getCdemoLastMapset()
                    + source.getCdemoCt01Info().getCdemoCt01TrnidFirst()
                    + source.getCdemoCt01Info().getCdemoCt01TrnidLast()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCt01Info().getCdemoCt01PageNum(), 8)
                    + source.getCdemoCt01Info().getCdemoCt01NextPageFlg()
                    + source.getCdemoCt01Info().getCdemoCt01TrnSelFlg()
                    + source.getCdemoCt01Info().getCdemoCt01TrnSelected());
        }

        @AfterMapping
        default void makeSource(Cotrn01cDfhcommarea source,
                @MappingTarget Cotrn01cCarddemoCommarea target) {
            target.getCdemoGeneralInfo().setCdemoFromTranid(
                    source.getLkCommarea().substring(0, 4));
            target.getCdemoGeneralInfo().setCdemoFromProgram(
                    source.getLkCommarea().substring(4, 12));
            target.getCdemoGeneralInfo().setCdemoToTranid(
                    source.getLkCommarea().substring(12, 16));
            target.getCdemoGeneralInfo().setCdemoToProgram(
                    source.getLkCommarea().substring(16, 24));
            target.getCdemoGeneralInfo().setCdemoUserId(
                    source.getLkCommarea().substring(24, 32));
            target.getCdemoGeneralInfo().setCdemoUserType(
                    source.getLkCommarea().substring(32, 33));
            target.getCdemoGeneralInfo().setCdemoPgmContext(
                    ((int) DataConverter.convZonedStringToLong(source
                            .getLkCommarea().substring(33, 34), 1)));
            target.getCdemoCustomerInfo().setCdemoCustId(
                    ((int) DataConverter.convZonedStringToLong(source
                            .getLkCommarea().substring(34, 43), 9)));
            target.getCdemoCustomerInfo().setCdemoCustFname(
                    source.getLkCommarea().substring(43, 68));
            target.getCdemoCustomerInfo().setCdemoCustMname(
                    source.getLkCommarea().substring(68, 93));
            target.getCdemoCustomerInfo().setCdemoCustLname(
                    source.getLkCommarea().substring(93, 118));
            target.getCdemoAccountInfo().setCdemoAcctId(
                    DataConverter.convZonedStringToLong(source.getLkCommarea()
                            .substring(118, 129), 11));
            target.getCdemoAccountInfo().setCdemoAcctStatus(
                    source.getLkCommarea().substring(129, 130));
            target.getCdemoCardInfo().setCdemoCardNum(
                    DataConverter.convZonedStringToLong(source.getLkCommarea()
                            .substring(130, 146), 16));
            target.getCdemoMoreInfo().setCdemoLastMap(
                    source.getLkCommarea().substring(146, 153));
            target.getCdemoMoreInfo().setCdemoLastMapset(
                    source.getLkCommarea().substring(153, 160));
            target.getCdemoCt01Info().setCdemoCt01TrnidFirst(
                    source.getLkCommarea().substring(160, 176));
            target.getCdemoCt01Info().setCdemoCt01TrnidLast(
                    source.getLkCommarea().substring(176, 192));
            target.getCdemoCt01Info().setCdemoCt01PageNum(
                    ((int) DataConverter.convZonedStringToLong(source
                            .getLkCommarea().substring(192, 200), 8)));
            target.getCdemoCt01Info().setCdemoCt01NextPageFlg(
                    source.getLkCommarea().substring(200, 201));
            target.getCdemoCt01Info().setCdemoCt01TrnSelFlg(
                    source.getLkCommarea().substring(201, 202));
            target.getCdemoCt01Info().setCdemoCt01TrnSelected(
                    source.getLkCommarea().substring(202, 218));
        }
    }

    /** 
     * <p>Mapper class to convert data for CICS processing</p>
     * <ul>
     * <li>source class: {@link Cotrn01cCarddemoCommarea}</li>
     * <li>target class: {@link Cotrn00cDfhcommarea}</li>
     * </ul>
     */
    @Mapper(unmappedTargetPolicy = ReportingPolicy.IGNORE)
    public interface Cotrn01cCarddemoCommareaToCotrn00cDfhcommarea {
        Cotrn01cCarddemoCommareaToCotrn00cDfhcommarea INSTANCE = Mappers
                .getMapper(Cotrn01cCarddemoCommareaToCotrn00cDfhcommarea.class);

        Cotrn00cDfhcommarea toTarget(Cotrn01cCarddemoCommarea source);

        Cotrn01cCarddemoCommarea toSource(Cotrn00cDfhcommarea source);

        @AfterMapping
        default void makeTarget(Cotrn01cCarddemoCommarea source,
                @MappingTarget Cotrn00cDfhcommarea target) {
            target.setLkCommarea(source.getCdemoGeneralInfo()
                    .getCdemoFromTranid()
                    + source.getCdemoGeneralInfo().getCdemoFromProgram()
                    + source.getCdemoGeneralInfo().getCdemoToTranid()
                    + source.getCdemoGeneralInfo().getCdemoToProgram()
                    + source.getCdemoGeneralInfo().getCdemoUserId()
                    + source.getCdemoGeneralInfo().getCdemoUserType()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoGeneralInfo().getCdemoPgmContext(), 1)
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCustomerInfo().getCdemoCustId(), 9)
                    + source.getCdemoCustomerInfo().getCdemoCustFname()
                    + source.getCdemoCustomerInfo().getCdemoCustMname()
                    + source.getCdemoCustomerInfo().getCdemoCustLname()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoAccountInfo().getCdemoAcctId(), 11)
                    + source.getCdemoAccountInfo().getCdemoAcctStatus()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCardInfo().getCdemoCardNum(), 16)
                    + source.getCdemoMoreInfo().getCdemoLastMap()
                    + source.getCdemoMoreInfo().getCdemoLastMapset()
                    + source.getCdemoCt01Info().getCdemoCt01TrnidFirst()
                    + source.getCdemoCt01Info().getCdemoCt01TrnidLast()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCt01Info().getCdemoCt01PageNum(), 8)
                    + source.getCdemoCt01Info().getCdemoCt01NextPageFlg()
                    + source.getCdemoCt01Info().getCdemoCt01TrnSelFlg()
                    + source.getCdemoCt01Info().getCdemoCt01TrnSelected());
        }

        @AfterMapping
        default void makeSource(Cotrn00cDfhcommarea source,
                @MappingTarget Cotrn01cCarddemoCommarea target) {
            target.getCdemoGeneralInfo().setCdemoFromTranid(
                    source.getLkCommarea().substring(0, 4));
            target.getCdemoGeneralInfo().setCdemoFromProgram(
                    source.getLkCommarea().substring(4, 12));
            target.getCdemoGeneralInfo().setCdemoToTranid(
                    source.getLkCommarea().substring(12, 16));
            target.getCdemoGeneralInfo().setCdemoToProgram(
                    source.getLkCommarea().substring(16, 24));
            target.getCdemoGeneralInfo().setCdemoUserId(
                    source.getLkCommarea().substring(24, 32));
            target.getCdemoGeneralInfo().setCdemoUserType(
                    source.getLkCommarea().substring(32, 33));
            target.getCdemoGeneralInfo().setCdemoPgmContext(
                    ((int) DataConverter.convZonedStringToLong(source
                            .getLkCommarea().substring(33, 34), 1)));
            target.getCdemoCustomerInfo().setCdemoCustId(
                    ((int) DataConverter.convZonedStringToLong(source
                            .getLkCommarea().substring(34, 43), 9)));
            target.getCdemoCustomerInfo().setCdemoCustFname(
                    source.getLkCommarea().substring(43, 68));
            target.getCdemoCustomerInfo().setCdemoCustMname(
                    source.getLkCommarea().substring(68, 93));
            target.getCdemoCustomerInfo().setCdemoCustLname(
                    source.getLkCommarea().substring(93, 118));
            target.getCdemoAccountInfo().setCdemoAcctId(
                    DataConverter.convZonedStringToLong(source.getLkCommarea()
                            .substring(118, 129), 11));
            target.getCdemoAccountInfo().setCdemoAcctStatus(
                    source.getLkCommarea().substring(129, 130));
            target.getCdemoCardInfo().setCdemoCardNum(
                    DataConverter.convZonedStringToLong(source.getLkCommarea()
                            .substring(130, 146), 16));
            target.getCdemoMoreInfo().setCdemoLastMap(
                    source.getLkCommarea().substring(146, 153));
            target.getCdemoMoreInfo().setCdemoLastMapset(
                    source.getLkCommarea().substring(153, 160));
            target.getCdemoCt01Info().setCdemoCt01TrnidFirst(
                    source.getLkCommarea().substring(160, 176));
            target.getCdemoCt01Info().setCdemoCt01TrnidLast(
                    source.getLkCommarea().substring(176, 192));
            target.getCdemoCt01Info().setCdemoCt01PageNum(
                    ((int) DataConverter.convZonedStringToLong(source
                            .getLkCommarea().substring(192, 200), 8)));
            target.getCdemoCt01Info().setCdemoCt01NextPageFlg(
                    source.getLkCommarea().substring(200, 201));
            target.getCdemoCt01Info().setCdemoCt01TrnSelFlg(
                    source.getLkCommarea().substring(201, 202));
            target.getCdemoCt01Info().setCdemoCt01TrnSelected(
                    source.getLkCommarea().substring(202, 218));
        }
    }
}
