package aws.carddemo.mapper;

import com.tmax.openframe.DataConverter;
import org.apache.commons.lang3.StringUtils;
import org.mapstruct.*;
import org.mapstruct.factory.*;
import aws.carddemo.variable.group.Cotrn02cCarddemoCommarea;
import aws.carddemo.variable.group.Cosgn00cDfhcommarea;
import aws.carddemo.variable.group.Cotrn02cDfhcommarea;
import aws.carddemo.variable.group.Cotrn02cCardXrefRecord;
import aws.carddemo.dto.AwsM2CarddemoCardxrefVsamKsdsDto;
import aws.carddemo.variable.group.Cotrn02cTranRecord;
import aws.carddemo.dto.AwsM2CarddemoTransactVsamKsdsDto;
import aws.carddemo.variable.group.Comen01cDfhcommarea;
import lombok.*;
import java.math.*;
import java.util.*;

/** 
 * <p>This source code was generated by T-Up OpenFrame COBOL to Java migrator</p>
 * <p>  Generation date : 2024/05/02 05:57:49 UTC</p>
 * <hr>
 * <p>Mapper class for converting data between different classes</p>
 */
public interface Cotrn02cMapperInterface {
    /** 
     * <p>Mapper class to convert data for CICS processing</p>
     * <ul>
     * <li>source class: {@link Cotrn02cCarddemoCommarea}</li>
     * <li>target class: {@link Cosgn00cDfhcommarea}</li>
     * </ul>
     */
    @Mapper(unmappedTargetPolicy = ReportingPolicy.IGNORE)
    public interface Cotrn02cCarddemoCommareaToCosgn00cDfhcommarea {
        Cotrn02cCarddemoCommareaToCosgn00cDfhcommarea INSTANCE = Mappers
                .getMapper(Cotrn02cCarddemoCommareaToCosgn00cDfhcommarea.class);

        Cosgn00cDfhcommarea toTarget(Cotrn02cCarddemoCommarea source);

        Cotrn02cCarddemoCommarea toSource(Cosgn00cDfhcommarea source);

        @AfterMapping
        default void makeTarget(Cotrn02cCarddemoCommarea source,
                @MappingTarget Cosgn00cDfhcommarea target) {
            target.setLkCommarea(source.getCdemoGeneralInfo()
                    .getCdemoFromTranid()
                    + source.getCdemoGeneralInfo().getCdemoFromProgram()
                    + source.getCdemoGeneralInfo().getCdemoToTranid()
                    + source.getCdemoGeneralInfo().getCdemoToProgram()
                    + source.getCdemoGeneralInfo().getCdemoUserId()
                    + source.getCdemoGeneralInfo().getCdemoUserType()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoGeneralInfo().getCdemoPgmContext(), 1)
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCustomerInfo().getCdemoCustId(), 9)
                    + source.getCdemoCustomerInfo().getCdemoCustFname()
                    + source.getCdemoCustomerInfo().getCdemoCustMname()
                    + source.getCdemoCustomerInfo().getCdemoCustLname()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoAccountInfo().getCdemoAcctId(), 11)
                    + source.getCdemoAccountInfo().getCdemoAcctStatus()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCardInfo().getCdemoCardNum(), 16)
                    + source.getCdemoMoreInfo().getCdemoLastMap()
                    + source.getCdemoMoreInfo().getCdemoLastMapset()
                    + source.getCdemoCt02Info().getCdemoCt02TrnidFirst()
                    + source.getCdemoCt02Info().getCdemoCt02TrnidLast()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCt02Info().getCdemoCt02PageNum(), 8)
                    + source.getCdemoCt02Info().getCdemoCt02NextPageFlg()
                    + source.getCdemoCt02Info().getCdemoCt02TrnSelFlg()
                    + source.getCdemoCt02Info().getCdemoCt02TrnSelected());
        }

        @AfterMapping
        default void makeSource(Cosgn00cDfhcommarea source,
                @MappingTarget Cotrn02cCarddemoCommarea target) {
            target.getCdemoGeneralInfo().setCdemoFromTranid(
                    source.getLkCommarea().substring(0, 4));
            target.getCdemoGeneralInfo().setCdemoFromProgram(
                    source.getLkCommarea().substring(4, 12));
            target.getCdemoGeneralInfo().setCdemoToTranid(
                    source.getLkCommarea().substring(12, 16));
            target.getCdemoGeneralInfo().setCdemoToProgram(
                    source.getLkCommarea().substring(16, 24));
            target.getCdemoGeneralInfo().setCdemoUserId(
                    source.getLkCommarea().substring(24, 32));
            target.getCdemoGeneralInfo().setCdemoUserType(
                    source.getLkCommarea().substring(32, 33));
            target.getCdemoGeneralInfo().setCdemoPgmContext(
                    ((int) DataConverter.convZonedStringToLong(source
                            .getLkCommarea().substring(33, 34), 1)));
            target.getCdemoCustomerInfo().setCdemoCustId(
                    ((int) DataConverter.convZonedStringToLong(source
                            .getLkCommarea().substring(34, 43), 9)));
            target.getCdemoCustomerInfo().setCdemoCustFname(
                    source.getLkCommarea().substring(43, 68));
            target.getCdemoCustomerInfo().setCdemoCustMname(
                    source.getLkCommarea().substring(68, 93));
            target.getCdemoCustomerInfo().setCdemoCustLname(
                    source.getLkCommarea().substring(93, 118));
            target.getCdemoAccountInfo().setCdemoAcctId(
                    DataConverter.convZonedStringToLong(source.getLkCommarea()
                            .substring(118, 129), 11));
            target.getCdemoAccountInfo().setCdemoAcctStatus(
                    source.getLkCommarea().substring(129, 130));
            target.getCdemoCardInfo().setCdemoCardNum(
                    DataConverter.convZonedStringToLong(source.getLkCommarea()
                            .substring(130, 146), 16));
            target.getCdemoMoreInfo().setCdemoLastMap(
                    source.getLkCommarea().substring(146, 153));
            target.getCdemoMoreInfo().setCdemoLastMapset(
                    source.getLkCommarea().substring(153, 160));
            target.getCdemoCt02Info().setCdemoCt02TrnidFirst(
                    source.getLkCommarea().substring(160, 176));
            target.getCdemoCt02Info().setCdemoCt02TrnidLast(
                    source.getLkCommarea().substring(176, 192));
            target.getCdemoCt02Info().setCdemoCt02PageNum(
                    ((int) DataConverter.convZonedStringToLong(source
                            .getLkCommarea().substring(192, 200), 8)));
            target.getCdemoCt02Info().setCdemoCt02NextPageFlg(
                    source.getLkCommarea().substring(200, 201));
            target.getCdemoCt02Info().setCdemoCt02TrnSelFlg(
                    source.getLkCommarea().substring(201, 202));
            target.getCdemoCt02Info().setCdemoCt02TrnSelected(
                    source.getLkCommarea().substring(202, 218));
        }
    }

    /** 
     * <p>Mapper class to convert data for CICS processing</p>
     * <ul>
     * <li>source class: {@link Cotrn02cCarddemoCommarea}</li>
     * <li>target class: {@link Cotrn02cDfhcommarea}</li>
     * </ul>
     */
    @Mapper(unmappedTargetPolicy = ReportingPolicy.IGNORE)
    public interface Cotrn02cCarddemoCommareaToCotrn02cDfhcommarea {
        Cotrn02cCarddemoCommareaToCotrn02cDfhcommarea INSTANCE = Mappers
                .getMapper(Cotrn02cCarddemoCommareaToCotrn02cDfhcommarea.class);

        Cotrn02cDfhcommarea toTarget(Cotrn02cCarddemoCommarea source);

        Cotrn02cCarddemoCommarea toSource(Cotrn02cDfhcommarea source);

        @AfterMapping
        default void makeTarget(Cotrn02cCarddemoCommarea source,
                @MappingTarget Cotrn02cDfhcommarea target) {
            target.setLkCommarea(source.getCdemoGeneralInfo()
                    .getCdemoFromTranid()
                    + source.getCdemoGeneralInfo().getCdemoFromProgram()
                    + source.getCdemoGeneralInfo().getCdemoToTranid()
                    + source.getCdemoGeneralInfo().getCdemoToProgram()
                    + source.getCdemoGeneralInfo().getCdemoUserId()
                    + source.getCdemoGeneralInfo().getCdemoUserType()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoGeneralInfo().getCdemoPgmContext(), 1)
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCustomerInfo().getCdemoCustId(), 9)
                    + source.getCdemoCustomerInfo().getCdemoCustFname()
                    + source.getCdemoCustomerInfo().getCdemoCustMname()
                    + source.getCdemoCustomerInfo().getCdemoCustLname()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoAccountInfo().getCdemoAcctId(), 11)
                    + source.getCdemoAccountInfo().getCdemoAcctStatus()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCardInfo().getCdemoCardNum(), 16)
                    + source.getCdemoMoreInfo().getCdemoLastMap()
                    + source.getCdemoMoreInfo().getCdemoLastMapset()
                    + source.getCdemoCt02Info().getCdemoCt02TrnidFirst()
                    + source.getCdemoCt02Info().getCdemoCt02TrnidLast()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCt02Info().getCdemoCt02PageNum(), 8)
                    + source.getCdemoCt02Info().getCdemoCt02NextPageFlg()
                    + source.getCdemoCt02Info().getCdemoCt02TrnSelFlg()
                    + source.getCdemoCt02Info().getCdemoCt02TrnSelected());
        }

        @AfterMapping
        default void makeSource(Cotrn02cDfhcommarea source,
                @MappingTarget Cotrn02cCarddemoCommarea target) {
            target.getCdemoGeneralInfo().setCdemoFromTranid(
                    source.getLkCommarea().substring(0, 4));
            target.getCdemoGeneralInfo().setCdemoFromProgram(
                    source.getLkCommarea().substring(4, 12));
            target.getCdemoGeneralInfo().setCdemoToTranid(
                    source.getLkCommarea().substring(12, 16));
            target.getCdemoGeneralInfo().setCdemoToProgram(
                    source.getLkCommarea().substring(16, 24));
            target.getCdemoGeneralInfo().setCdemoUserId(
                    source.getLkCommarea().substring(24, 32));
            target.getCdemoGeneralInfo().setCdemoUserType(
                    source.getLkCommarea().substring(32, 33));
            target.getCdemoGeneralInfo().setCdemoPgmContext(
                    ((int) DataConverter.convZonedStringToLong(source
                            .getLkCommarea().substring(33, 34), 1)));
            target.getCdemoCustomerInfo().setCdemoCustId(
                    ((int) DataConverter.convZonedStringToLong(source
                            .getLkCommarea().substring(34, 43), 9)));
            target.getCdemoCustomerInfo().setCdemoCustFname(
                    source.getLkCommarea().substring(43, 68));
            target.getCdemoCustomerInfo().setCdemoCustMname(
                    source.getLkCommarea().substring(68, 93));
            target.getCdemoCustomerInfo().setCdemoCustLname(
                    source.getLkCommarea().substring(93, 118));
            target.getCdemoAccountInfo().setCdemoAcctId(
                    DataConverter.convZonedStringToLong(source.getLkCommarea()
                            .substring(118, 129), 11));
            target.getCdemoAccountInfo().setCdemoAcctStatus(
                    source.getLkCommarea().substring(129, 130));
            target.getCdemoCardInfo().setCdemoCardNum(
                    DataConverter.convZonedStringToLong(source.getLkCommarea()
                            .substring(130, 146), 16));
            target.getCdemoMoreInfo().setCdemoLastMap(
                    source.getLkCommarea().substring(146, 153));
            target.getCdemoMoreInfo().setCdemoLastMapset(
                    source.getLkCommarea().substring(153, 160));
            target.getCdemoCt02Info().setCdemoCt02TrnidFirst(
                    source.getLkCommarea().substring(160, 176));
            target.getCdemoCt02Info().setCdemoCt02TrnidLast(
                    source.getLkCommarea().substring(176, 192));
            target.getCdemoCt02Info().setCdemoCt02PageNum(
                    ((int) DataConverter.convZonedStringToLong(source
                            .getLkCommarea().substring(192, 200), 8)));
            target.getCdemoCt02Info().setCdemoCt02NextPageFlg(
                    source.getLkCommarea().substring(200, 201));
            target.getCdemoCt02Info().setCdemoCt02TrnSelFlg(
                    source.getLkCommarea().substring(201, 202));
            target.getCdemoCt02Info().setCdemoCt02TrnSelected(
                    source.getLkCommarea().substring(202, 218));
        }
    }

    /** 
     * <p>Mapper class to convert data for CICS processing</p>
     * <ul>
     * <li>source class: {@link Cotrn02cCardXrefRecord}</li>
     * <li>target class: {@link AwsM2CarddemoCardxrefVsamKsdsDto}</li>
     * </ul>
     */
    @Mapper(unmappedTargetPolicy = ReportingPolicy.IGNORE)
    public interface Cotrn02cCardXrefRecordToAwsM2CarddemoCardxrefVsamKsdsDto {
        Cotrn02cCardXrefRecordToAwsM2CarddemoCardxrefVsamKsdsDto INSTANCE = Mappers
                .getMapper(Cotrn02cCardXrefRecordToAwsM2CarddemoCardxrefVsamKsdsDto.class);

        @Mapping(source = "xrefCardNum", target = "xrefCardNum")
        @Mapping(source = "xrefCustId", target = "xrefCustId")
        @Mapping(source = "xrefAcctId", target = "xrefAcctId")
        @Mapping(source = "OFFILLER1", target = "filler")
        AwsM2CarddemoCardxrefVsamKsdsDto toTarget(Cotrn02cCardXrefRecord source);

        @Mapping(source = "xrefCardNum", target = "xrefCardNum")
        @Mapping(source = "xrefCustId", target = "xrefCustId")
        @Mapping(source = "xrefAcctId", target = "xrefAcctId")
        @Mapping(source = "filler", target = "OFFILLER1")
        Cotrn02cCardXrefRecord toSource(AwsM2CarddemoCardxrefVsamKsdsDto source);
    }

    /** 
     * <p>Mapper class to convert data for CICS processing</p>
     * <ul>
     * <li>source class: {@link Cotrn02cTranRecord}</li>
     * <li>target class: {@link AwsM2CarddemoTransactVsamKsdsDto}</li>
     * </ul>
     */
    @Mapper(unmappedTargetPolicy = ReportingPolicy.IGNORE)
    public interface Cotrn02cTranRecordToAwsM2CarddemoTransactVsamKsdsDto {
        Cotrn02cTranRecordToAwsM2CarddemoTransactVsamKsdsDto INSTANCE = Mappers
                .getMapper(Cotrn02cTranRecordToAwsM2CarddemoTransactVsamKsdsDto.class);

        @Mapping(source = "tranId", target = "tranId")
        @Mapping(source = "tranTypeCd", target = "tranTypeCd")
        @Mapping(source = "tranCatCd", target = "tranCatCd")
        @Mapping(source = "tranSource", target = "tranSource")
        @Mapping(source = "tranDesc", target = "tranDesc")
        @Mapping(source = "tranAmt", target = "tranAmt")
        @Mapping(source = "tranMerchantId", target = "tranMerchantId")
        @Mapping(source = "tranMerchantName", target = "tranMerchantName")
        @Mapping(source = "tranMerchantCity", target = "tranMerchantCity")
        @Mapping(source = "tranMerchantZip", target = "tranMerchantZip")
        @Mapping(source = "tranCardNum", target = "tranCardNum")
        @Mapping(source = "tranOrigTs", target = "tranOrigTs")
        @Mapping(source = "tranProcTs", target = "tranProcTs")
        @Mapping(source = "OFFILLER1", target = "filler")
        AwsM2CarddemoTransactVsamKsdsDto toTarget(Cotrn02cTranRecord source);

        @Mapping(source = "tranId", target = "tranId")
        @Mapping(source = "tranTypeCd", target = "tranTypeCd")
        @Mapping(source = "tranCatCd", target = "tranCatCd")
        @Mapping(source = "tranSource", target = "tranSource")
        @Mapping(source = "tranDesc", target = "tranDesc")
        @Mapping(source = "tranAmt", target = "tranAmt")
        @Mapping(source = "tranMerchantId", target = "tranMerchantId")
        @Mapping(source = "tranMerchantName", target = "tranMerchantName")
        @Mapping(source = "tranMerchantCity", target = "tranMerchantCity")
        @Mapping(source = "tranMerchantZip", target = "tranMerchantZip")
        @Mapping(source = "tranCardNum", target = "tranCardNum")
        @Mapping(source = "tranOrigTs", target = "tranOrigTs")
        @Mapping(source = "tranProcTs", target = "tranProcTs")
        @Mapping(source = "filler", target = "OFFILLER1")
        Cotrn02cTranRecord toSource(AwsM2CarddemoTransactVsamKsdsDto source);
    }

    /** 
     * <p>Mapper class to convert data for CICS processing</p>
     * <ul>
     * <li>source class: {@link Cotrn02cCarddemoCommarea}</li>
     * <li>target class: {@link Comen01cDfhcommarea}</li>
     * </ul>
     */
    @Mapper(unmappedTargetPolicy = ReportingPolicy.IGNORE)
    public interface Cotrn02cCarddemoCommareaToComen01cDfhcommarea {
        Cotrn02cCarddemoCommareaToComen01cDfhcommarea INSTANCE = Mappers
                .getMapper(Cotrn02cCarddemoCommareaToComen01cDfhcommarea.class);

        Comen01cDfhcommarea toTarget(Cotrn02cCarddemoCommarea source);

        Cotrn02cCarddemoCommarea toSource(Comen01cDfhcommarea source);

        @AfterMapping
        default void makeTarget(Cotrn02cCarddemoCommarea source,
                @MappingTarget Comen01cDfhcommarea target) {
            target.setLkCommarea(source.getCdemoGeneralInfo()
                    .getCdemoFromTranid()
                    + source.getCdemoGeneralInfo().getCdemoFromProgram()
                    + source.getCdemoGeneralInfo().getCdemoToTranid()
                    + source.getCdemoGeneralInfo().getCdemoToProgram()
                    + source.getCdemoGeneralInfo().getCdemoUserId()
                    + source.getCdemoGeneralInfo().getCdemoUserType()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoGeneralInfo().getCdemoPgmContext(), 1)
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCustomerInfo().getCdemoCustId(), 9)
                    + source.getCdemoCustomerInfo().getCdemoCustFname()
                    + source.getCdemoCustomerInfo().getCdemoCustMname()
                    + source.getCdemoCustomerInfo().getCdemoCustLname()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoAccountInfo().getCdemoAcctId(), 11)
                    + source.getCdemoAccountInfo().getCdemoAcctStatus()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCardInfo().getCdemoCardNum(), 16)
                    + source.getCdemoMoreInfo().getCdemoLastMap()
                    + source.getCdemoMoreInfo().getCdemoLastMapset()
                    + source.getCdemoCt02Info().getCdemoCt02TrnidFirst()
                    + source.getCdemoCt02Info().getCdemoCt02TrnidLast()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCt02Info().getCdemoCt02PageNum(), 8)
                    + source.getCdemoCt02Info().getCdemoCt02NextPageFlg()
                    + source.getCdemoCt02Info().getCdemoCt02TrnSelFlg()
                    + source.getCdemoCt02Info().getCdemoCt02TrnSelected());
        }

        @AfterMapping
        default void makeSource(Comen01cDfhcommarea source,
                @MappingTarget Cotrn02cCarddemoCommarea target) {
            target.getCdemoGeneralInfo().setCdemoFromTranid(
                    source.getLkCommarea().substring(0, 4));
            target.getCdemoGeneralInfo().setCdemoFromProgram(
                    source.getLkCommarea().substring(4, 12));
            target.getCdemoGeneralInfo().setCdemoToTranid(
                    source.getLkCommarea().substring(12, 16));
            target.getCdemoGeneralInfo().setCdemoToProgram(
                    source.getLkCommarea().substring(16, 24));
            target.getCdemoGeneralInfo().setCdemoUserId(
                    source.getLkCommarea().substring(24, 32));
            target.getCdemoGeneralInfo().setCdemoUserType(
                    source.getLkCommarea().substring(32, 33));
            target.getCdemoGeneralInfo().setCdemoPgmContext(
                    ((int) DataConverter.convZonedStringToLong(source
                            .getLkCommarea().substring(33, 34), 1)));
            target.getCdemoCustomerInfo().setCdemoCustId(
                    ((int) DataConverter.convZonedStringToLong(source
                            .getLkCommarea().substring(34, 43), 9)));
            target.getCdemoCustomerInfo().setCdemoCustFname(
                    source.getLkCommarea().substring(43, 68));
            target.getCdemoCustomerInfo().setCdemoCustMname(
                    source.getLkCommarea().substring(68, 93));
            target.getCdemoCustomerInfo().setCdemoCustLname(
                    source.getLkCommarea().substring(93, 118));
            target.getCdemoAccountInfo().setCdemoAcctId(
                    DataConverter.convZonedStringToLong(source.getLkCommarea()
                            .substring(118, 129), 11));
            target.getCdemoAccountInfo().setCdemoAcctStatus(
                    source.getLkCommarea().substring(129, 130));
            target.getCdemoCardInfo().setCdemoCardNum(
                    DataConverter.convZonedStringToLong(source.getLkCommarea()
                            .substring(130, 146), 16));
            target.getCdemoMoreInfo().setCdemoLastMap(
                    source.getLkCommarea().substring(146, 153));
            target.getCdemoMoreInfo().setCdemoLastMapset(
                    source.getLkCommarea().substring(153, 160));
            target.getCdemoCt02Info().setCdemoCt02TrnidFirst(
                    source.getLkCommarea().substring(160, 176));
            target.getCdemoCt02Info().setCdemoCt02TrnidLast(
                    source.getLkCommarea().substring(176, 192));
            target.getCdemoCt02Info().setCdemoCt02PageNum(
                    ((int) DataConverter.convZonedStringToLong(source
                            .getLkCommarea().substring(192, 200), 8)));
            target.getCdemoCt02Info().setCdemoCt02NextPageFlg(
                    source.getLkCommarea().substring(200, 201));
            target.getCdemoCt02Info().setCdemoCt02TrnSelFlg(
                    source.getLkCommarea().substring(201, 202));
            target.getCdemoCt02Info().setCdemoCt02TrnSelected(
                    source.getLkCommarea().substring(202, 218));
        }
    }
}
