package aws.carddemo.mapper;

import com.tmax.openframe.DataConverter;
import org.apache.commons.lang3.StringUtils;
import org.mapstruct.*;
import org.mapstruct.factory.*;
import aws.carddemo.variable.group.Cousr00cCarddemoCommarea;
import aws.carddemo.variable.group.Cosgn00cDfhcommarea;
import aws.carddemo.variable.group.Coadm01cDfhcommarea;
import aws.carddemo.variable.group.Cousr00cDfhcommarea;
import aws.carddemo.variable.group.Cousr03cDfhcommarea;
import aws.carddemo.variable.group.Cousr00cSecUserData;
import aws.carddemo.dto.AwsM2CarddemoUsrsecVsamKsdsDto;
import aws.carddemo.variable.group.Cousr02cDfhcommarea;
import lombok.*;
import java.math.*;
import java.util.*;

/** 
 * <p>This source code was generated by T-Up OpenFrame COBOL to Java migrator</p>
 * <p>  Generation date : 2024/05/02 05:57:47 UTC</p>
 * <hr>
 * <p>Mapper class for converting data between different classes</p>
 */
public interface Cousr00cMapperInterface {
    /** 
     * <p>Mapper class to convert data for CICS processing</p>
     * <ul>
     * <li>source class: {@link Cousr00cCarddemoCommarea}</li>
     * <li>target class: {@link Cosgn00cDfhcommarea}</li>
     * </ul>
     */
    @Mapper(unmappedTargetPolicy = ReportingPolicy.IGNORE)
    public interface Cousr00cCarddemoCommareaToCosgn00cDfhcommarea {
        Cousr00cCarddemoCommareaToCosgn00cDfhcommarea INSTANCE = Mappers
                .getMapper(Cousr00cCarddemoCommareaToCosgn00cDfhcommarea.class);

        Cosgn00cDfhcommarea toTarget(Cousr00cCarddemoCommarea source);

        Cousr00cCarddemoCommarea toSource(Cosgn00cDfhcommarea source);

        @AfterMapping
        default void makeTarget(Cousr00cCarddemoCommarea source,
                @MappingTarget Cosgn00cDfhcommarea target) {
            target.setLkCommarea(source.getCdemoGeneralInfo()
                    .getCdemoFromTranid()
                    + source.getCdemoGeneralInfo().getCdemoFromProgram()
                    + source.getCdemoGeneralInfo().getCdemoToTranid()
                    + source.getCdemoGeneralInfo().getCdemoToProgram()
                    + source.getCdemoGeneralInfo().getCdemoUserId()
                    + source.getCdemoGeneralInfo().getCdemoUserType()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoGeneralInfo().getCdemoPgmContext(), 1)
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCustomerInfo().getCdemoCustId(), 9)
                    + source.getCdemoCustomerInfo().getCdemoCustFname()
                    + source.getCdemoCustomerInfo().getCdemoCustMname()
                    + source.getCdemoCustomerInfo().getCdemoCustLname()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoAccountInfo().getCdemoAcctId(), 11)
                    + source.getCdemoAccountInfo().getCdemoAcctStatus()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCardInfo().getCdemoCardNum(), 16)
                    + source.getCdemoMoreInfo().getCdemoLastMap()
                    + source.getCdemoMoreInfo().getCdemoLastMapset()
                    + source.getCdemoCu00Info().getCdemoCu00UsridFirst()
                    + source.getCdemoCu00Info().getCdemoCu00UsridLast()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCu00Info().getCdemoCu00PageNum(), 8)
                    + source.getCdemoCu00Info().getCdemoCu00NextPageFlg()
                    + source.getCdemoCu00Info().getCdemoCu00UsrSelFlg()
                    + source.getCdemoCu00Info().getCdemoCu00UsrSelected());
        }

        @AfterMapping
        default void makeSource(Cosgn00cDfhcommarea source,
                @MappingTarget Cousr00cCarddemoCommarea target) {
            target.getCdemoGeneralInfo().setCdemoFromTranid(
                    source.getLkCommarea().substring(0, 4));
            target.getCdemoGeneralInfo().setCdemoFromProgram(
                    source.getLkCommarea().substring(4, 12));
            target.getCdemoGeneralInfo().setCdemoToTranid(
                    source.getLkCommarea().substring(12, 16));
            target.getCdemoGeneralInfo().setCdemoToProgram(
                    source.getLkCommarea().substring(16, 24));
            target.getCdemoGeneralInfo().setCdemoUserId(
                    source.getLkCommarea().substring(24, 32));
            target.getCdemoGeneralInfo().setCdemoUserType(
                    source.getLkCommarea().substring(32, 33));
            target.getCdemoGeneralInfo().setCdemoPgmContext(
                    ((int) DataConverter.convZonedStringToLong(source
                            .getLkCommarea().substring(33, 34), 1)));
            target.getCdemoCustomerInfo().setCdemoCustId(
                    ((int) DataConverter.convZonedStringToLong(source
                            .getLkCommarea().substring(34, 43), 9)));
            target.getCdemoCustomerInfo().setCdemoCustFname(
                    source.getLkCommarea().substring(43, 68));
            target.getCdemoCustomerInfo().setCdemoCustMname(
                    source.getLkCommarea().substring(68, 93));
            target.getCdemoCustomerInfo().setCdemoCustLname(
                    source.getLkCommarea().substring(93, 118));
            target.getCdemoAccountInfo().setCdemoAcctId(
                    DataConverter.convZonedStringToLong(source.getLkCommarea()
                            .substring(118, 129), 11));
            target.getCdemoAccountInfo().setCdemoAcctStatus(
                    source.getLkCommarea().substring(129, 130));
            target.getCdemoCardInfo().setCdemoCardNum(
                    DataConverter.convZonedStringToLong(source.getLkCommarea()
                            .substring(130, 146), 16));
            target.getCdemoMoreInfo().setCdemoLastMap(
                    source.getLkCommarea().substring(146, 153));
            target.getCdemoMoreInfo().setCdemoLastMapset(
                    source.getLkCommarea().substring(153, 160));
            target.getCdemoCu00Info().setCdemoCu00UsridFirst(
                    source.getLkCommarea().substring(160, 168));
            target.getCdemoCu00Info().setCdemoCu00UsridLast(
                    source.getLkCommarea().substring(168, 176));
            target.getCdemoCu00Info().setCdemoCu00PageNum(
                    ((int) DataConverter.convZonedStringToLong(source
                            .getLkCommarea().substring(176, 184), 8)));
            target.getCdemoCu00Info().setCdemoCu00NextPageFlg(
                    source.getLkCommarea().substring(184, 185));
            target.getCdemoCu00Info().setCdemoCu00UsrSelFlg(
                    source.getLkCommarea().substring(185, 186));
            target.getCdemoCu00Info().setCdemoCu00UsrSelected(
                    source.getLkCommarea().substring(186, 194));
        }
    }

    /** 
     * <p>Mapper class to convert data for CICS processing</p>
     * <ul>
     * <li>source class: {@link Cousr00cCarddemoCommarea}</li>
     * <li>target class: {@link Coadm01cDfhcommarea}</li>
     * </ul>
     */
    @Mapper(unmappedTargetPolicy = ReportingPolicy.IGNORE)
    public interface Cousr00cCarddemoCommareaToCoadm01cDfhcommarea {
        Cousr00cCarddemoCommareaToCoadm01cDfhcommarea INSTANCE = Mappers
                .getMapper(Cousr00cCarddemoCommareaToCoadm01cDfhcommarea.class);

        Coadm01cDfhcommarea toTarget(Cousr00cCarddemoCommarea source);

        Cousr00cCarddemoCommarea toSource(Coadm01cDfhcommarea source);

        @AfterMapping
        default void makeTarget(Cousr00cCarddemoCommarea source,
                @MappingTarget Coadm01cDfhcommarea target) {
            target.setLkCommarea(source.getCdemoGeneralInfo()
                    .getCdemoFromTranid()
                    + source.getCdemoGeneralInfo().getCdemoFromProgram()
                    + source.getCdemoGeneralInfo().getCdemoToTranid()
                    + source.getCdemoGeneralInfo().getCdemoToProgram()
                    + source.getCdemoGeneralInfo().getCdemoUserId()
                    + source.getCdemoGeneralInfo().getCdemoUserType()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoGeneralInfo().getCdemoPgmContext(), 1)
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCustomerInfo().getCdemoCustId(), 9)
                    + source.getCdemoCustomerInfo().getCdemoCustFname()
                    + source.getCdemoCustomerInfo().getCdemoCustMname()
                    + source.getCdemoCustomerInfo().getCdemoCustLname()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoAccountInfo().getCdemoAcctId(), 11)
                    + source.getCdemoAccountInfo().getCdemoAcctStatus()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCardInfo().getCdemoCardNum(), 16)
                    + source.getCdemoMoreInfo().getCdemoLastMap()
                    + source.getCdemoMoreInfo().getCdemoLastMapset()
                    + source.getCdemoCu00Info().getCdemoCu00UsridFirst()
                    + source.getCdemoCu00Info().getCdemoCu00UsridLast()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCu00Info().getCdemoCu00PageNum(), 8)
                    + source.getCdemoCu00Info().getCdemoCu00NextPageFlg()
                    + source.getCdemoCu00Info().getCdemoCu00UsrSelFlg()
                    + source.getCdemoCu00Info().getCdemoCu00UsrSelected());
        }

        @AfterMapping
        default void makeSource(Coadm01cDfhcommarea source,
                @MappingTarget Cousr00cCarddemoCommarea target) {
            target.getCdemoGeneralInfo().setCdemoFromTranid(
                    source.getLkCommarea().substring(0, 4));
            target.getCdemoGeneralInfo().setCdemoFromProgram(
                    source.getLkCommarea().substring(4, 12));
            target.getCdemoGeneralInfo().setCdemoToTranid(
                    source.getLkCommarea().substring(12, 16));
            target.getCdemoGeneralInfo().setCdemoToProgram(
                    source.getLkCommarea().substring(16, 24));
            target.getCdemoGeneralInfo().setCdemoUserId(
                    source.getLkCommarea().substring(24, 32));
            target.getCdemoGeneralInfo().setCdemoUserType(
                    source.getLkCommarea().substring(32, 33));
            target.getCdemoGeneralInfo().setCdemoPgmContext(
                    ((int) DataConverter.convZonedStringToLong(source
                            .getLkCommarea().substring(33, 34), 1)));
            target.getCdemoCustomerInfo().setCdemoCustId(
                    ((int) DataConverter.convZonedStringToLong(source
                            .getLkCommarea().substring(34, 43), 9)));
            target.getCdemoCustomerInfo().setCdemoCustFname(
                    source.getLkCommarea().substring(43, 68));
            target.getCdemoCustomerInfo().setCdemoCustMname(
                    source.getLkCommarea().substring(68, 93));
            target.getCdemoCustomerInfo().setCdemoCustLname(
                    source.getLkCommarea().substring(93, 118));
            target.getCdemoAccountInfo().setCdemoAcctId(
                    DataConverter.convZonedStringToLong(source.getLkCommarea()
                            .substring(118, 129), 11));
            target.getCdemoAccountInfo().setCdemoAcctStatus(
                    source.getLkCommarea().substring(129, 130));
            target.getCdemoCardInfo().setCdemoCardNum(
                    DataConverter.convZonedStringToLong(source.getLkCommarea()
                            .substring(130, 146), 16));
            target.getCdemoMoreInfo().setCdemoLastMap(
                    source.getLkCommarea().substring(146, 153));
            target.getCdemoMoreInfo().setCdemoLastMapset(
                    source.getLkCommarea().substring(153, 160));
            target.getCdemoCu00Info().setCdemoCu00UsridFirst(
                    source.getLkCommarea().substring(160, 168));
            target.getCdemoCu00Info().setCdemoCu00UsridLast(
                    source.getLkCommarea().substring(168, 176));
            target.getCdemoCu00Info().setCdemoCu00PageNum(
                    ((int) DataConverter.convZonedStringToLong(source
                            .getLkCommarea().substring(176, 184), 8)));
            target.getCdemoCu00Info().setCdemoCu00NextPageFlg(
                    source.getLkCommarea().substring(184, 185));
            target.getCdemoCu00Info().setCdemoCu00UsrSelFlg(
                    source.getLkCommarea().substring(185, 186));
            target.getCdemoCu00Info().setCdemoCu00UsrSelected(
                    source.getLkCommarea().substring(186, 194));
        }
    }

    /** 
     * <p>Mapper class to convert data for CICS processing</p>
     * <ul>
     * <li>source class: {@link Cousr00cCarddemoCommarea}</li>
     * <li>target class: {@link Cousr00cDfhcommarea}</li>
     * </ul>
     */
    @Mapper(unmappedTargetPolicy = ReportingPolicy.IGNORE)
    public interface Cousr00cCarddemoCommareaToCousr00cDfhcommarea {
        Cousr00cCarddemoCommareaToCousr00cDfhcommarea INSTANCE = Mappers
                .getMapper(Cousr00cCarddemoCommareaToCousr00cDfhcommarea.class);

        Cousr00cDfhcommarea toTarget(Cousr00cCarddemoCommarea source);

        Cousr00cCarddemoCommarea toSource(Cousr00cDfhcommarea source);

        @AfterMapping
        default void makeTarget(Cousr00cCarddemoCommarea source,
                @MappingTarget Cousr00cDfhcommarea target) {
            target.setLkCommarea(source.getCdemoGeneralInfo()
                    .getCdemoFromTranid()
                    + source.getCdemoGeneralInfo().getCdemoFromProgram()
                    + source.getCdemoGeneralInfo().getCdemoToTranid()
                    + source.getCdemoGeneralInfo().getCdemoToProgram()
                    + source.getCdemoGeneralInfo().getCdemoUserId()
                    + source.getCdemoGeneralInfo().getCdemoUserType()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoGeneralInfo().getCdemoPgmContext(), 1)
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCustomerInfo().getCdemoCustId(), 9)
                    + source.getCdemoCustomerInfo().getCdemoCustFname()
                    + source.getCdemoCustomerInfo().getCdemoCustMname()
                    + source.getCdemoCustomerInfo().getCdemoCustLname()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoAccountInfo().getCdemoAcctId(), 11)
                    + source.getCdemoAccountInfo().getCdemoAcctStatus()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCardInfo().getCdemoCardNum(), 16)
                    + source.getCdemoMoreInfo().getCdemoLastMap()
                    + source.getCdemoMoreInfo().getCdemoLastMapset()
                    + source.getCdemoCu00Info().getCdemoCu00UsridFirst()
                    + source.getCdemoCu00Info().getCdemoCu00UsridLast()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCu00Info().getCdemoCu00PageNum(), 8)
                    + source.getCdemoCu00Info().getCdemoCu00NextPageFlg()
                    + source.getCdemoCu00Info().getCdemoCu00UsrSelFlg()
                    + source.getCdemoCu00Info().getCdemoCu00UsrSelected());
        }

        @AfterMapping
        default void makeSource(Cousr00cDfhcommarea source,
                @MappingTarget Cousr00cCarddemoCommarea target) {
            target.getCdemoGeneralInfo().setCdemoFromTranid(
                    source.getLkCommarea().substring(0, 4));
            target.getCdemoGeneralInfo().setCdemoFromProgram(
                    source.getLkCommarea().substring(4, 12));
            target.getCdemoGeneralInfo().setCdemoToTranid(
                    source.getLkCommarea().substring(12, 16));
            target.getCdemoGeneralInfo().setCdemoToProgram(
                    source.getLkCommarea().substring(16, 24));
            target.getCdemoGeneralInfo().setCdemoUserId(
                    source.getLkCommarea().substring(24, 32));
            target.getCdemoGeneralInfo().setCdemoUserType(
                    source.getLkCommarea().substring(32, 33));
            target.getCdemoGeneralInfo().setCdemoPgmContext(
                    ((int) DataConverter.convZonedStringToLong(source
                            .getLkCommarea().substring(33, 34), 1)));
            target.getCdemoCustomerInfo().setCdemoCustId(
                    ((int) DataConverter.convZonedStringToLong(source
                            .getLkCommarea().substring(34, 43), 9)));
            target.getCdemoCustomerInfo().setCdemoCustFname(
                    source.getLkCommarea().substring(43, 68));
            target.getCdemoCustomerInfo().setCdemoCustMname(
                    source.getLkCommarea().substring(68, 93));
            target.getCdemoCustomerInfo().setCdemoCustLname(
                    source.getLkCommarea().substring(93, 118));
            target.getCdemoAccountInfo().setCdemoAcctId(
                    DataConverter.convZonedStringToLong(source.getLkCommarea()
                            .substring(118, 129), 11));
            target.getCdemoAccountInfo().setCdemoAcctStatus(
                    source.getLkCommarea().substring(129, 130));
            target.getCdemoCardInfo().setCdemoCardNum(
                    DataConverter.convZonedStringToLong(source.getLkCommarea()
                            .substring(130, 146), 16));
            target.getCdemoMoreInfo().setCdemoLastMap(
                    source.getLkCommarea().substring(146, 153));
            target.getCdemoMoreInfo().setCdemoLastMapset(
                    source.getLkCommarea().substring(153, 160));
            target.getCdemoCu00Info().setCdemoCu00UsridFirst(
                    source.getLkCommarea().substring(160, 168));
            target.getCdemoCu00Info().setCdemoCu00UsridLast(
                    source.getLkCommarea().substring(168, 176));
            target.getCdemoCu00Info().setCdemoCu00PageNum(
                    ((int) DataConverter.convZonedStringToLong(source
                            .getLkCommarea().substring(176, 184), 8)));
            target.getCdemoCu00Info().setCdemoCu00NextPageFlg(
                    source.getLkCommarea().substring(184, 185));
            target.getCdemoCu00Info().setCdemoCu00UsrSelFlg(
                    source.getLkCommarea().substring(185, 186));
            target.getCdemoCu00Info().setCdemoCu00UsrSelected(
                    source.getLkCommarea().substring(186, 194));
        }
    }

    /** 
     * <p>Mapper class to convert data for CICS processing</p>
     * <ul>
     * <li>source class: {@link Cousr00cCarddemoCommarea}</li>
     * <li>target class: {@link Cousr03cDfhcommarea}</li>
     * </ul>
     */
    @Mapper(unmappedTargetPolicy = ReportingPolicy.IGNORE)
    public interface Cousr00cCarddemoCommareaToCousr03cDfhcommarea {
        Cousr00cCarddemoCommareaToCousr03cDfhcommarea INSTANCE = Mappers
                .getMapper(Cousr00cCarddemoCommareaToCousr03cDfhcommarea.class);

        Cousr03cDfhcommarea toTarget(Cousr00cCarddemoCommarea source);

        Cousr00cCarddemoCommarea toSource(Cousr03cDfhcommarea source);

        @AfterMapping
        default void makeTarget(Cousr00cCarddemoCommarea source,
                @MappingTarget Cousr03cDfhcommarea target) {
            target.setLkCommarea(source.getCdemoGeneralInfo()
                    .getCdemoFromTranid()
                    + source.getCdemoGeneralInfo().getCdemoFromProgram()
                    + source.getCdemoGeneralInfo().getCdemoToTranid()
                    + source.getCdemoGeneralInfo().getCdemoToProgram()
                    + source.getCdemoGeneralInfo().getCdemoUserId()
                    + source.getCdemoGeneralInfo().getCdemoUserType()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoGeneralInfo().getCdemoPgmContext(), 1)
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCustomerInfo().getCdemoCustId(), 9)
                    + source.getCdemoCustomerInfo().getCdemoCustFname()
                    + source.getCdemoCustomerInfo().getCdemoCustMname()
                    + source.getCdemoCustomerInfo().getCdemoCustLname()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoAccountInfo().getCdemoAcctId(), 11)
                    + source.getCdemoAccountInfo().getCdemoAcctStatus()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCardInfo().getCdemoCardNum(), 16)
                    + source.getCdemoMoreInfo().getCdemoLastMap()
                    + source.getCdemoMoreInfo().getCdemoLastMapset()
                    + source.getCdemoCu00Info().getCdemoCu00UsridFirst()
                    + source.getCdemoCu00Info().getCdemoCu00UsridLast()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCu00Info().getCdemoCu00PageNum(), 8)
                    + source.getCdemoCu00Info().getCdemoCu00NextPageFlg()
                    + source.getCdemoCu00Info().getCdemoCu00UsrSelFlg()
                    + source.getCdemoCu00Info().getCdemoCu00UsrSelected());
        }

        @AfterMapping
        default void makeSource(Cousr03cDfhcommarea source,
                @MappingTarget Cousr00cCarddemoCommarea target) {
            target.getCdemoGeneralInfo().setCdemoFromTranid(
                    source.getLkCommarea().substring(0, 4));
            target.getCdemoGeneralInfo().setCdemoFromProgram(
                    source.getLkCommarea().substring(4, 12));
            target.getCdemoGeneralInfo().setCdemoToTranid(
                    source.getLkCommarea().substring(12, 16));
            target.getCdemoGeneralInfo().setCdemoToProgram(
                    source.getLkCommarea().substring(16, 24));
            target.getCdemoGeneralInfo().setCdemoUserId(
                    source.getLkCommarea().substring(24, 32));
            target.getCdemoGeneralInfo().setCdemoUserType(
                    source.getLkCommarea().substring(32, 33));
            target.getCdemoGeneralInfo().setCdemoPgmContext(
                    ((int) DataConverter.convZonedStringToLong(source
                            .getLkCommarea().substring(33, 34), 1)));
            target.getCdemoCustomerInfo().setCdemoCustId(
                    ((int) DataConverter.convZonedStringToLong(source
                            .getLkCommarea().substring(34, 43), 9)));
            target.getCdemoCustomerInfo().setCdemoCustFname(
                    source.getLkCommarea().substring(43, 68));
            target.getCdemoCustomerInfo().setCdemoCustMname(
                    source.getLkCommarea().substring(68, 93));
            target.getCdemoCustomerInfo().setCdemoCustLname(
                    source.getLkCommarea().substring(93, 118));
            target.getCdemoAccountInfo().setCdemoAcctId(
                    DataConverter.convZonedStringToLong(source.getLkCommarea()
                            .substring(118, 129), 11));
            target.getCdemoAccountInfo().setCdemoAcctStatus(
                    source.getLkCommarea().substring(129, 130));
            target.getCdemoCardInfo().setCdemoCardNum(
                    DataConverter.convZonedStringToLong(source.getLkCommarea()
                            .substring(130, 146), 16));
            target.getCdemoMoreInfo().setCdemoLastMap(
                    source.getLkCommarea().substring(146, 153));
            target.getCdemoMoreInfo().setCdemoLastMapset(
                    source.getLkCommarea().substring(153, 160));
            target.getCdemoCu00Info().setCdemoCu00UsridFirst(
                    source.getLkCommarea().substring(160, 168));
            target.getCdemoCu00Info().setCdemoCu00UsridLast(
                    source.getLkCommarea().substring(168, 176));
            target.getCdemoCu00Info().setCdemoCu00PageNum(
                    ((int) DataConverter.convZonedStringToLong(source
                            .getLkCommarea().substring(176, 184), 8)));
            target.getCdemoCu00Info().setCdemoCu00NextPageFlg(
                    source.getLkCommarea().substring(184, 185));
            target.getCdemoCu00Info().setCdemoCu00UsrSelFlg(
                    source.getLkCommarea().substring(185, 186));
            target.getCdemoCu00Info().setCdemoCu00UsrSelected(
                    source.getLkCommarea().substring(186, 194));
        }
    }

    /** 
     * <p>Mapper class to convert data for CICS processing</p>
     * <ul>
     * <li>source class: {@link Cousr00cSecUserData}</li>
     * <li>target class: {@link AwsM2CarddemoUsrsecVsamKsdsDto}</li>
     * </ul>
     */
    @Mapper(unmappedTargetPolicy = ReportingPolicy.IGNORE)
    public interface Cousr00cSecUserDataToAwsM2CarddemoUsrsecVsamKsdsDto {
        Cousr00cSecUserDataToAwsM2CarddemoUsrsecVsamKsdsDto INSTANCE = Mappers
                .getMapper(Cousr00cSecUserDataToAwsM2CarddemoUsrsecVsamKsdsDto.class);

        @Mapping(source = "secUsrId", target = "secUsrId")
        @Mapping(source = "secUsrFname", target = "secUsrFname")
        @Mapping(source = "secUsrLname", target = "secUsrLname")
        @Mapping(source = "secUsrPwd", target = "secUsrPwd")
        @Mapping(source = "secUsrType", target = "secUsrType")
        @Mapping(source = "secUsrFiller", target = "secUsrFiller")
        AwsM2CarddemoUsrsecVsamKsdsDto toTarget(Cousr00cSecUserData source);

        @Mapping(source = "secUsrId", target = "secUsrId")
        @Mapping(source = "secUsrFname", target = "secUsrFname")
        @Mapping(source = "secUsrLname", target = "secUsrLname")
        @Mapping(source = "secUsrPwd", target = "secUsrPwd")
        @Mapping(source = "secUsrType", target = "secUsrType")
        @Mapping(source = "secUsrFiller", target = "secUsrFiller")
        Cousr00cSecUserData toSource(AwsM2CarddemoUsrsecVsamKsdsDto source);
    }

    /** 
     * <p>Mapper class to convert data for CICS processing</p>
     * <ul>
     * <li>source class: {@link Cousr00cCarddemoCommarea}</li>
     * <li>target class: {@link Cousr02cDfhcommarea}</li>
     * </ul>
     */
    @Mapper(unmappedTargetPolicy = ReportingPolicy.IGNORE)
    public interface Cousr00cCarddemoCommareaToCousr02cDfhcommarea {
        Cousr00cCarddemoCommareaToCousr02cDfhcommarea INSTANCE = Mappers
                .getMapper(Cousr00cCarddemoCommareaToCousr02cDfhcommarea.class);

        Cousr02cDfhcommarea toTarget(Cousr00cCarddemoCommarea source);

        Cousr00cCarddemoCommarea toSource(Cousr02cDfhcommarea source);

        @AfterMapping
        default void makeTarget(Cousr00cCarddemoCommarea source,
                @MappingTarget Cousr02cDfhcommarea target) {
            target.setLkCommarea(source.getCdemoGeneralInfo()
                    .getCdemoFromTranid()
                    + source.getCdemoGeneralInfo().getCdemoFromProgram()
                    + source.getCdemoGeneralInfo().getCdemoToTranid()
                    + source.getCdemoGeneralInfo().getCdemoToProgram()
                    + source.getCdemoGeneralInfo().getCdemoUserId()
                    + source.getCdemoGeneralInfo().getCdemoUserType()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoGeneralInfo().getCdemoPgmContext(), 1)
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCustomerInfo().getCdemoCustId(), 9)
                    + source.getCdemoCustomerInfo().getCdemoCustFname()
                    + source.getCdemoCustomerInfo().getCdemoCustMname()
                    + source.getCdemoCustomerInfo().getCdemoCustLname()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoAccountInfo().getCdemoAcctId(), 11)
                    + source.getCdemoAccountInfo().getCdemoAcctStatus()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCardInfo().getCdemoCardNum(), 16)
                    + source.getCdemoMoreInfo().getCdemoLastMap()
                    + source.getCdemoMoreInfo().getCdemoLastMapset()
                    + source.getCdemoCu00Info().getCdemoCu00UsridFirst()
                    + source.getCdemoCu00Info().getCdemoCu00UsridLast()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCu00Info().getCdemoCu00PageNum(), 8)
                    + source.getCdemoCu00Info().getCdemoCu00NextPageFlg()
                    + source.getCdemoCu00Info().getCdemoCu00UsrSelFlg()
                    + source.getCdemoCu00Info().getCdemoCu00UsrSelected());
        }

        @AfterMapping
        default void makeSource(Cousr02cDfhcommarea source,
                @MappingTarget Cousr00cCarddemoCommarea target) {
            target.getCdemoGeneralInfo().setCdemoFromTranid(
                    source.getLkCommarea().substring(0, 4));
            target.getCdemoGeneralInfo().setCdemoFromProgram(
                    source.getLkCommarea().substring(4, 12));
            target.getCdemoGeneralInfo().setCdemoToTranid(
                    source.getLkCommarea().substring(12, 16));
            target.getCdemoGeneralInfo().setCdemoToProgram(
                    source.getLkCommarea().substring(16, 24));
            target.getCdemoGeneralInfo().setCdemoUserId(
                    source.getLkCommarea().substring(24, 32));
            target.getCdemoGeneralInfo().setCdemoUserType(
                    source.getLkCommarea().substring(32, 33));
            target.getCdemoGeneralInfo().setCdemoPgmContext(
                    ((int) DataConverter.convZonedStringToLong(source
                            .getLkCommarea().substring(33, 34), 1)));
            target.getCdemoCustomerInfo().setCdemoCustId(
                    ((int) DataConverter.convZonedStringToLong(source
                            .getLkCommarea().substring(34, 43), 9)));
            target.getCdemoCustomerInfo().setCdemoCustFname(
                    source.getLkCommarea().substring(43, 68));
            target.getCdemoCustomerInfo().setCdemoCustMname(
                    source.getLkCommarea().substring(68, 93));
            target.getCdemoCustomerInfo().setCdemoCustLname(
                    source.getLkCommarea().substring(93, 118));
            target.getCdemoAccountInfo().setCdemoAcctId(
                    DataConverter.convZonedStringToLong(source.getLkCommarea()
                            .substring(118, 129), 11));
            target.getCdemoAccountInfo().setCdemoAcctStatus(
                    source.getLkCommarea().substring(129, 130));
            target.getCdemoCardInfo().setCdemoCardNum(
                    DataConverter.convZonedStringToLong(source.getLkCommarea()
                            .substring(130, 146), 16));
            target.getCdemoMoreInfo().setCdemoLastMap(
                    source.getLkCommarea().substring(146, 153));
            target.getCdemoMoreInfo().setCdemoLastMapset(
                    source.getLkCommarea().substring(153, 160));
            target.getCdemoCu00Info().setCdemoCu00UsridFirst(
                    source.getLkCommarea().substring(160, 168));
            target.getCdemoCu00Info().setCdemoCu00UsridLast(
                    source.getLkCommarea().substring(168, 176));
            target.getCdemoCu00Info().setCdemoCu00PageNum(
                    ((int) DataConverter.convZonedStringToLong(source
                            .getLkCommarea().substring(176, 184), 8)));
            target.getCdemoCu00Info().setCdemoCu00NextPageFlg(
                    source.getLkCommarea().substring(184, 185));
            target.getCdemoCu00Info().setCdemoCu00UsrSelFlg(
                    source.getLkCommarea().substring(185, 186));
            target.getCdemoCu00Info().setCdemoCu00UsrSelected(
                    source.getLkCommarea().substring(186, 194));
        }
    }
}
