package aws.carddemo.file;

import aws.carddemo.dao.*;
import aws.carddemo.dto.*;
import aws.carddemo.mapper.*;
import aws.carddemo.variable.group.Cbact04cFdXreffileRec;
import com.tmax.openframe.runtime.context.OpenFrameContext;
import com.tmax.openframe.runtime.file.FileStatus;
import com.tmax.openframe.runtime.file.KeyOperationType;
import com.tmax.openframe.runtime.file.RecordCommitter;
import java.math.*;
import java.util.*;
import java.util.function.Function;
import lombok.*;
import org.apache.ibatis.cursor.Cursor;
import org.apache.ibatis.executor.BatchResult;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

/** 
 * <p>This source code was generated by T-Up OpenFrame COBOL to Java migrator</p>
 * <p>  Generation date : 2024/05/02 05:55:55 UTC</p>
 * <hr>
 * <p>Class for processing file I/O operations</p>
 * <ul>
 * <li>target dataset: AwsM2CarddemoCardxrefVsamKsds</li>
 * <li>file operation class: {@link Cbact04cFileOpXrefFile}</li>
 * <li>DAO class: {@link AwsM2CarddemoCardxrefVsamKsdsDao}</li>
 * <li>DTO class: {@link AwsM2CarddemoCardxrefVsamKsdsDto}</li>
 * </ul>
 */
@Repository
public class Cbact04cFdXrefFile extends Cbact04cFileOpXrefFile {
    @Autowired
    private AwsM2CarddemoCardxrefVsamKsdsDao dao;
    @Autowired
    private RecordCommitter<AwsM2CarddemoCardxrefVsamKsdsDto> committer;

    public void open(OpenFrameContext context) {
        setIterator(context, dao.readAllAsc().iterator());
        setFileStatus(context, FileStatus.NORMAL);
        context.initFileWriteBuffer("Cbact04c", "XrefFile");
        committer.setThreshold(5000);
    }

    public void start(OpenFrameContext context, String key,
            KeyOperationType type) {
        Cbact04cFdXreffileRec startPoint = new Cbact04cFdXreffileRec();
        startPoint.setFdXrefCardNum(key);
        AwsM2CarddemoCardxrefVsamKsdsDto dto = Cbact04cMapperInterface.Cbact04cFdXreffileRecKeyToAwsM2CarddemoCardxrefVsamKsdsDto.INSTANCE
                .toTarget(startPoint);
        startDto(context, dto, type, dao::readGeDto, dao::readGtDto);
    }

    public void startAix(OpenFrameContext context, Long key,
            KeyOperationType type) {
        Cbact04cFdXreffileRec startPoint = new Cbact04cFdXreffileRec();
        startPoint.setFdXrefAcctId(key);
        AwsM2CarddemoCardxrefVsamKsdsDto dto = Cbact04cMapperInterface.Cbact04cFdXreffileRecAix10KeyToAwsM2CarddemoCardxrefVsamKsdsDto.INSTANCE
                .toTarget(startPoint);
        startDto(context, dto, type, dao::readGeDtoAix10, dao::readGtDtoAix10);
    }

    private void startDto(
            OpenFrameContext context,
            AwsM2CarddemoCardxrefVsamKsdsDto dto,
            KeyOperationType type,
            Function<AwsM2CarddemoCardxrefVsamKsdsDto, Cursor<AwsM2CarddemoCardxrefVsamKsdsDto>> startGeDtoMethod,
            Function<AwsM2CarddemoCardxrefVsamKsdsDto, Cursor<AwsM2CarddemoCardxrefVsamKsdsDto>> startGtDtoMethod) {
        switch (type) {
        case EQ:
        case GTEQ: {
            setIterator(context, startGeDtoMethod.apply(dto).iterator());
            break;
        }
        case GT: {
            setIterator(context, startGtDtoMethod.apply(dto).iterator());
            break;
        }
        default: {
            throw new RuntimeException(
                    "not supported operation for start method");
        }
        }
        if (!getIterator(context).hasNext()) {
            setFileStatus(context, FileStatus.INVALID_KEY_READ);
        } else {
            setFileStatus(context, FileStatus.NORMAL);
        }
    }

    public Cbact04cFdXreffileRec readNextRecord(OpenFrameContext context) {
        Iterator<AwsM2CarddemoCardxrefVsamKsdsDto> iterator = getIterator(context);
        if (iterator.hasNext()) {
            AwsM2CarddemoCardxrefVsamKsdsDto nextRecord = iterator.next();
            if (nextRecord == null) {
                setFileStatus(context, FileStatus.AT_END_CONDITION_SEQ_READ);
                return null;
            }
            setFileStatus(context, FileStatus.NORMAL);
            return Cbact04cMapperInterface.Cbact04cFdXreffileRecToAwsM2CarddemoCardxrefVsamKsdsDto.INSTANCE
                    .toSource(nextRecord);
        } else {
            setFileStatus(context, FileStatus.AT_END_CONDITION_SEQ_READ);
            return null;
        }
    }

    public Cbact04cFdXreffileRec readKey(OpenFrameContext context, String key) {
        commit(context);
        Cbact04cFdXreffileRec readKeyPoint = new Cbact04cFdXreffileRec();
        readKeyPoint.setFdXrefCardNum(key);
        AwsM2CarddemoCardxrefVsamKsdsDto dto = Cbact04cMapperInterface.Cbact04cFdXreffileRecKeyToAwsM2CarddemoCardxrefVsamKsdsDto.INSTANCE
                .toTarget(readKeyPoint);
        return readDto(context, dto, dao::readEqDto);
    }

    public Cbact04cFdXreffileRec readAixKey(OpenFrameContext context, Long key) {
        commit(context);
        Cbact04cFdXreffileRec readKeyPoint = new Cbact04cFdXreffileRec();
        readKeyPoint.setFdXrefAcctId(key);
        AwsM2CarddemoCardxrefVsamKsdsDto dto = Cbact04cMapperInterface.Cbact04cFdXreffileRecAix10KeyToAwsM2CarddemoCardxrefVsamKsdsDto.INSTANCE
                .toTarget(readKeyPoint);
        return readDto(context, dto, dao::readEqDtoAix10);
    }

    private Cbact04cFdXreffileRec readDto(
            OpenFrameContext context,
            AwsM2CarddemoCardxrefVsamKsdsDto dto,
            Function<AwsM2CarddemoCardxrefVsamKsdsDto, Cursor<AwsM2CarddemoCardxrefVsamKsdsDto>> readDtoMethod) {
        Iterator<AwsM2CarddemoCardxrefVsamKsdsDto> iterator = readDtoMethod
                .apply(dto).iterator();
        setIterator(context, iterator);
        if (iterator.hasNext()) {
            setFileStatus(context, FileStatus.NORMAL);
            return Cbact04cMapperInterface.Cbact04cFdXreffileRecToAwsM2CarddemoCardxrefVsamKsdsDto.INSTANCE
                    .toSource(iterator.next());
        } else {
            setFileStatus(context, FileStatus.INVALID_KEY_READ);
            return null;
        }
    }

    public void write(OpenFrameContext context, Cbact04cFdXreffileRec data) {
        List<AwsM2CarddemoCardxrefVsamKsdsDto> writeBuffer = getWriteBuffer(context);
        writeBuffer
                .add(Cbact04cMapperInterface.Cbact04cFdXreffileRecToAwsM2CarddemoCardxrefVsamKsdsDto.INSTANCE
                        .toTarget(data));
        if (writeBuffer.size() >= committer.getThreshold()) {
            committer.commit(dao::writeDto, writeBuffer);
            writeBuffer.clear();
        }
        setFileStatus(context, FileStatus.NORMAL);
    }

    public void rewrite(OpenFrameContext context, Cbact04cFdXreffileRec data,
            String key) {
        commit(context);
        data.setFdXrefCardNum(key);
        AwsM2CarddemoCardxrefVsamKsdsDto updateDto = Cbact04cMapperInterface.Cbact04cFdXreffileRecToAwsM2CarddemoCardxrefVsamKsdsDto.INSTANCE
                .toTarget(data);
        dao.flush();
        dao.rewriteDto(updateDto);
        List<BatchResult> resultList = dao.flush();
        if (resultList.get(0).getUpdateCounts()[0] > 0) {
            setFileStatus(context, FileStatus.NORMAL);
        } else {
            setFileStatus(context, FileStatus.INVALID_KEY_CREATE);
        }
    }

    public void delete(OpenFrameContext context, String key) {
        if (getIterator(context) == null) {
            return;
        }
        commit(context);
        Cbact04cFdXreffileRec deletePoint = new Cbact04cFdXreffileRec();
        deletePoint.setFdXrefCardNum(key);
        AwsM2CarddemoCardxrefVsamKsdsDto dto = Cbact04cMapperInterface.Cbact04cFdXreffileRecKeyToAwsM2CarddemoCardxrefVsamKsdsDto.INSTANCE
                .toTarget(deletePoint);
        dao.flush();
        dao.deleteDto(dto);
        List<BatchResult> resultList = dao.flush();
        if (resultList.get(0).getUpdateCounts()[0] > 0) {
            setFileStatus(context, FileStatus.NORMAL);
        } else {
            setFileStatus(context, FileStatus.INVALID_KEY_READ);
        }
    }

    public void close(OpenFrameContext context) {
        commit(context);
        setIterator(context, null);
        setFileStatus(context, FileStatus.NORMAL);
    }

    public void commit(OpenFrameContext context) {
        List<AwsM2CarddemoCardxrefVsamKsdsDto> writeBuffer = getWriteBuffer(context);
        if (writeBuffer != null && writeBuffer.size() > 0) {
            committer.commit(dao::writeDto, writeBuffer);
            writeBuffer.clear();
        }
    }

    private void setIterator(OpenFrameContext context,
            Iterator<AwsM2CarddemoCardxrefVsamKsdsDto> iterator) {
        context.setFileIterator("Cbact04c", "XrefFile", iterator);
    }

    private Iterator<AwsM2CarddemoCardxrefVsamKsdsDto> getIterator(
            OpenFrameContext context) {
        return context.getFileIterator("Cbact04c", "XrefFile");
    }

    private List<AwsM2CarddemoCardxrefVsamKsdsDto> getWriteBuffer(
            OpenFrameContext context) {
        return context.getFileWriteBuffer("Cbact04c", "XrefFile");
    }
}
