package aws.carddemo.file;

import aws.carddemo.dao.*;
import aws.carddemo.dto.*;
import aws.carddemo.mapper.*;
import aws.carddemo.variable.group.Cbcus01cFdCustfileRec;
import com.tmax.openframe.runtime.context.OpenFrameContext;
import com.tmax.openframe.runtime.file.FileStatus;
import com.tmax.openframe.runtime.file.KeyOperationType;
import com.tmax.openframe.runtime.file.RecordCommitter;
import java.math.*;
import java.util.*;
import lombok.*;
import org.apache.ibatis.executor.BatchResult;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

/** 
 * <p>This source code was generated by T-Up OpenFrame COBOL to Java migrator</p>
 * <p>  Generation date : 2024/05/02 05:55:55 UTC</p>
 * <hr>
 * <p>Class for processing file I/O operations</p>
 * <ul>
 * <li>target dataset: AwsM2CarddemoCustdataVsamKsds</li>
 * <li>file operation class: {@link Cbcus01cFileOpCustfileFile}</li>
 * <li>DAO class: {@link AwsM2CarddemoCustdataVsamKsdsDao}</li>
 * <li>DTO class: {@link AwsM2CarddemoCustdataVsamKsdsDto}</li>
 * </ul>
 */
@Repository
public class Cbcus01cFdCustfileFile extends Cbcus01cFileOpCustfileFile {
    @Autowired
    private AwsM2CarddemoCustdataVsamKsdsDao dao;
    @Autowired
    private RecordCommitter<AwsM2CarddemoCustdataVsamKsdsDto> committer;

    public void open(OpenFrameContext context) {
        setIterator(context, dao.readAllAsc().iterator());
        setFileStatus(context, FileStatus.NORMAL);
        context.initFileWriteBuffer("Cbcus01c", "CustfileFile");
        committer.setThreshold(5000);
    }

    public void start(OpenFrameContext context, Integer key,
            KeyOperationType type) {
        Cbcus01cFdCustfileRec startPoint = new Cbcus01cFdCustfileRec();
        startPoint.setFdCustId(key);
        AwsM2CarddemoCustdataVsamKsdsDto dto = Cbcus01cMapperInterface.Cbcus01cFdCustfileRecKeyToAwsM2CarddemoCustdataVsamKsdsDto.INSTANCE
                .toTarget(startPoint);
        switch (type) {
        case EQ:
        case GTEQ: {
            setIterator(context, dao.readGeDto(dto).iterator());
            break;
        }
        case GT: {
            setIterator(context, dao.readGtDto(dto).iterator());
            break;
        }
        default: {
            throw new RuntimeException(
                    "not supported operation for start method");
        }
        }
        if (!getIterator(context).hasNext()) {
            setFileStatus(context, FileStatus.INVALID_KEY_READ);
        } else {
            setFileStatus(context, FileStatus.NORMAL);
        }
    }

    public Cbcus01cFdCustfileRec readNextRecord(OpenFrameContext context) {
        Iterator<AwsM2CarddemoCustdataVsamKsdsDto> iterator = getIterator(context);
        if (iterator.hasNext()) {
            AwsM2CarddemoCustdataVsamKsdsDto nextRecord = iterator.next();
            if (nextRecord == null) {
                setFileStatus(context, FileStatus.AT_END_CONDITION_SEQ_READ);
                return null;
            }
            setFileStatus(context, FileStatus.NORMAL);
            return Cbcus01cMapperInterface.Cbcus01cFdCustfileRecToAwsM2CarddemoCustdataVsamKsdsDto.INSTANCE
                    .toSource(nextRecord);
        } else {
            setFileStatus(context, FileStatus.AT_END_CONDITION_SEQ_READ);
            return null;
        }
    }

    public Cbcus01cFdCustfileRec readKey(OpenFrameContext context, Integer key) {
        commit(context);
        Cbcus01cFdCustfileRec readKeyPoint = new Cbcus01cFdCustfileRec();
        readKeyPoint.setFdCustId(key);
        AwsM2CarddemoCustdataVsamKsdsDto dto = Cbcus01cMapperInterface.Cbcus01cFdCustfileRecKeyToAwsM2CarddemoCustdataVsamKsdsDto.INSTANCE
                .toTarget(readKeyPoint);
        Iterator<AwsM2CarddemoCustdataVsamKsdsDto> iterator = dao
                .readEqDto(dto).iterator();
        setIterator(context, iterator);
        if (iterator.hasNext()) {
            setFileStatus(context, FileStatus.NORMAL);
            return Cbcus01cMapperInterface.Cbcus01cFdCustfileRecToAwsM2CarddemoCustdataVsamKsdsDto.INSTANCE
                    .toSource(iterator.next());
        } else {
            setFileStatus(context, FileStatus.INVALID_KEY_READ);
            return null;
        }
    }

    public void write(OpenFrameContext context, Cbcus01cFdCustfileRec data) {
        List<AwsM2CarddemoCustdataVsamKsdsDto> writeBuffer = getWriteBuffer(context);
        writeBuffer
                .add(Cbcus01cMapperInterface.Cbcus01cFdCustfileRecToAwsM2CarddemoCustdataVsamKsdsDto.INSTANCE
                        .toTarget(data));
        if (writeBuffer.size() >= committer.getThreshold()) {
            committer.commit(dao::writeDto, writeBuffer);
            writeBuffer.clear();
        }
        setFileStatus(context, FileStatus.NORMAL);
    }

    public void rewrite(OpenFrameContext context, Cbcus01cFdCustfileRec data,
            Integer key) {
        commit(context);
        data.setFdCustId(key);
        AwsM2CarddemoCustdataVsamKsdsDto updateDto = Cbcus01cMapperInterface.Cbcus01cFdCustfileRecToAwsM2CarddemoCustdataVsamKsdsDto.INSTANCE
                .toTarget(data);
        dao.flush();
        dao.rewriteDto(updateDto);
        List<BatchResult> resultList = dao.flush();
        if (resultList.get(0).getUpdateCounts()[0] > 0) {
            setFileStatus(context, FileStatus.NORMAL);
        } else {
            setFileStatus(context, FileStatus.INVALID_KEY_CREATE);
        }
    }

    public void delete(OpenFrameContext context, Integer key) {
        if (getIterator(context) == null) {
            return;
        }
        commit(context);
        Cbcus01cFdCustfileRec deletePoint = new Cbcus01cFdCustfileRec();
        deletePoint.setFdCustId(key);
        AwsM2CarddemoCustdataVsamKsdsDto dto = Cbcus01cMapperInterface.Cbcus01cFdCustfileRecKeyToAwsM2CarddemoCustdataVsamKsdsDto.INSTANCE
                .toTarget(deletePoint);
        dao.flush();
        dao.deleteDto(dto);
        List<BatchResult> resultList = dao.flush();
        if (resultList.get(0).getUpdateCounts()[0] > 0) {
            setFileStatus(context, FileStatus.NORMAL);
        } else {
            setFileStatus(context, FileStatus.INVALID_KEY_READ);
        }
    }

    public void close(OpenFrameContext context) {
        commit(context);
        setIterator(context, null);
        setFileStatus(context, FileStatus.NORMAL);
    }

    public void commit(OpenFrameContext context) {
        List<AwsM2CarddemoCustdataVsamKsdsDto> writeBuffer = getWriteBuffer(context);
        if (writeBuffer != null && writeBuffer.size() > 0) {
            committer.commit(dao::writeDto, writeBuffer);
            writeBuffer.clear();
        }
    }

    private void setIterator(OpenFrameContext context,
            Iterator<AwsM2CarddemoCustdataVsamKsdsDto> iterator) {
        context.setFileIterator("Cbcus01c", "CustfileFile", iterator);
    }

    private Iterator<AwsM2CarddemoCustdataVsamKsdsDto> getIterator(
            OpenFrameContext context) {
        return context.getFileIterator("Cbcus01c", "CustfileFile");
    }

    private List<AwsM2CarddemoCustdataVsamKsdsDto> getWriteBuffer(
            OpenFrameContext context) {
        return context.getFileWriteBuffer("Cbcus01c", "CustfileFile");
    }
}
