package aws.carddemo.variable.group;

import java.math.*;
import java.nio.ByteBuffer;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.stream.*;
import lombok.*;
import org.apache.commons.lang3.StringUtils;

/** 
 * <p>This source code was generated by T-Up OpenFrame COBOL to Java migrator</p>
 * <p>  Generation date : 2024/05/02 05:57:44 UTC</p>
 */
public @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class Comen01cComen1ai {
    // [T-Up#INFO][COMEN01.CPY, LINE #19] FILLER (level: 2)
    private @Getter @Builder.Default String OFFILLER1 = StringUtils.repeat(' ',
            12);
    // [T-Up#INFO][COMEN01.CPY, LINE #20] TRNNAMEL (level: 2)
    private @Getter @Setter int trnnamel;
    // [T-Up#INFO][COMEN01.CPY, LINE #21] TRNNAMEF (level: 2)
    private @Getter @Builder.Default String trnnamef = StringUtils.repeat(' ',
            1);

    public _OFFILLER2 getOFFILLER2() {
        return _OFFILLER2.builder().trnnamea(getTrnnamea()).build();
    }

    public void setOFFILLER2(String source) {
        setTrnnamea(source.substring(0, 1));
    }

    public void setOFFILLER2(_OFFILLER2 source) {
        setOFFILLER2(source.toString());
    }

    public String getTrnnamea() {
        return getTrnnamef();
    }

    public void setTrnnamea(String source) {
        setTrnnamef(source);
    }

    // [T-Up#INFO][COMEN01.CPY, LINE #24] FILLER (level: 2)
    private @Getter @Builder.Default String OFFILLER3 = StringUtils.repeat(' ',
            4);
    // [T-Up#INFO][COMEN01.CPY, LINE #25] TRNNAMEI (level: 2)
    private @Getter @Builder.Default String trnnamei = StringUtils.repeat(' ',
            4);
    // [T-Up#INFO][COMEN01.CPY, LINE #26] TITLE01L (level: 2)
    private @Getter @Setter int title01l;
    // [T-Up#INFO][COMEN01.CPY, LINE #27] TITLE01F (level: 2)
    private @Getter @Builder.Default String title01f = StringUtils.repeat(' ',
            1);

    public _OFFILLER4 getOFFILLER4() {
        return _OFFILLER4.builder().title01a(getTitle01a()).build();
    }

    public void setOFFILLER4(String source) {
        setTitle01a(source.substring(0, 1));
    }

    public void setOFFILLER4(_OFFILLER4 source) {
        setOFFILLER4(source.toString());
    }

    public String getTitle01a() {
        return getTitle01f();
    }

    public void setTitle01a(String source) {
        setTitle01f(source);
    }

    // [T-Up#INFO][COMEN01.CPY, LINE #30] FILLER (level: 2)
    private @Getter @Builder.Default String OFFILLER5 = StringUtils.repeat(' ',
            4);
    // [T-Up#INFO][COMEN01.CPY, LINE #31] TITLE01I (level: 2)
    private @Getter @Builder.Default String title01i = StringUtils.repeat(' ',
            40);
    // [T-Up#INFO][COMEN01.CPY, LINE #32] CURDATEL (level: 2)
    private @Getter @Setter int curdatel;
    // [T-Up#INFO][COMEN01.CPY, LINE #33] CURDATEF (level: 2)
    private @Getter @Builder.Default String curdatef = StringUtils.repeat(' ',
            1);

    public _OFFILLER6 getOFFILLER6() {
        return _OFFILLER6.builder().curdatea(getCurdatea()).build();
    }

    public void setOFFILLER6(String source) {
        setCurdatea(source.substring(0, 1));
    }

    public void setOFFILLER6(_OFFILLER6 source) {
        setOFFILLER6(source.toString());
    }

    public String getCurdatea() {
        return getCurdatef();
    }

    public void setCurdatea(String source) {
        setCurdatef(source);
    }

    // [T-Up#INFO][COMEN01.CPY, LINE #36] FILLER (level: 2)
    private @Getter @Builder.Default String OFFILLER7 = StringUtils.repeat(' ',
            4);
    // [T-Up#INFO][COMEN01.CPY, LINE #37] CURDATEI (level: 2)
    private @Getter @Builder.Default String curdatei = StringUtils.repeat(' ',
            8);
    // [T-Up#INFO][COMEN01.CPY, LINE #38] PGMNAMEL (level: 2)
    private @Getter @Setter int pgmnamel;
    // [T-Up#INFO][COMEN01.CPY, LINE #39] PGMNAMEF (level: 2)
    private @Getter @Builder.Default String pgmnamef = StringUtils.repeat(' ',
            1);

    public _OFFILLER8 getOFFILLER8() {
        return _OFFILLER8.builder().pgmnamea(getPgmnamea()).build();
    }

    public void setOFFILLER8(String source) {
        setPgmnamea(source.substring(0, 1));
    }

    public void setOFFILLER8(_OFFILLER8 source) {
        setOFFILLER8(source.toString());
    }

    public String getPgmnamea() {
        return getPgmnamef();
    }

    public void setPgmnamea(String source) {
        setPgmnamef(source);
    }

    // [T-Up#INFO][COMEN01.CPY, LINE #42] FILLER (level: 2)
    private @Getter @Builder.Default String OFFILLER9 = StringUtils.repeat(' ',
            4);
    // [T-Up#INFO][COMEN01.CPY, LINE #43] PGMNAMEI (level: 2)
    private @Getter @Builder.Default String pgmnamei = StringUtils.repeat(' ',
            8);
    // [T-Up#INFO][COMEN01.CPY, LINE #44] TITLE02L (level: 2)
    private @Getter @Setter int title02l;
    // [T-Up#INFO][COMEN01.CPY, LINE #45] TITLE02F (level: 2)
    private @Getter @Builder.Default String title02f = StringUtils.repeat(' ',
            1);

    public _OFFILLER10 getOFFILLER10() {
        return _OFFILLER10.builder().title02a(getTitle02a()).build();
    }

    public void setOFFILLER10(String source) {
        setTitle02a(source.substring(0, 1));
    }

    public void setOFFILLER10(_OFFILLER10 source) {
        setOFFILLER10(source.toString());
    }

    public String getTitle02a() {
        return getTitle02f();
    }

    public void setTitle02a(String source) {
        setTitle02f(source);
    }

    // [T-Up#INFO][COMEN01.CPY, LINE #48] FILLER (level: 2)
    private @Getter @Builder.Default String OFFILLER11 = StringUtils.repeat(
            ' ', 4);
    // [T-Up#INFO][COMEN01.CPY, LINE #49] TITLE02I (level: 2)
    private @Getter @Builder.Default String title02i = StringUtils.repeat(' ',
            40);
    // [T-Up#INFO][COMEN01.CPY, LINE #50] CURTIMEL (level: 2)
    private @Getter @Setter int curtimel;
    // [T-Up#INFO][COMEN01.CPY, LINE #51] CURTIMEF (level: 2)
    private @Getter @Builder.Default String curtimef = StringUtils.repeat(' ',
            1);

    public _OFFILLER12 getOFFILLER12() {
        return _OFFILLER12.builder().curtimea(getCurtimea()).build();
    }

    public void setOFFILLER12(String source) {
        setCurtimea(source.substring(0, 1));
    }

    public void setOFFILLER12(_OFFILLER12 source) {
        setOFFILLER12(source.toString());
    }

    public String getCurtimea() {
        return getCurtimef();
    }

    public void setCurtimea(String source) {
        setCurtimef(source);
    }

    // [T-Up#INFO][COMEN01.CPY, LINE #54] FILLER (level: 2)
    private @Getter @Builder.Default String OFFILLER13 = StringUtils.repeat(
            ' ', 4);
    // [T-Up#INFO][COMEN01.CPY, LINE #55] CURTIMEI (level: 2)
    private @Getter @Builder.Default String curtimei = StringUtils.repeat(' ',
            8);
    // [T-Up#INFO][COMEN01.CPY, LINE #56] OPTN001L (level: 2)
    private @Getter @Setter int optn001l;
    // [T-Up#INFO][COMEN01.CPY, LINE #57] OPTN001F (level: 2)
    private @Getter @Builder.Default String optn001f = StringUtils.repeat(' ',
            1);

    public _OFFILLER14 getOFFILLER14() {
        return _OFFILLER14.builder().optn001a(getOptn001a()).build();
    }

    public void setOFFILLER14(String source) {
        setOptn001a(source.substring(0, 1));
    }

    public void setOFFILLER14(_OFFILLER14 source) {
        setOFFILLER14(source.toString());
    }

    public String getOptn001a() {
        return getOptn001f();
    }

    public void setOptn001a(String source) {
        setOptn001f(source);
    }

    // [T-Up#INFO][COMEN01.CPY, LINE #60] FILLER (level: 2)
    private @Getter @Builder.Default String OFFILLER15 = StringUtils.repeat(
            ' ', 4);
    // [T-Up#INFO][COMEN01.CPY, LINE #61] OPTN001I (level: 2)
    private @Getter @Builder.Default String optn001i = StringUtils.repeat(' ',
            40);
    // [T-Up#INFO][COMEN01.CPY, LINE #62] OPTN002L (level: 2)
    private @Getter @Setter int optn002l;
    // [T-Up#INFO][COMEN01.CPY, LINE #63] OPTN002F (level: 2)
    private @Getter @Builder.Default String optn002f = StringUtils.repeat(' ',
            1);

    public _OFFILLER16 getOFFILLER16() {
        return _OFFILLER16.builder().optn002a(getOptn002a()).build();
    }

    public void setOFFILLER16(String source) {
        setOptn002a(source.substring(0, 1));
    }

    public void setOFFILLER16(_OFFILLER16 source) {
        setOFFILLER16(source.toString());
    }

    public String getOptn002a() {
        return getOptn002f();
    }

    public void setOptn002a(String source) {
        setOptn002f(source);
    }

    // [T-Up#INFO][COMEN01.CPY, LINE #66] FILLER (level: 2)
    private @Getter @Builder.Default String OFFILLER17 = StringUtils.repeat(
            ' ', 4);
    // [T-Up#INFO][COMEN01.CPY, LINE #67] OPTN002I (level: 2)
    private @Getter @Builder.Default String optn002i = StringUtils.repeat(' ',
            40);
    // [T-Up#INFO][COMEN01.CPY, LINE #68] OPTN003L (level: 2)
    private @Getter @Setter int optn003l;
    // [T-Up#INFO][COMEN01.CPY, LINE #69] OPTN003F (level: 2)
    private @Getter @Builder.Default String optn003f = StringUtils.repeat(' ',
            1);

    public _OFFILLER18 getOFFILLER18() {
        return _OFFILLER18.builder().optn003a(getOptn003a()).build();
    }

    public void setOFFILLER18(String source) {
        setOptn003a(source.substring(0, 1));
    }

    public void setOFFILLER18(_OFFILLER18 source) {
        setOFFILLER18(source.toString());
    }

    public String getOptn003a() {
        return getOptn003f();
    }

    public void setOptn003a(String source) {
        setOptn003f(source);
    }

    // [T-Up#INFO][COMEN01.CPY, LINE #72] FILLER (level: 2)
    private @Getter @Builder.Default String OFFILLER19 = StringUtils.repeat(
            ' ', 4);
    // [T-Up#INFO][COMEN01.CPY, LINE #73] OPTN003I (level: 2)
    private @Getter @Builder.Default String optn003i = StringUtils.repeat(' ',
            40);
    // [T-Up#INFO][COMEN01.CPY, LINE #74] OPTN004L (level: 2)
    private @Getter @Setter int optn004l;
    // [T-Up#INFO][COMEN01.CPY, LINE #75] OPTN004F (level: 2)
    private @Getter @Builder.Default String optn004f = StringUtils.repeat(' ',
            1);

    public _OFFILLER20 getOFFILLER20() {
        return _OFFILLER20.builder().optn004a(getOptn004a()).build();
    }

    public void setOFFILLER20(String source) {
        setOptn004a(source.substring(0, 1));
    }

    public void setOFFILLER20(_OFFILLER20 source) {
        setOFFILLER20(source.toString());
    }

    public String getOptn004a() {
        return getOptn004f();
    }

    public void setOptn004a(String source) {
        setOptn004f(source);
    }

    // [T-Up#INFO][COMEN01.CPY, LINE #78] FILLER (level: 2)
    private @Getter @Builder.Default String OFFILLER21 = StringUtils.repeat(
            ' ', 4);
    // [T-Up#INFO][COMEN01.CPY, LINE #79] OPTN004I (level: 2)
    private @Getter @Builder.Default String optn004i = StringUtils.repeat(' ',
            40);
    // [T-Up#INFO][COMEN01.CPY, LINE #80] OPTN005L (level: 2)
    private @Getter @Setter int optn005l;
    // [T-Up#INFO][COMEN01.CPY, LINE #81] OPTN005F (level: 2)
    private @Getter @Builder.Default String optn005f = StringUtils.repeat(' ',
            1);

    public _OFFILLER22 getOFFILLER22() {
        return _OFFILLER22.builder().optn005a(getOptn005a()).build();
    }

    public void setOFFILLER22(String source) {
        setOptn005a(source.substring(0, 1));
    }

    public void setOFFILLER22(_OFFILLER22 source) {
        setOFFILLER22(source.toString());
    }

    public String getOptn005a() {
        return getOptn005f();
    }

    public void setOptn005a(String source) {
        setOptn005f(source);
    }

    // [T-Up#INFO][COMEN01.CPY, LINE #84] FILLER (level: 2)
    private @Getter @Builder.Default String OFFILLER23 = StringUtils.repeat(
            ' ', 4);
    // [T-Up#INFO][COMEN01.CPY, LINE #85] OPTN005I (level: 2)
    private @Getter @Builder.Default String optn005i = StringUtils.repeat(' ',
            40);
    // [T-Up#INFO][COMEN01.CPY, LINE #86] OPTN006L (level: 2)
    private @Getter @Setter int optn006l;
    // [T-Up#INFO][COMEN01.CPY, LINE #87] OPTN006F (level: 2)
    private @Getter @Builder.Default String optn006f = StringUtils.repeat(' ',
            1);

    public _OFFILLER24 getOFFILLER24() {
        return _OFFILLER24.builder().optn006a(getOptn006a()).build();
    }

    public void setOFFILLER24(String source) {
        setOptn006a(source.substring(0, 1));
    }

    public void setOFFILLER24(_OFFILLER24 source) {
        setOFFILLER24(source.toString());
    }

    public String getOptn006a() {
        return getOptn006f();
    }

    public void setOptn006a(String source) {
        setOptn006f(source);
    }

    // [T-Up#INFO][COMEN01.CPY, LINE #90] FILLER (level: 2)
    private @Getter @Builder.Default String OFFILLER25 = StringUtils.repeat(
            ' ', 4);
    // [T-Up#INFO][COMEN01.CPY, LINE #91] OPTN006I (level: 2)
    private @Getter @Builder.Default String optn006i = StringUtils.repeat(' ',
            40);
    // [T-Up#INFO][COMEN01.CPY, LINE #92] OPTN007L (level: 2)
    private @Getter @Setter int optn007l;
    // [T-Up#INFO][COMEN01.CPY, LINE #93] OPTN007F (level: 2)
    private @Getter @Builder.Default String optn007f = StringUtils.repeat(' ',
            1);

    public _OFFILLER26 getOFFILLER26() {
        return _OFFILLER26.builder().optn007a(getOptn007a()).build();
    }

    public void setOFFILLER26(String source) {
        setOptn007a(source.substring(0, 1));
    }

    public void setOFFILLER26(_OFFILLER26 source) {
        setOFFILLER26(source.toString());
    }

    public String getOptn007a() {
        return getOptn007f();
    }

    public void setOptn007a(String source) {
        setOptn007f(source);
    }

    // [T-Up#INFO][COMEN01.CPY, LINE #96] FILLER (level: 2)
    private @Getter @Builder.Default String OFFILLER27 = StringUtils.repeat(
            ' ', 4);
    // [T-Up#INFO][COMEN01.CPY, LINE #97] OPTN007I (level: 2)
    private @Getter @Builder.Default String optn007i = StringUtils.repeat(' ',
            40);
    // [T-Up#INFO][COMEN01.CPY, LINE #98] OPTN008L (level: 2)
    private @Getter @Setter int optn008l;
    // [T-Up#INFO][COMEN01.CPY, LINE #99] OPTN008F (level: 2)
    private @Getter @Builder.Default String optn008f = StringUtils.repeat(' ',
            1);

    public _OFFILLER28 getOFFILLER28() {
        return _OFFILLER28.builder().optn008a(getOptn008a()).build();
    }

    public void setOFFILLER28(String source) {
        setOptn008a(source.substring(0, 1));
    }

    public void setOFFILLER28(_OFFILLER28 source) {
        setOFFILLER28(source.toString());
    }

    public String getOptn008a() {
        return getOptn008f();
    }

    public void setOptn008a(String source) {
        setOptn008f(source);
    }

    // [T-Up#INFO][COMEN01.CPY, LINE #102] FILLER (level: 2)
    private @Getter @Builder.Default String OFFILLER29 = StringUtils.repeat(
            ' ', 4);
    // [T-Up#INFO][COMEN01.CPY, LINE #103] OPTN008I (level: 2)
    private @Getter @Builder.Default String optn008i = StringUtils.repeat(' ',
            40);
    // [T-Up#INFO][COMEN01.CPY, LINE #104] OPTN009L (level: 2)
    private @Getter @Setter int optn009l;
    // [T-Up#INFO][COMEN01.CPY, LINE #105] OPTN009F (level: 2)
    private @Getter @Builder.Default String optn009f = StringUtils.repeat(' ',
            1);

    public _OFFILLER30 getOFFILLER30() {
        return _OFFILLER30.builder().optn009a(getOptn009a()).build();
    }

    public void setOFFILLER30(String source) {
        setOptn009a(source.substring(0, 1));
    }

    public void setOFFILLER30(_OFFILLER30 source) {
        setOFFILLER30(source.toString());
    }

    public String getOptn009a() {
        return getOptn009f();
    }

    public void setOptn009a(String source) {
        setOptn009f(source);
    }

    // [T-Up#INFO][COMEN01.CPY, LINE #108] FILLER (level: 2)
    private @Getter @Builder.Default String OFFILLER31 = StringUtils.repeat(
            ' ', 4);
    // [T-Up#INFO][COMEN01.CPY, LINE #109] OPTN009I (level: 2)
    private @Getter @Builder.Default String optn009i = StringUtils.repeat(' ',
            40);
    // [T-Up#INFO][COMEN01.CPY, LINE #110] OPTN010L (level: 2)
    private @Getter @Setter int optn010l;
    // [T-Up#INFO][COMEN01.CPY, LINE #111] OPTN010F (level: 2)
    private @Getter @Builder.Default String optn010f = StringUtils.repeat(' ',
            1);

    public _OFFILLER32 getOFFILLER32() {
        return _OFFILLER32.builder().optn010a(getOptn010a()).build();
    }

    public void setOFFILLER32(String source) {
        setOptn010a(source.substring(0, 1));
    }

    public void setOFFILLER32(_OFFILLER32 source) {
        setOFFILLER32(source.toString());
    }

    public String getOptn010a() {
        return getOptn010f();
    }

    public void setOptn010a(String source) {
        setOptn010f(source);
    }

    // [T-Up#INFO][COMEN01.CPY, LINE #114] FILLER (level: 2)
    private @Getter @Builder.Default String OFFILLER33 = StringUtils.repeat(
            ' ', 4);
    // [T-Up#INFO][COMEN01.CPY, LINE #115] OPTN010I (level: 2)
    private @Getter @Builder.Default String optn010i = StringUtils.repeat(' ',
            40);
    // [T-Up#INFO][COMEN01.CPY, LINE #116] OPTN011L (level: 2)
    private @Getter @Setter int optn011l;
    // [T-Up#INFO][COMEN01.CPY, LINE #117] OPTN011F (level: 2)
    private @Getter @Builder.Default String optn011f = StringUtils.repeat(' ',
            1);

    public _OFFILLER34 getOFFILLER34() {
        return _OFFILLER34.builder().optn011a(getOptn011a()).build();
    }

    public void setOFFILLER34(String source) {
        setOptn011a(source.substring(0, 1));
    }

    public void setOFFILLER34(_OFFILLER34 source) {
        setOFFILLER34(source.toString());
    }

    public String getOptn011a() {
        return getOptn011f();
    }

    public void setOptn011a(String source) {
        setOptn011f(source);
    }

    // [T-Up#INFO][COMEN01.CPY, LINE #120] FILLER (level: 2)
    private @Getter @Builder.Default String OFFILLER35 = StringUtils.repeat(
            ' ', 4);
    // [T-Up#INFO][COMEN01.CPY, LINE #121] OPTN011I (level: 2)
    private @Getter @Builder.Default String optn011i = StringUtils.repeat(' ',
            40);
    // [T-Up#INFO][COMEN01.CPY, LINE #122] OPTN012L (level: 2)
    private @Getter @Setter int optn012l;
    // [T-Up#INFO][COMEN01.CPY, LINE #123] OPTN012F (level: 2)
    private @Getter @Builder.Default String optn012f = StringUtils.repeat(' ',
            1);

    public _OFFILLER36 getOFFILLER36() {
        return _OFFILLER36.builder().optn012a(getOptn012a()).build();
    }

    public void setOFFILLER36(String source) {
        setOptn012a(source.substring(0, 1));
    }

    public void setOFFILLER36(_OFFILLER36 source) {
        setOFFILLER36(source.toString());
    }

    public String getOptn012a() {
        return getOptn012f();
    }

    public void setOptn012a(String source) {
        setOptn012f(source);
    }

    // [T-Up#INFO][COMEN01.CPY, LINE #126] FILLER (level: 2)
    private @Getter @Builder.Default String OFFILLER37 = StringUtils.repeat(
            ' ', 4);
    // [T-Up#INFO][COMEN01.CPY, LINE #127] OPTN012I (level: 2)
    private @Getter @Builder.Default String optn012i = StringUtils.repeat(' ',
            40);
    // [T-Up#INFO][COMEN01.CPY, LINE #128] OPTIONL (level: 2)
    private @Getter @Setter int optionl;
    // [T-Up#INFO][COMEN01.CPY, LINE #129] OPTIONF (level: 2)
    private @Getter @Builder.Default String optionf = StringUtils
            .repeat(' ', 1);

    public _OFFILLER38 getOFFILLER38() {
        return _OFFILLER38.builder().optiona(getOptiona()).build();
    }

    public void setOFFILLER38(String source) {
        setOptiona(source.substring(0, 1));
    }

    public void setOFFILLER38(_OFFILLER38 source) {
        setOFFILLER38(source.toString());
    }

    public String getOptiona() {
        return getOptionf();
    }

    public void setOptiona(String source) {
        setOptionf(source);
    }

    // [T-Up#INFO][COMEN01.CPY, LINE #132] FILLER (level: 2)
    private @Getter @Builder.Default String OFFILLER39 = StringUtils.repeat(
            ' ', 4);
    // [T-Up#INFO][COMEN01.CPY, LINE #133] OPTIONI (level: 2)
    private @Getter @Builder.Default String optioni = StringUtils
            .repeat(' ', 2);
    // [T-Up#INFO][COMEN01.CPY, LINE #134] ERRMSGL (level: 2)
    private @Getter @Setter int errmsgl;
    // [T-Up#INFO][COMEN01.CPY, LINE #135] ERRMSGF (level: 2)
    private @Getter @Builder.Default String errmsgf = StringUtils
            .repeat(' ', 1);

    public _OFFILLER40 getOFFILLER40() {
        return _OFFILLER40.builder().errmsga(getErrmsga()).build();
    }

    public void setOFFILLER40(String source) {
        setErrmsga(source.substring(0, 1));
    }

    public void setOFFILLER40(_OFFILLER40 source) {
        setOFFILLER40(source.toString());
    }

    public String getErrmsga() {
        return getErrmsgf();
    }

    public void setErrmsga(String source) {
        setErrmsgf(source);
    }

    // [T-Up#INFO][COMEN01.CPY, LINE #138] FILLER (level: 2)
    private @Getter @Builder.Default String OFFILLER41 = StringUtils.repeat(
            ' ', 4);
    // [T-Up#INFO][COMEN01.CPY, LINE #139] ERRMSGI (level: 2)
    private @Getter @Builder.Default String errmsgi = StringUtils.repeat(' ',
            78);

    public void setOFFILLER1(String source) {
        OFFILLER1 = StringUtils.truncate(StringUtils.rightPad(source, 12), 12);
    }

    public void setTrnnamef(String source) {
        trnnamef = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setOFFILLER3(String source) {
        OFFILLER3 = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setTrnnamei(String source) {
        trnnamei = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setTitle01f(String source) {
        title01f = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setOFFILLER5(String source) {
        OFFILLER5 = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setTitle01i(String source) {
        title01i = StringUtils.truncate(StringUtils.rightPad(source, 40), 40);
    }

    public void setCurdatef(String source) {
        curdatef = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setOFFILLER7(String source) {
        OFFILLER7 = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setCurdatei(String source) {
        curdatei = StringUtils.truncate(StringUtils.rightPad(source, 8), 8);
    }

    public void setPgmnamef(String source) {
        pgmnamef = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setOFFILLER9(String source) {
        OFFILLER9 = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setPgmnamei(String source) {
        pgmnamei = StringUtils.truncate(StringUtils.rightPad(source, 8), 8);
    }

    public void setTitle02f(String source) {
        title02f = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setOFFILLER11(String source) {
        OFFILLER11 = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setTitle02i(String source) {
        title02i = StringUtils.truncate(StringUtils.rightPad(source, 40), 40);
    }

    public void setCurtimef(String source) {
        curtimef = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setOFFILLER13(String source) {
        OFFILLER13 = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setCurtimei(String source) {
        curtimei = StringUtils.truncate(StringUtils.rightPad(source, 8), 8);
    }

    public void setOptn001f(String source) {
        optn001f = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setOFFILLER15(String source) {
        OFFILLER15 = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setOptn001i(String source) {
        optn001i = StringUtils.truncate(StringUtils.rightPad(source, 40), 40);
    }

    public void setOptn002f(String source) {
        optn002f = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setOFFILLER17(String source) {
        OFFILLER17 = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setOptn002i(String source) {
        optn002i = StringUtils.truncate(StringUtils.rightPad(source, 40), 40);
    }

    public void setOptn003f(String source) {
        optn003f = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setOFFILLER19(String source) {
        OFFILLER19 = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setOptn003i(String source) {
        optn003i = StringUtils.truncate(StringUtils.rightPad(source, 40), 40);
    }

    public void setOptn004f(String source) {
        optn004f = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setOFFILLER21(String source) {
        OFFILLER21 = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setOptn004i(String source) {
        optn004i = StringUtils.truncate(StringUtils.rightPad(source, 40), 40);
    }

    public void setOptn005f(String source) {
        optn005f = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setOFFILLER23(String source) {
        OFFILLER23 = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setOptn005i(String source) {
        optn005i = StringUtils.truncate(StringUtils.rightPad(source, 40), 40);
    }

    public void setOptn006f(String source) {
        optn006f = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setOFFILLER25(String source) {
        OFFILLER25 = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setOptn006i(String source) {
        optn006i = StringUtils.truncate(StringUtils.rightPad(source, 40), 40);
    }

    public void setOptn007f(String source) {
        optn007f = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setOFFILLER27(String source) {
        OFFILLER27 = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setOptn007i(String source) {
        optn007i = StringUtils.truncate(StringUtils.rightPad(source, 40), 40);
    }

    public void setOptn008f(String source) {
        optn008f = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setOFFILLER29(String source) {
        OFFILLER29 = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setOptn008i(String source) {
        optn008i = StringUtils.truncate(StringUtils.rightPad(source, 40), 40);
    }

    public void setOptn009f(String source) {
        optn009f = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setOFFILLER31(String source) {
        OFFILLER31 = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setOptn009i(String source) {
        optn009i = StringUtils.truncate(StringUtils.rightPad(source, 40), 40);
    }

    public void setOptn010f(String source) {
        optn010f = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setOFFILLER33(String source) {
        OFFILLER33 = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setOptn010i(String source) {
        optn010i = StringUtils.truncate(StringUtils.rightPad(source, 40), 40);
    }

    public void setOptn011f(String source) {
        optn011f = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setOFFILLER35(String source) {
        OFFILLER35 = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setOptn011i(String source) {
        optn011i = StringUtils.truncate(StringUtils.rightPad(source, 40), 40);
    }

    public void setOptn012f(String source) {
        optn012f = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setOFFILLER37(String source) {
        OFFILLER37 = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setOptn012i(String source) {
        optn012i = StringUtils.truncate(StringUtils.rightPad(source, 40), 40);
    }

    public void setOptionf(String source) {
        optionf = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setOFFILLER39(String source) {
        OFFILLER39 = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setOptioni(String source) {
        optioni = StringUtils.truncate(StringUtils.rightPad(source, 2), 2);
    }

    public void setErrmsgf(String source) {
        errmsgf = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setOFFILLER41(String source) {
        OFFILLER41 = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setErrmsgi(String source) {
        errmsgi = StringUtils.truncate(StringUtils.rightPad(source, 78), 78);
    }

    public static Comen01cComen1ai createDefaultValueInstance() {
        return new Comen01cComen1ai.builder().build();
    }

    public void set(String source) {
        ByteBuffer tempByteBuffer1;
        source = StringUtils.truncate(StringUtils.rightPad(source, 820), 820);
        OFFILLER1 = source.substring(0, 12);
        try {
            tempByteBuffer1 = ByteBuffer.allocate(Short.BYTES);
            tempByteBuffer1.put(source.substring(12, 14).getBytes(
                    StandardCharsets.ISO_8859_1));
            tempByteBuffer1.flip();
            trnnamel = tempByteBuffer1.getShort();
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            trnnamel = 0;
        }
        trnnamef = source.substring(14, 15);
        OFFILLER3 = source.substring(15, 19);
        trnnamei = source.substring(19, 23);
        try {
            tempByteBuffer1 = ByteBuffer.allocate(Short.BYTES);
            tempByteBuffer1.put(source.substring(23, 25).getBytes(
                    StandardCharsets.ISO_8859_1));
            tempByteBuffer1.flip();
            title01l = tempByteBuffer1.getShort();
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            title01l = 0;
        }
        title01f = source.substring(25, 26);
        OFFILLER5 = source.substring(26, 30);
        title01i = source.substring(30, 70);
        try {
            tempByteBuffer1 = ByteBuffer.allocate(Short.BYTES);
            tempByteBuffer1.put(source.substring(70, 72).getBytes(
                    StandardCharsets.ISO_8859_1));
            tempByteBuffer1.flip();
            curdatel = tempByteBuffer1.getShort();
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            curdatel = 0;
        }
        curdatef = source.substring(72, 73);
        OFFILLER7 = source.substring(73, 77);
        curdatei = source.substring(77, 85);
        try {
            tempByteBuffer1 = ByteBuffer.allocate(Short.BYTES);
            tempByteBuffer1.put(source.substring(85, 87).getBytes(
                    StandardCharsets.ISO_8859_1));
            tempByteBuffer1.flip();
            pgmnamel = tempByteBuffer1.getShort();
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            pgmnamel = 0;
        }
        pgmnamef = source.substring(87, 88);
        OFFILLER9 = source.substring(88, 92);
        pgmnamei = source.substring(92, 100);
        try {
            tempByteBuffer1 = ByteBuffer.allocate(Short.BYTES);
            tempByteBuffer1.put(source.substring(100, 102).getBytes(
                    StandardCharsets.ISO_8859_1));
            tempByteBuffer1.flip();
            title02l = tempByteBuffer1.getShort();
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            title02l = 0;
        }
        title02f = source.substring(102, 103);
        OFFILLER11 = source.substring(103, 107);
        title02i = source.substring(107, 147);
        try {
            tempByteBuffer1 = ByteBuffer.allocate(Short.BYTES);
            tempByteBuffer1.put(source.substring(147, 149).getBytes(
                    StandardCharsets.ISO_8859_1));
            tempByteBuffer1.flip();
            curtimel = tempByteBuffer1.getShort();
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            curtimel = 0;
        }
        curtimef = source.substring(149, 150);
        OFFILLER13 = source.substring(150, 154);
        curtimei = source.substring(154, 162);
        try {
            tempByteBuffer1 = ByteBuffer.allocate(Short.BYTES);
            tempByteBuffer1.put(source.substring(162, 164).getBytes(
                    StandardCharsets.ISO_8859_1));
            tempByteBuffer1.flip();
            optn001l = tempByteBuffer1.getShort();
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            optn001l = 0;
        }
        optn001f = source.substring(164, 165);
        OFFILLER15 = source.substring(165, 169);
        optn001i = source.substring(169, 209);
        try {
            tempByteBuffer1 = ByteBuffer.allocate(Short.BYTES);
            tempByteBuffer1.put(source.substring(209, 211).getBytes(
                    StandardCharsets.ISO_8859_1));
            tempByteBuffer1.flip();
            optn002l = tempByteBuffer1.getShort();
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            optn002l = 0;
        }
        optn002f = source.substring(211, 212);
        OFFILLER17 = source.substring(212, 216);
        optn002i = source.substring(216, 256);
        try {
            tempByteBuffer1 = ByteBuffer.allocate(Short.BYTES);
            tempByteBuffer1.put(source.substring(256, 258).getBytes(
                    StandardCharsets.ISO_8859_1));
            tempByteBuffer1.flip();
            optn003l = tempByteBuffer1.getShort();
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            optn003l = 0;
        }
        optn003f = source.substring(258, 259);
        OFFILLER19 = source.substring(259, 263);
        optn003i = source.substring(263, 303);
        try {
            tempByteBuffer1 = ByteBuffer.allocate(Short.BYTES);
            tempByteBuffer1.put(source.substring(303, 305).getBytes(
                    StandardCharsets.ISO_8859_1));
            tempByteBuffer1.flip();
            optn004l = tempByteBuffer1.getShort();
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            optn004l = 0;
        }
        optn004f = source.substring(305, 306);
        OFFILLER21 = source.substring(306, 310);
        optn004i = source.substring(310, 350);
        try {
            tempByteBuffer1 = ByteBuffer.allocate(Short.BYTES);
            tempByteBuffer1.put(source.substring(350, 352).getBytes(
                    StandardCharsets.ISO_8859_1));
            tempByteBuffer1.flip();
            optn005l = tempByteBuffer1.getShort();
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            optn005l = 0;
        }
        optn005f = source.substring(352, 353);
        OFFILLER23 = source.substring(353, 357);
        optn005i = source.substring(357, 397);
        try {
            tempByteBuffer1 = ByteBuffer.allocate(Short.BYTES);
            tempByteBuffer1.put(source.substring(397, 399).getBytes(
                    StandardCharsets.ISO_8859_1));
            tempByteBuffer1.flip();
            optn006l = tempByteBuffer1.getShort();
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            optn006l = 0;
        }
        optn006f = source.substring(399, 400);
        OFFILLER25 = source.substring(400, 404);
        optn006i = source.substring(404, 444);
        try {
            tempByteBuffer1 = ByteBuffer.allocate(Short.BYTES);
            tempByteBuffer1.put(source.substring(444, 446).getBytes(
                    StandardCharsets.ISO_8859_1));
            tempByteBuffer1.flip();
            optn007l = tempByteBuffer1.getShort();
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            optn007l = 0;
        }
        optn007f = source.substring(446, 447);
        OFFILLER27 = source.substring(447, 451);
        optn007i = source.substring(451, 491);
        try {
            tempByteBuffer1 = ByteBuffer.allocate(Short.BYTES);
            tempByteBuffer1.put(source.substring(491, 493).getBytes(
                    StandardCharsets.ISO_8859_1));
            tempByteBuffer1.flip();
            optn008l = tempByteBuffer1.getShort();
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            optn008l = 0;
        }
        optn008f = source.substring(493, 494);
        OFFILLER29 = source.substring(494, 498);
        optn008i = source.substring(498, 538);
        try {
            tempByteBuffer1 = ByteBuffer.allocate(Short.BYTES);
            tempByteBuffer1.put(source.substring(538, 540).getBytes(
                    StandardCharsets.ISO_8859_1));
            tempByteBuffer1.flip();
            optn009l = tempByteBuffer1.getShort();
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            optn009l = 0;
        }
        optn009f = source.substring(540, 541);
        OFFILLER31 = source.substring(541, 545);
        optn009i = source.substring(545, 585);
        try {
            tempByteBuffer1 = ByteBuffer.allocate(Short.BYTES);
            tempByteBuffer1.put(source.substring(585, 587).getBytes(
                    StandardCharsets.ISO_8859_1));
            tempByteBuffer1.flip();
            optn010l = tempByteBuffer1.getShort();
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            optn010l = 0;
        }
        optn010f = source.substring(587, 588);
        OFFILLER33 = source.substring(588, 592);
        optn010i = source.substring(592, 632);
        try {
            tempByteBuffer1 = ByteBuffer.allocate(Short.BYTES);
            tempByteBuffer1.put(source.substring(632, 634).getBytes(
                    StandardCharsets.ISO_8859_1));
            tempByteBuffer1.flip();
            optn011l = tempByteBuffer1.getShort();
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            optn011l = 0;
        }
        optn011f = source.substring(634, 635);
        OFFILLER35 = source.substring(635, 639);
        optn011i = source.substring(639, 679);
        try {
            tempByteBuffer1 = ByteBuffer.allocate(Short.BYTES);
            tempByteBuffer1.put(source.substring(679, 681).getBytes(
                    StandardCharsets.ISO_8859_1));
            tempByteBuffer1.flip();
            optn012l = tempByteBuffer1.getShort();
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            optn012l = 0;
        }
        optn012f = source.substring(681, 682);
        OFFILLER37 = source.substring(682, 686);
        optn012i = source.substring(686, 726);
        try {
            tempByteBuffer1 = ByteBuffer.allocate(Short.BYTES);
            tempByteBuffer1.put(source.substring(726, 728).getBytes(
                    StandardCharsets.ISO_8859_1));
            tempByteBuffer1.flip();
            optionl = tempByteBuffer1.getShort();
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            optionl = 0;
        }
        optionf = source.substring(728, 729);
        OFFILLER39 = source.substring(729, 733);
        optioni = source.substring(733, 735);
        try {
            tempByteBuffer1 = ByteBuffer.allocate(Short.BYTES);
            tempByteBuffer1.put(source.substring(735, 737).getBytes(
                    StandardCharsets.ISO_8859_1));
            tempByteBuffer1.flip();
            errmsgl = tempByteBuffer1.getShort();
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            errmsgl = 0;
        }
        errmsgf = source.substring(737, 738);
        OFFILLER41 = source.substring(738, 742);
        errmsgi = source.substring(742, 820);
    }

    public String get() {
        ByteBuffer tempByteBuffer1;
        StringBuilder sb = new StringBuilder();
        sb.append(OFFILLER1);
        tempByteBuffer1 = ByteBuffer.allocate(Short.BYTES);
        tempByteBuffer1.putShort((short) trnnamel);
        tempByteBuffer1.flip();
        sb.append(StandardCharsets.ISO_8859_1.decode(tempByteBuffer1)
                .toString());
        sb.append(trnnamef);
        sb.append(OFFILLER3);
        sb.append(trnnamei);
        tempByteBuffer1 = ByteBuffer.allocate(Short.BYTES);
        tempByteBuffer1.putShort((short) title01l);
        tempByteBuffer1.flip();
        sb.append(StandardCharsets.ISO_8859_1.decode(tempByteBuffer1)
                .toString());
        sb.append(title01f);
        sb.append(OFFILLER5);
        sb.append(title01i);
        tempByteBuffer1 = ByteBuffer.allocate(Short.BYTES);
        tempByteBuffer1.putShort((short) curdatel);
        tempByteBuffer1.flip();
        sb.append(StandardCharsets.ISO_8859_1.decode(tempByteBuffer1)
                .toString());
        sb.append(curdatef);
        sb.append(OFFILLER7);
        sb.append(curdatei);
        tempByteBuffer1 = ByteBuffer.allocate(Short.BYTES);
        tempByteBuffer1.putShort((short) pgmnamel);
        tempByteBuffer1.flip();
        sb.append(StandardCharsets.ISO_8859_1.decode(tempByteBuffer1)
                .toString());
        sb.append(pgmnamef);
        sb.append(OFFILLER9);
        sb.append(pgmnamei);
        tempByteBuffer1 = ByteBuffer.allocate(Short.BYTES);
        tempByteBuffer1.putShort((short) title02l);
        tempByteBuffer1.flip();
        sb.append(StandardCharsets.ISO_8859_1.decode(tempByteBuffer1)
                .toString());
        sb.append(title02f);
        sb.append(OFFILLER11);
        sb.append(title02i);
        tempByteBuffer1 = ByteBuffer.allocate(Short.BYTES);
        tempByteBuffer1.putShort((short) curtimel);
        tempByteBuffer1.flip();
        sb.append(StandardCharsets.ISO_8859_1.decode(tempByteBuffer1)
                .toString());
        sb.append(curtimef);
        sb.append(OFFILLER13);
        sb.append(curtimei);
        tempByteBuffer1 = ByteBuffer.allocate(Short.BYTES);
        tempByteBuffer1.putShort((short) optn001l);
        tempByteBuffer1.flip();
        sb.append(StandardCharsets.ISO_8859_1.decode(tempByteBuffer1)
                .toString());
        sb.append(optn001f);
        sb.append(OFFILLER15);
        sb.append(optn001i);
        tempByteBuffer1 = ByteBuffer.allocate(Short.BYTES);
        tempByteBuffer1.putShort((short) optn002l);
        tempByteBuffer1.flip();
        sb.append(StandardCharsets.ISO_8859_1.decode(tempByteBuffer1)
                .toString());
        sb.append(optn002f);
        sb.append(OFFILLER17);
        sb.append(optn002i);
        tempByteBuffer1 = ByteBuffer.allocate(Short.BYTES);
        tempByteBuffer1.putShort((short) optn003l);
        tempByteBuffer1.flip();
        sb.append(StandardCharsets.ISO_8859_1.decode(tempByteBuffer1)
                .toString());
        sb.append(optn003f);
        sb.append(OFFILLER19);
        sb.append(optn003i);
        tempByteBuffer1 = ByteBuffer.allocate(Short.BYTES);
        tempByteBuffer1.putShort((short) optn004l);
        tempByteBuffer1.flip();
        sb.append(StandardCharsets.ISO_8859_1.decode(tempByteBuffer1)
                .toString());
        sb.append(optn004f);
        sb.append(OFFILLER21);
        sb.append(optn004i);
        tempByteBuffer1 = ByteBuffer.allocate(Short.BYTES);
        tempByteBuffer1.putShort((short) optn005l);
        tempByteBuffer1.flip();
        sb.append(StandardCharsets.ISO_8859_1.decode(tempByteBuffer1)
                .toString());
        sb.append(optn005f);
        sb.append(OFFILLER23);
        sb.append(optn005i);
        tempByteBuffer1 = ByteBuffer.allocate(Short.BYTES);
        tempByteBuffer1.putShort((short) optn006l);
        tempByteBuffer1.flip();
        sb.append(StandardCharsets.ISO_8859_1.decode(tempByteBuffer1)
                .toString());
        sb.append(optn006f);
        sb.append(OFFILLER25);
        sb.append(optn006i);
        tempByteBuffer1 = ByteBuffer.allocate(Short.BYTES);
        tempByteBuffer1.putShort((short) optn007l);
        tempByteBuffer1.flip();
        sb.append(StandardCharsets.ISO_8859_1.decode(tempByteBuffer1)
                .toString());
        sb.append(optn007f);
        sb.append(OFFILLER27);
        sb.append(optn007i);
        tempByteBuffer1 = ByteBuffer.allocate(Short.BYTES);
        tempByteBuffer1.putShort((short) optn008l);
        tempByteBuffer1.flip();
        sb.append(StandardCharsets.ISO_8859_1.decode(tempByteBuffer1)
                .toString());
        sb.append(optn008f);
        sb.append(OFFILLER29);
        sb.append(optn008i);
        tempByteBuffer1 = ByteBuffer.allocate(Short.BYTES);
        tempByteBuffer1.putShort((short) optn009l);
        tempByteBuffer1.flip();
        sb.append(StandardCharsets.ISO_8859_1.decode(tempByteBuffer1)
                .toString());
        sb.append(optn009f);
        sb.append(OFFILLER31);
        sb.append(optn009i);
        tempByteBuffer1 = ByteBuffer.allocate(Short.BYTES);
        tempByteBuffer1.putShort((short) optn010l);
        tempByteBuffer1.flip();
        sb.append(StandardCharsets.ISO_8859_1.decode(tempByteBuffer1)
                .toString());
        sb.append(optn010f);
        sb.append(OFFILLER33);
        sb.append(optn010i);
        tempByteBuffer1 = ByteBuffer.allocate(Short.BYTES);
        tempByteBuffer1.putShort((short) optn011l);
        tempByteBuffer1.flip();
        sb.append(StandardCharsets.ISO_8859_1.decode(tempByteBuffer1)
                .toString());
        sb.append(optn011f);
        sb.append(OFFILLER35);
        sb.append(optn011i);
        tempByteBuffer1 = ByteBuffer.allocate(Short.BYTES);
        tempByteBuffer1.putShort((short) optn012l);
        tempByteBuffer1.flip();
        sb.append(StandardCharsets.ISO_8859_1.decode(tempByteBuffer1)
                .toString());
        sb.append(optn012f);
        sb.append(OFFILLER37);
        sb.append(optn012i);
        tempByteBuffer1 = ByteBuffer.allocate(Short.BYTES);
        tempByteBuffer1.putShort((short) optionl);
        tempByteBuffer1.flip();
        sb.append(StandardCharsets.ISO_8859_1.decode(tempByteBuffer1)
                .toString());
        sb.append(optionf);
        sb.append(OFFILLER39);
        sb.append(optioni);
        tempByteBuffer1 = ByteBuffer.allocate(Short.BYTES);
        tempByteBuffer1.putShort((short) errmsgl);
        tempByteBuffer1.flip();
        sb.append(StandardCharsets.ISO_8859_1.decode(tempByteBuffer1)
                .toString());
        sb.append(errmsgf);
        sb.append(OFFILLER41);
        sb.append(errmsgi);
        return sb.toString();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(OFFILLER1);
        sb.append(String.valueOf(getTrnnamel()));
        sb.append(getTrnnamef());
        sb.append(OFFILLER3);
        sb.append(getTrnnamei());
        sb.append(String.valueOf(getTitle01l()));
        sb.append(getTitle01f());
        sb.append(OFFILLER5);
        sb.append(getTitle01i());
        sb.append(String.valueOf(getCurdatel()));
        sb.append(getCurdatef());
        sb.append(OFFILLER7);
        sb.append(getCurdatei());
        sb.append(String.valueOf(getPgmnamel()));
        sb.append(getPgmnamef());
        sb.append(OFFILLER9);
        sb.append(getPgmnamei());
        sb.append(String.valueOf(getTitle02l()));
        sb.append(getTitle02f());
        sb.append(OFFILLER11);
        sb.append(getTitle02i());
        sb.append(String.valueOf(getCurtimel()));
        sb.append(getCurtimef());
        sb.append(OFFILLER13);
        sb.append(getCurtimei());
        sb.append(String.valueOf(getOptn001l()));
        sb.append(getOptn001f());
        sb.append(OFFILLER15);
        sb.append(getOptn001i());
        sb.append(String.valueOf(getOptn002l()));
        sb.append(getOptn002f());
        sb.append(OFFILLER17);
        sb.append(getOptn002i());
        sb.append(String.valueOf(getOptn003l()));
        sb.append(getOptn003f());
        sb.append(OFFILLER19);
        sb.append(getOptn003i());
        sb.append(String.valueOf(getOptn004l()));
        sb.append(getOptn004f());
        sb.append(OFFILLER21);
        sb.append(getOptn004i());
        sb.append(String.valueOf(getOptn005l()));
        sb.append(getOptn005f());
        sb.append(OFFILLER23);
        sb.append(getOptn005i());
        sb.append(String.valueOf(getOptn006l()));
        sb.append(getOptn006f());
        sb.append(OFFILLER25);
        sb.append(getOptn006i());
        sb.append(String.valueOf(getOptn007l()));
        sb.append(getOptn007f());
        sb.append(OFFILLER27);
        sb.append(getOptn007i());
        sb.append(String.valueOf(getOptn008l()));
        sb.append(getOptn008f());
        sb.append(OFFILLER29);
        sb.append(getOptn008i());
        sb.append(String.valueOf(getOptn009l()));
        sb.append(getOptn009f());
        sb.append(OFFILLER31);
        sb.append(getOptn009i());
        sb.append(String.valueOf(getOptn010l()));
        sb.append(getOptn010f());
        sb.append(OFFILLER33);
        sb.append(getOptn010i());
        sb.append(String.valueOf(getOptn011l()));
        sb.append(getOptn011f());
        sb.append(OFFILLER35);
        sb.append(getOptn011i());
        sb.append(String.valueOf(getOptn012l()));
        sb.append(getOptn012f());
        sb.append(OFFILLER37);
        sb.append(getOptn012i());
        sb.append(String.valueOf(getOptionl()));
        sb.append(getOptionf());
        sb.append(OFFILLER39);
        sb.append(getOptioni());
        sb.append(String.valueOf(getErrmsgl()));
        sb.append(getErrmsgf());
        sb.append(OFFILLER41);
        sb.append(getErrmsgi());
        return sb.toString();
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class _OFFILLER2 {
        // [T-Up#INFO][COMEN01.CPY, LINE #23] TRNNAMEA (level: 3)
        private @Getter String trnnamea = StringUtils.repeat(' ', 1);

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(trnnamea);
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(trnnamea);
            return sb.toString();
        }
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class _OFFILLER4 {
        // [T-Up#INFO][COMEN01.CPY, LINE #29] TITLE01A (level: 3)
        private @Getter String title01a = StringUtils.repeat(' ', 1);

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(title01a);
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(title01a);
            return sb.toString();
        }
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class _OFFILLER6 {
        // [T-Up#INFO][COMEN01.CPY, LINE #35] CURDATEA (level: 3)
        private @Getter String curdatea = StringUtils.repeat(' ', 1);

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(curdatea);
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(curdatea);
            return sb.toString();
        }
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class _OFFILLER8 {
        // [T-Up#INFO][COMEN01.CPY, LINE #41] PGMNAMEA (level: 3)
        private @Getter String pgmnamea = StringUtils.repeat(' ', 1);

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(pgmnamea);
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(pgmnamea);
            return sb.toString();
        }
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class _OFFILLER10 {
        // [T-Up#INFO][COMEN01.CPY, LINE #47] TITLE02A (level: 3)
        private @Getter String title02a = StringUtils.repeat(' ', 1);

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(title02a);
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(title02a);
            return sb.toString();
        }
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class _OFFILLER12 {
        // [T-Up#INFO][COMEN01.CPY, LINE #53] CURTIMEA (level: 3)
        private @Getter String curtimea = StringUtils.repeat(' ', 1);

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(curtimea);
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(curtimea);
            return sb.toString();
        }
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class _OFFILLER14 {
        // [T-Up#INFO][COMEN01.CPY, LINE #59] OPTN001A (level: 3)
        private @Getter String optn001a = StringUtils.repeat(' ', 1);

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(optn001a);
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(optn001a);
            return sb.toString();
        }
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class _OFFILLER16 {
        // [T-Up#INFO][COMEN01.CPY, LINE #65] OPTN002A (level: 3)
        private @Getter String optn002a = StringUtils.repeat(' ', 1);

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(optn002a);
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(optn002a);
            return sb.toString();
        }
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class _OFFILLER18 {
        // [T-Up#INFO][COMEN01.CPY, LINE #71] OPTN003A (level: 3)
        private @Getter String optn003a = StringUtils.repeat(' ', 1);

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(optn003a);
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(optn003a);
            return sb.toString();
        }
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class _OFFILLER20 {
        // [T-Up#INFO][COMEN01.CPY, LINE #77] OPTN004A (level: 3)
        private @Getter String optn004a = StringUtils.repeat(' ', 1);

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(optn004a);
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(optn004a);
            return sb.toString();
        }
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class _OFFILLER22 {
        // [T-Up#INFO][COMEN01.CPY, LINE #83] OPTN005A (level: 3)
        private @Getter String optn005a = StringUtils.repeat(' ', 1);

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(optn005a);
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(optn005a);
            return sb.toString();
        }
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class _OFFILLER24 {
        // [T-Up#INFO][COMEN01.CPY, LINE #89] OPTN006A (level: 3)
        private @Getter String optn006a = StringUtils.repeat(' ', 1);

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(optn006a);
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(optn006a);
            return sb.toString();
        }
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class _OFFILLER26 {
        // [T-Up#INFO][COMEN01.CPY, LINE #95] OPTN007A (level: 3)
        private @Getter String optn007a = StringUtils.repeat(' ', 1);

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(optn007a);
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(optn007a);
            return sb.toString();
        }
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class _OFFILLER28 {
        // [T-Up#INFO][COMEN01.CPY, LINE #101] OPTN008A (level: 3)
        private @Getter String optn008a = StringUtils.repeat(' ', 1);

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(optn008a);
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(optn008a);
            return sb.toString();
        }
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class _OFFILLER30 {
        // [T-Up#INFO][COMEN01.CPY, LINE #107] OPTN009A (level: 3)
        private @Getter String optn009a = StringUtils.repeat(' ', 1);

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(optn009a);
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(optn009a);
            return sb.toString();
        }
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class _OFFILLER32 {
        // [T-Up#INFO][COMEN01.CPY, LINE #113] OPTN010A (level: 3)
        private @Getter String optn010a = StringUtils.repeat(' ', 1);

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(optn010a);
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(optn010a);
            return sb.toString();
        }
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class _OFFILLER34 {
        // [T-Up#INFO][COMEN01.CPY, LINE #119] OPTN011A (level: 3)
        private @Getter String optn011a = StringUtils.repeat(' ', 1);

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(optn011a);
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(optn011a);
            return sb.toString();
        }
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class _OFFILLER36 {
        // [T-Up#INFO][COMEN01.CPY, LINE #125] OPTN012A (level: 3)
        private @Getter String optn012a = StringUtils.repeat(' ', 1);

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(optn012a);
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(optn012a);
            return sb.toString();
        }
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class _OFFILLER38 {
        // [T-Up#INFO][COMEN01.CPY, LINE #131] OPTIONA (level: 3)
        private @Getter String optiona = StringUtils.repeat(' ', 1);

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(optiona);
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(optiona);
            return sb.toString();
        }
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class _OFFILLER40 {
        // [T-Up#INFO][COMEN01.CPY, LINE #137] ERRMSGA (level: 3)
        private @Getter String errmsga = StringUtils.repeat(' ', 1);

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(errmsga);
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(errmsga);
            return sb.toString();
        }
    }
}
