package aws.carddemo.file;

import aws.carddemo.dao.*;
import aws.carddemo.dto.*;
import aws.carddemo.mapper.*;
import aws.carddemo.variable.group.Cbtrn02cFdTranCatBalRecord;
import com.tmax.openframe.runtime.context.OpenFrameContext;
import com.tmax.openframe.runtime.file.FileStatus;
import com.tmax.openframe.runtime.file.KeyOperationType;
import com.tmax.openframe.runtime.file.RecordCommitter;
import java.math.*;
import java.util.*;
import lombok.*;
import org.apache.ibatis.executor.BatchResult;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

/** 
 * <p>This source code was generated by T-Up OpenFrame COBOL to Java migrator</p>
 * <p>  Generation date : 2024/05/02 05:55:56 UTC</p>
 * <hr>
 * <p>Class for processing file I/O operations</p>
 * <ul>
 * <li>target dataset: AwsM2CarddemoTcatbalfVsamKsds</li>
 * <li>file operation class: {@link Cbtrn02cFileOpTcatbalFile}</li>
 * <li>DAO class: {@link AwsM2CarddemoTcatbalfVsamKsdsDao}</li>
 * <li>DTO class: {@link AwsM2CarddemoTcatbalfVsamKsdsDto}</li>
 * </ul>
 */
@Repository
public class Cbtrn02cFdTcatbalFile extends Cbtrn02cFileOpTcatbalFile {
    @Autowired
    private AwsM2CarddemoTcatbalfVsamKsdsDao dao;
    @Autowired
    private RecordCommitter<AwsM2CarddemoTcatbalfVsamKsdsDto> committer;

    public void open(OpenFrameContext context) {
        setIterator(context, dao.readAllAsc().iterator());
        setFileStatus(context, FileStatus.NORMAL);
        context.initFileWriteBuffer("Cbtrn02c", "TcatbalFile");
        committer.setThreshold(5000);
    }

    public void start(OpenFrameContext context,
            Cbtrn02cFdTranCatBalRecord.Cbtrn02cFdTranCatKey key,
            KeyOperationType type) {
        Cbtrn02cFdTranCatBalRecord startPoint = new Cbtrn02cFdTranCatBalRecord();
        startPoint.setFdTranCatKey(key);
        AwsM2CarddemoTcatbalfVsamKsdsDto dto = Cbtrn02cMapperInterface.Cbtrn02cFdTranCatBalRecordKeyToAwsM2CarddemoTcatbalfVsamKsdsDto.INSTANCE
                .toTarget(startPoint);
        switch (type) {
        case EQ:
        case GTEQ: {
            setIterator(context, dao.readGeDto(dto).iterator());
            break;
        }
        case GT: {
            setIterator(context, dao.readGtDto(dto).iterator());
            break;
        }
        default: {
            throw new RuntimeException(
                    "not supported operation for start method");
        }
        }
        if (!getIterator(context).hasNext()) {
            setFileStatus(context, FileStatus.INVALID_KEY_READ);
        } else {
            setFileStatus(context, FileStatus.NORMAL);
        }
    }

    public Cbtrn02cFdTranCatBalRecord readNextRecord(OpenFrameContext context) {
        Iterator<AwsM2CarddemoTcatbalfVsamKsdsDto> iterator = getIterator(context);
        if (iterator.hasNext()) {
            AwsM2CarddemoTcatbalfVsamKsdsDto nextRecord = iterator.next();
            if (nextRecord == null) {
                setFileStatus(context, FileStatus.AT_END_CONDITION_SEQ_READ);
                return null;
            }
            setFileStatus(context, FileStatus.NORMAL);
            return Cbtrn02cMapperInterface.Cbtrn02cFdTranCatBalRecordToAwsM2CarddemoTcatbalfVsamKsdsDto.INSTANCE
                    .toSource(nextRecord);
        } else {
            setFileStatus(context, FileStatus.AT_END_CONDITION_SEQ_READ);
            return null;
        }
    }

    public Cbtrn02cFdTranCatBalRecord readKey(OpenFrameContext context,
            Cbtrn02cFdTranCatBalRecord.Cbtrn02cFdTranCatKey key) {
        commit(context);
        Cbtrn02cFdTranCatBalRecord readKeyPoint = new Cbtrn02cFdTranCatBalRecord();
        readKeyPoint.setFdTranCatKey(key);
        AwsM2CarddemoTcatbalfVsamKsdsDto dto = Cbtrn02cMapperInterface.Cbtrn02cFdTranCatBalRecordKeyToAwsM2CarddemoTcatbalfVsamKsdsDto.INSTANCE
                .toTarget(readKeyPoint);
        Iterator<AwsM2CarddemoTcatbalfVsamKsdsDto> iterator = dao
                .readEqDto(dto).iterator();
        setIterator(context, iterator);
        if (iterator.hasNext()) {
            setFileStatus(context, FileStatus.NORMAL);
            return Cbtrn02cMapperInterface.Cbtrn02cFdTranCatBalRecordToAwsM2CarddemoTcatbalfVsamKsdsDto.INSTANCE
                    .toSource(iterator.next());
        } else {
            setFileStatus(context, FileStatus.INVALID_KEY_READ);
            return null;
        }
    }

    public void write(OpenFrameContext context, Cbtrn02cFdTranCatBalRecord data) {
        List<AwsM2CarddemoTcatbalfVsamKsdsDto> writeBuffer = getWriteBuffer(context);
        writeBuffer
                .add(Cbtrn02cMapperInterface.Cbtrn02cFdTranCatBalRecordToAwsM2CarddemoTcatbalfVsamKsdsDto.INSTANCE
                        .toTarget(data));
        if (writeBuffer.size() >= committer.getThreshold()) {
            committer.commit(dao::writeDto, writeBuffer);
            writeBuffer.clear();
        }
        setFileStatus(context, FileStatus.NORMAL);
    }

    public void rewrite(OpenFrameContext context,
            Cbtrn02cFdTranCatBalRecord data,
            Cbtrn02cFdTranCatBalRecord.Cbtrn02cFdTranCatKey key) {
        commit(context);
        data.setFdTranCatKey(key);
        AwsM2CarddemoTcatbalfVsamKsdsDto updateDto = Cbtrn02cMapperInterface.Cbtrn02cFdTranCatBalRecordToAwsM2CarddemoTcatbalfVsamKsdsDto.INSTANCE
                .toTarget(data);
        dao.flush();
        dao.rewriteDto(updateDto);
        List<BatchResult> resultList = dao.flush();
        if (resultList.get(0).getUpdateCounts()[0] > 0) {
            setFileStatus(context, FileStatus.NORMAL);
        } else {
            setFileStatus(context, FileStatus.INVALID_KEY_CREATE);
        }
    }

    public void delete(OpenFrameContext context,
            Cbtrn02cFdTranCatBalRecord.Cbtrn02cFdTranCatKey key) {
        if (getIterator(context) == null) {
            return;
        }
        commit(context);
        Cbtrn02cFdTranCatBalRecord deletePoint = new Cbtrn02cFdTranCatBalRecord();
        deletePoint.setFdTranCatKey(key);
        AwsM2CarddemoTcatbalfVsamKsdsDto dto = Cbtrn02cMapperInterface.Cbtrn02cFdTranCatBalRecordKeyToAwsM2CarddemoTcatbalfVsamKsdsDto.INSTANCE
                .toTarget(deletePoint);
        dao.flush();
        dao.deleteDto(dto);
        List<BatchResult> resultList = dao.flush();
        if (resultList.get(0).getUpdateCounts()[0] > 0) {
            setFileStatus(context, FileStatus.NORMAL);
        } else {
            setFileStatus(context, FileStatus.INVALID_KEY_READ);
        }
    }

    public void close(OpenFrameContext context) {
        commit(context);
        setIterator(context, null);
        setFileStatus(context, FileStatus.NORMAL);
    }

    public void commit(OpenFrameContext context) {
        List<AwsM2CarddemoTcatbalfVsamKsdsDto> writeBuffer = getWriteBuffer(context);
        if (writeBuffer != null && writeBuffer.size() > 0) {
            committer.commit(dao::writeDto, writeBuffer);
            writeBuffer.clear();
        }
    }

    private void setIterator(OpenFrameContext context,
            Iterator<AwsM2CarddemoTcatbalfVsamKsdsDto> iterator) {
        context.setFileIterator("Cbtrn02c", "TcatbalFile", iterator);
    }

    private Iterator<AwsM2CarddemoTcatbalfVsamKsdsDto> getIterator(
            OpenFrameContext context) {
        return context.getFileIterator("Cbtrn02c", "TcatbalFile");
    }

    private List<AwsM2CarddemoTcatbalfVsamKsdsDto> getWriteBuffer(
            OpenFrameContext context) {
        return context.getFileWriteBuffer("Cbtrn02c", "TcatbalFile");
    }
}
