openframe:
  batch:
    datasource:
      url: jdbc:tibero:thin:@192.168.103.151:8629:tb_oflab
      username: tibero
      password: tmax
      driver-class-name: com.tmax.tibero.jdbc.TbDriver

mybatis:
  mapper-locations: classpath*:**/mapper/*.xml

spring:
  main:
    allow-bean-definition-overriding: true
  output:
    ansi:
      enabled: always
