import React from 'react';
import {useToasts} from "react-toast-notifications";

const COACTUP_CACTUPAValidation = ({  ACCTSID, ACCTSIDRef, ACSTTUS, ACSTTUSRef, OPNYEAR, OPNYEARRef, OPNMON, OPNMONRef, OPNDAY, OPNDAYRef, ACRDLIM, ACRDLIMRef, EXPYEAR, EXPYEARRef, EXPMON, EXPMONRef, EXPDAY, EXPDAYRef, ACSHLIM, ACSHLIMRef, RISYEAR, RISYEARRef, RISMON, RISMONRef, RISDAY, RISDAYRef, ACURBAL, ACURBALRef, ACRCYCR, ACRCYCRRef, AADDGRP, AADDGRPRef, ACRCYDB, ACRCYDBRef, ACSTNUM, ACSTNUMRef, ACTSSN1, ACTSSN1Ref, ACTSSN2, ACTSSN2Ref, ACTSSN3, ACTSSN3Ref, DOBYEAR, DOBYEARRef, DOBMON, DOBMONRef, DOBDAY, DOBDAYRef, ACSTFCO, ACSTFCORef, ACSFNAM, ACSFNAMRef, ACSMNAM, ACSMNAMRef, ACSLNAM, ACSLNAMRef, ACSADL1, ACSADL1Ref, ACSSTTE, ACSSTTERef, ACSADL2, ACSADL2Ref, ACSZIPC, ACSZIPCRef, ACSCITY, ACSCITYRef, ACSCTRY, ACSCTRYRef, ACSPH1A, ACSPH1ARef, ACSPH1B, ACSPH1BRef, ACSPH1C, ACSPH1CRef, ACSGOVT, ACSGOVTRef, ACSPH2A, ACSPH2ARef, ACSPH2B, ACSPH2BRef, ACSPH2C, ACSPH2CRef, ACSEFTC, ACSEFTCRef, ACSPFLG, ACSPFLGRef, }) => {
    // const {addToast} = useToasts();

    const validate = () => {
        return true;
    }

    return validate();

};
export default COACTUP_CACTUPAValidation;

