package aws.carddemo;

import com.tmax.openframe.online.service.api.ProgramControl;
import aws.carddemo.dto.Cosgn00cInputDto;
import aws.carddemo.mapper.Cobil00cMapperInterface.*;
import aws.carddemo.dto.Comen01cInputDto;
import com.tmax.openframe.online.service.api.TaskInvoker;
import com.tmax.openframe.online.service.dto.taskdto.TaskDto;
import com.tmax.openframe.online.service.dto.taskdto.Data;
import com.tmax.openframe.online.service.api.Time;
import com.tmax.openframe.online.service.api.Task;
import aws.carddemo.dto.Cobil00cOutputDto;
import aws.carddemo.dto.Cobil00cInputDto;
import com.tmax.openframe.online.service.exception.ConditionException;
import aws.carddemo.dto.AwsM2CarddemoAcctdataVsamKsdsDto;
import com.tmax.openframe.online.service.api.ReadPointManager;
import com.tmax.openframe.online.service.api.RecordKeyAccessor;
import aws.carddemo.dto.AwsM2CarddemoCardxrefVsamKsdsDto;
import aws.carddemo.dao.AwsM2CarddemoTransactVsamKsdsDao;
import aws.carddemo.dto.AwsM2CarddemoTransactVsamKsdsDto;
import com.tmax.openframe.online.service.dto.ReadPoint;
import com.tmax.openframe.online.service.api.ReadPointAccessor;
import static aws.carddemo.variable.group.Cobil00cCarddemoCommarea.Cobil00cCdemoGeneralInfo.*;
import static aws.carddemo.variable.group.Cobil00cWsVariables.*;
import aws.carddemo.variable.Cobil00cVariableContainer;
import aws.carddemo.variable.group.*;
import com.tmax.openframe.DataConverter;
import com.tmax.openframe.runtime.cobol.CobStringUtils;
import com.tmax.openframe.runtime.cobol.IntrinsicFunction;
import com.tmax.openframe.runtime.context.OpenFrameContext;
import com.tmax.openframe.runtime.flow.ControlManager;
import java.math.*;
import java.util.*;
import java.util.function.Consumer;
import java.util.regex.Pattern;
import lombok.*;
import org.apache.commons.lang3.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/** 
 * <p>This source code was generated by T-Up OpenFrame COBOL to Java migrator</p>
 * <p>  Generation date : 2024/05/02 05:57:47 UTC</p>
 * <hr>
 * <p>Java class for defining logics of COBOL program</p>
 * <ul>
 * <li>The name of COBOL program: COBIL00C.cbl</li>
 * <li>Variable container class: {@link Cobil00cVariableContainer}</li>
 * </ul>
 */
@Service
@RequiredArgsConstructor
@Transactional
public class Cobil00c {
    private final ReadPointAccessor readPointAccessor;
    private final ReadPointManager readPointManager;
    private final RecordKeyAccessor recordKeyAccessor;
    private final Task task;
    private final Time time;
    private final TaskInvoker taskInvoker;
    private final ProgramControl programControl;
    /** 
     * <p>Class that manages an execution flow of the program</p>
     */
    private final ControlManager controlManager;
    Consumer<OpenFrameContext> mainPara = this::mainPara;
    Consumer<OpenFrameContext> processEnterKey = this::processEnterKey;
    Consumer<OpenFrameContext> getCurrentTimestamp = this::getCurrentTimestamp;
    Consumer<OpenFrameContext> returnToPrevScreen = this::returnToPrevScreen;
    Consumer<OpenFrameContext> sendBillpayScreen = this::sendBillpayScreen;
    Consumer<OpenFrameContext> receiveBillpayScreen = this::receiveBillpayScreen;
    Consumer<OpenFrameContext> populateHeaderInfo = this::populateHeaderInfo;
    Consumer<OpenFrameContext> readAcctdatFile = this::readAcctdatFile;
    Consumer<OpenFrameContext> updateAcctdatFile = this::updateAcctdatFile;
    Consumer<OpenFrameContext> readCxacaixFile = this::readCxacaixFile;
    Consumer<OpenFrameContext> startbrTransactFile = this::startbrTransactFile;
    Consumer<OpenFrameContext> readprevTransactFile = this::readprevTransactFile;
    Consumer<OpenFrameContext> endbrTransactFile = this::endbrTransactFile;
    Consumer<OpenFrameContext> writeTransactFile = this::writeTransactFile;
    Consumer<OpenFrameContext> clearCurrentScreen = this::clearCurrentScreen;
    Consumer<OpenFrameContext> initializeAllFields = this::initializeAllFields;
    /** 
     * <p>execution flow of COBOL program that defined in the procedure division</p>
     */
    ArrayList<Consumer> methodList = new ArrayList<>();
    {
        methodList.add(mainPara);
        methodList.add(processEnterKey);
        methodList.add(getCurrentTimestamp);
        methodList.add(returnToPrevScreen);
        methodList.add(sendBillpayScreen);
        methodList.add(receiveBillpayScreen);
        methodList.add(populateHeaderInfo);
        methodList.add(readAcctdatFile);
        methodList.add(updateAcctdatFile);
        methodList.add(readCxacaixFile);
        methodList.add(startbrTransactFile);
        methodList.add(readprevTransactFile);
        methodList.add(endbrTransactFile);
        methodList.add(writeTransactFile);
        methodList.add(clearCurrentScreen);
        methodList.add(initializeAllFields);
    }

    /** 
     * <p>method for executing a program logic that defined in the procedure division</p>
     * @param generalContext context that is necessary for executing program
     * @return return value of program
     */
    public int run(Map<String, Object> generalContext) {
        OpenFrameContext context = new OpenFrameContext(generalContext,
                methodList);
        if (context.getProgramVariableContainer("Cobil00c") == null) {
            Cobil00cVariableContainer container = new Cobil00cVariableContainer();
            context.setProgramVariableContainer("Cobil00c", container);
        }
        controlManager.run(context);
        return context.getReturnValue();
    }

    // ******************************************************************
    // * Program     : COBIL00C.CBL                                      
    // * Application : CardDemo                                          
    // * Type        : CICS COBOL Program                                
    // * Function    : Bill Payment - Pay account balance in full and a  
    // *               tractionsaction for the online bill payment.      
    // ******************************************************************
    // * Copyright Amazon.com, Inc. or its affiliates.                   
    // * All Rights Reserved.                                            
    // *                                                                 
    // * Licensed under the Apache License, Version 2.0 (the "License"). 
    // * You may not use this file except in compliance with the License.
    // * You may obtain a copy of the License at                         
    // *                                                                 
    // *    http://www.apache.org/licenses/LICENSE-2.0                   
    // *                                                                 
    // * Unless required by applicable law or agreed to in writing,      
    // * software distributed under the License is distributed on an     
    // * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,    
    // * either express or implied. See the License for the specific     
    // * language governing permissions and limitations under the License
    // ******************************************************************
    // *      OCCURS 1 TO 32767 TIMES DEPENDING ON EIBCALEN.             
    // *----------------------------------------------------------------*
    // *                       PROCEDURE DIVISION                        
    // *----------------------------------------------------------------*

    void mainPara(OpenFrameContext context) {
        Cobil00cVariableContainer container = (Cobil00cVariableContainer) context
                .getProgramVariableContainer("Cobil00c");
        // [T-Up#INFO][COBIL00C.cbl, LINE #101] SET statement
        container.getWsVariables().setWsErrFlg(ERR_FLG_OFF);
        // [T-Up#INFO][COBIL00C.cbl, LINE #102] SET statement
        container.getWsVariables().setWsUsrModified(USR_MODIFIED_NO);
        // [T-Up#INFO][COBIL00C.cbl, LINE #104] MOVE statement
        container.getWsVariables().setWsMessage(StringUtils.repeat(' ', 80));
        container.setErrmsgo(StringUtils.repeat(' ', 78));
        // [T-Up#INFO][COBIL00C.cbl, LINE #107] IF statement
        if (task.hasCommarea() == 0) {
            // [T-Up#INFO][COBIL00C.cbl, LINE #108] MOVE statement
            container.getCarddemoCommarea().getCdemoGeneralInfo()
                    .setCdemoToProgram("COSGN00C");
            // [T-Up#INFO][COBIL00C.cbl, LINE #109] MOVE statement
            container
                    .getCarddemoCommarea()
                    .getCdemoGeneralInfo()
                    .setCdemoFromTranid(
                            container.getWsVariables().getWsTranid());
            // [T-Up#INFO][COBIL00C.cbl, LINE #110] MOVE statement
            container
                    .getCarddemoCommarea()
                    .getCdemoGeneralInfo()
                    .setCdemoFromProgram(
                            container.getWsVariables().getWsPgmname());
            // [T-Up#INFO][COBIL00C.cbl, LINE #111] MOVE statement
            container.getCarddemoCommarea().getCdemoGeneralInfo()
                    .setCdemoPgmContext(0);
            // [T-Up#INFO][COBIL00C.cbl, LINE #112] EXEC_CICS statement
            /*
                               EXEC CICS                                                
                               XCTL PROGRAM('COSGN00C')                                 
                               COMMAREA(CARDDEMO-COMMAREA)                              
                               END-EXEC
             */
            Cosgn00cInputDto cosgn00cInputDto = new Cosgn00cInputDto();
            cosgn00cInputDto
                    .setDfhcommarea(Cobil00cCarddemoCommareaToCosgn00cDfhcommarea.INSTANCE
                            .toTarget(container.getCarddemoCommarea()));
            programControl.forward("CC00", cosgn00cInputDto);
            context.setReturnFlag(true);
            // [T-Up#INFO][COBIL00C.cbl, LINE #116] PERFORM statement
            controlManager.run(context, returnToPrevScreen);
            if (controlManager.isTerminate(context)) {
                return;
            }
        } else {
            // [T-Up#INFO][COBIL00C.cbl, LINE #118] MOVE statement
            container.getCarddemoCommarea().set(
                    StringUtils.overlay(container.getCarddemoCommarea().get(),
                            container.getDfhcommarea().get().substring(0, 160),
                            0, 160));
            // [T-Up#INFO][COBIL00C.cbl, LINE #119] IF statement
            if (!(container.getCarddemoCommarea().getCdemoGeneralInfo()
                    .getCdemoPgmContext() == CDEMO_PGM_REENTER)) {
                // [T-Up#INFO][COBIL00C.cbl, LINE #120] SET statement
                container.getCarddemoCommarea().getCdemoGeneralInfo()
                        .setCdemoPgmContext(CDEMO_PGM_REENTER);
                // [T-Up#INFO][COBIL00C.cbl, LINE #121] MOVE statement
                container.setCobil0ao(Cobil00cCobil0ai
                        .createDefaultValueInstance().get());
                // [T-Up#INFO][COBIL00C.cbl, LINE #122] MOVE statement
                container.getCobil0ai().setActidinl(-1);
                // [T-Up#INFO][COBIL00C.cbl, LINE #123] IF statement
                if (CobStringUtils.compare(container.getCarddemoCommarea()
                        .getCdemoCb00Info().getCdemoCb00TrnSelected(),
                        StringUtils.repeat(' ', 16)) != 0
                        && CobStringUtils.compare(container
                                .getCarddemoCommarea().getCdemoCb00Info()
                                .getCdemoCb00TrnSelected(),
                                StringUtils.repeat((char) 0x00, 16)) != 0) {
                    // [T-Up#INFO][COBIL00C.cbl, LINE #125] MOVE statement
                    container.getCobil0ai().setActidini(
                            container.getCarddemoCommarea().getCdemoCb00Info()
                                    .getCdemoCb00TrnSelected());
                    // [T-Up#INFO][COBIL00C.cbl, LINE #127] PERFORM statement
                    controlManager.run(context, processEnterKey);
                    if (controlManager.isTerminate(context)) {
                        return;
                    }
                }
                // [T-Up#INFO][COBIL00C.cbl, LINE #129] PERFORM statement
                controlManager.run(context, sendBillpayScreen);
                if (controlManager.isTerminate(context)) {
                    return;
                }
            } else {
                // [T-Up#INFO][COBIL00C.cbl, LINE #131] PERFORM statement
                controlManager.run(context, receiveBillpayScreen);
                if (controlManager.isTerminate(context)) {
                    return;
                }
                // [T-Up#INFO][COBIL00C.cbl, LINE #132] EVALUATE statement
                if (CobStringUtils.compare(task.getPressedKey(), container
                        .getDfhaid().getDfhenter()) == 0) {
                    // [T-Up#INFO][COBIL00C.cbl, LINE #134] PERFORM statement
                    controlManager.run(context, processEnterKey);
                    if (controlManager.isTerminate(context)) {
                        return;
                    }
                } else if (CobStringUtils.compare(task.getPressedKey(),
                        container.getDfhaid().getDfhpf3()) == 0) {
                    // [T-Up#INFO][COBIL00C.cbl, LINE #136] IF statement
                    if (CobStringUtils.compare(container.getCarddemoCommarea()
                            .getCdemoGeneralInfo().getCdemoFromProgram(),
                            StringUtils.repeat(' ', 8)) == 0
                            || CobStringUtils.compare(container
                                    .getCarddemoCommarea()
                                    .getCdemoGeneralInfo()
                                    .getCdemoFromProgram(),
                                    StringUtils.repeat((char) 0x00, 8)) == 0) {
                        // [T-Up#INFO][COBIL00C.cbl, LINE #137] MOVE statement
                        container.getCarddemoCommarea().getCdemoGeneralInfo()
                                .setCdemoToProgram("COMEN01C");
                        // [T-Up#INFO][COBIL00C.cbl, LINE #138] MOVE statement
                        container
                                .getCarddemoCommarea()
                                .getCdemoGeneralInfo()
                                .setCdemoFromTranid(
                                        container.getWsVariables()
                                                .getWsTranid());
                        // [T-Up#INFO][COBIL00C.cbl, LINE #139] MOVE statement
                        container
                                .getCarddemoCommarea()
                                .getCdemoGeneralInfo()
                                .setCdemoFromProgram(
                                        container.getWsVariables()
                                                .getWsPgmname());
                        // [T-Up#INFO][COBIL00C.cbl, LINE #140] MOVE statement
                        container.getCarddemoCommarea().getCdemoGeneralInfo()
                                .setCdemoPgmContext(0);
                        // [T-Up#INFO][COBIL00C.cbl, LINE #141] EXEC_CICS statement
                        /*
                                                           EXEC CICS                                
                                                           XCTL PROGRAM('COMEN01C')                 
                                                           COMMAREA(CARDDEMO-COMMAREA)              
                                                           END-EXEC
                         */
                        Comen01cInputDto comen01cInputDto = new Comen01cInputDto();
                        comen01cInputDto
                                .setDfhcommarea(Cobil00cCarddemoCommareaToComen01cDfhcommarea.INSTANCE
                                        .toTarget(container
                                                .getCarddemoCommarea()));
                        programControl.forward("CM00", comen01cInputDto);
                        context.setReturnFlag(true);
                    } else {
                        // [T-Up#INFO][COBIL00C.cbl, LINE #146] MOVE statement
                        container
                                .getCarddemoCommarea()
                                .getCdemoGeneralInfo()
                                .setCdemoToProgram(
                                        container.getCarddemoCommarea()
                                                .getCdemoGeneralInfo()
                                                .getCdemoFromProgram());
                        // [T-Up#INFO][COBIL00C.cbl, LINE #148] MOVE statement
                        container
                                .getCarddemoCommarea()
                                .getCdemoGeneralInfo()
                                .setCdemoFromTranid(
                                        container.getWsVariables()
                                                .getWsTranid());
                        // [T-Up#INFO][COBIL00C.cbl, LINE #149] MOVE statement
                        container
                                .getCarddemoCommarea()
                                .getCdemoGeneralInfo()
                                .setCdemoFromProgram(
                                        container.getWsVariables()
                                                .getWsPgmname());
                        // [T-Up#INFO][COBIL00C.cbl, LINE #150] MOVE statement
                        container.getCarddemoCommarea().getCdemoGeneralInfo()
                                .setCdemoPgmContext(0);
                        // [T-Up#INFO][COBIL00C.cbl, LINE #151] EXEC_CICS statement
                        /*
                                                           EXEC CICS                                
                                                           XCTL PROGRAM('COMEN01C')                 
                                                           COMMAREA(CARDDEMO-COMMAREA)              
                                                           END-EXEC
                         */
                        Comen01cInputDto comen01cInputDto = new Comen01cInputDto();
                        comen01cInputDto
                                .setDfhcommarea(Cobil00cCarddemoCommareaToComen01cDfhcommarea.INSTANCE
                                        .toTarget(container
                                                .getCarddemoCommarea()));
                        programControl.forward("CM00", comen01cInputDto);
                        context.setReturnFlag(true);
                    }
                    // [T-Up#INFO][COBIL00C.cbl, LINE #156] PERFORM statement
                    controlManager.run(context, returnToPrevScreen);
                    if (controlManager.isTerminate(context)) {
                        return;
                    }
                } else if (CobStringUtils.compare(task.getPressedKey(),
                        container.getDfhaid().getDfhpf4()) == 0) {
                    // [T-Up#INFO][COBIL00C.cbl, LINE #158] PERFORM statement
                    controlManager.run(context, clearCurrentScreen);
                    if (controlManager.isTerminate(context)) {
                        return;
                    }
                } else {
                    // [T-Up#INFO][COBIL00C.cbl, LINE #160] MOVE statement
                    container.getWsVariables().setWsErrFlg("Y");
                    // [T-Up#INFO][COBIL00C.cbl, LINE #161] MOVE statement
                    container.getWsVariables().setWsMessage(
                            container.getCcdaCommonMessages()
                                    .getCcdaMsgInvalidKey());
                    // [T-Up#INFO][COBIL00C.cbl, LINE #162] PERFORM statement
                    controlManager.run(context, sendBillpayScreen);
                    if (controlManager.isTerminate(context)) {
                        return;
                    }
                }
            }
        }
        // [T-Up#INFO][COBIL00C.cbl, LINE #167] EXEC_CICS statement
        /*
                       EXEC CICS RETURN                                             
                                 TRANSID (WS-TRANID)                                
                                 COMMAREA (CARDDEMO-COMMAREA)                       
                       END-EXEC
         */
        TaskDto taskDto = TaskDto
                .builder()
                .destination("CB00")
                .data(Data
                        .session(Cobil00cCarddemoCommareaToCobil00cDfhcommarea.INSTANCE
                                .toTarget(container.getCarddemoCommarea())))
                .build();
        taskInvoker.setNextTask(taskDto);
        context.setReturnFlag(true);
    }

    // *----------------------------------------------------------------*
    // *                      PROCESS-ENTER-KEY                          
    // *----------------------------------------------------------------*

    void processEnterKey(OpenFrameContext context) {
        Cobil00cVariableContainer container = (Cobil00cVariableContainer) context
                .getProgramVariableContainer("Cobil00c");
        // [T-Up#INFO][COBIL00C.cbl, LINE #177] SET statement
        container.getWsVariables().setWsConfPayFlg(CONF_PAY_NO);
        // [T-Up#INFO][COBIL00C.cbl, LINE #179] EVALUATE statement
        if (CobStringUtils.compare(container.getCobil0ai().getActidini(),
                StringUtils.repeat(' ', 11)) == 0
                || CobStringUtils.compare(
                        container.getCobil0ai().getActidini(),
                        StringUtils.repeat((char) 0x00, 11)) == 0) {
            // [T-Up#INFO][COBIL00C.cbl, LINE #181] MOVE statement
            container.getWsVariables().setWsErrFlg("Y");
            // [T-Up#INFO][COBIL00C.cbl, LINE #182] MOVE statement
            container.getWsVariables().setWsMessage(
                    "Acct ID can NOT be empty...");
            // [T-Up#INFO][COBIL00C.cbl, LINE #184] MOVE statement
            container.getCobil0ai().setActidinl(-1);
            // [T-Up#INFO][COBIL00C.cbl, LINE #185] PERFORM statement
            controlManager.run(context, sendBillpayScreen);
            if (controlManager.isTerminate(context)) {
                return;
            }
        } else {
            // [T-Up#INFO][COBIL00C.cbl, LINE #187] CONTINUE statement
        }
        // [T-Up#INFO][COBIL00C.cbl, LINE #190] IF statement
        if (!(CobStringUtils.compare(container.getWsVariables().getWsErrFlg(),
                ERR_FLG_ON) == 0)) {
            // [T-Up#INFO][COBIL00C.cbl, LINE #191] IF statement
            if (CobStringUtils.compare(container.getCobil0ai().getActidini(),
                    StringUtils.repeat(' ', 11)) == 0) {
                // [T-Up#INFO][COBIL00C.cbl, LINE #192] MOVE statement
                container.getAccountRecord().setAcctId((long) 0);
                container.getCardXrefRecord().setXrefAcctId((long) 0);
            } else {
                // [T-Up#INFO][COBIL00C.cbl, LINE #194] MOVE statement
                container.getAccountRecord().setAcctId(
                        Long.parseLong(container.getCobil0ai().getActidini()
                                .trim()));
                container.getCardXrefRecord().setXrefAcctId(
                        Long.parseLong(container.getCobil0ai().getActidini()
                                .trim()));
                // [T-Up#INFO][COBIL00C.cbl, LINE #197] EVALUATE statement
                if ((CobStringUtils.compare(container.getCobil0ai()
                        .getConfirmi(), "Y") == 0)
                        || (CobStringUtils.compare(container.getCobil0ai()
                                .getConfirmi(), "y") == 0)) {
                    // [T-Up#INFO][COBIL00C.cbl, LINE #200] SET statement
                    container.getWsVariables().setWsConfPayFlg(CONF_PAY_YES);
                    // [T-Up#INFO][COBIL00C.cbl, LINE #201] PERFORM statement
                    controlManager.run(context, readAcctdatFile);
                    if (controlManager.isTerminate(context)) {
                        return;
                    }
                } else if ((CobStringUtils.compare(container.getCobil0ai()
                        .getConfirmi(), "N") == 0)
                        || (CobStringUtils.compare(container.getCobil0ai()
                                .getConfirmi(), "n") == 0)) {
                    // [T-Up#INFO][COBIL00C.cbl, LINE #204] PERFORM statement
                    controlManager.run(context, clearCurrentScreen);
                    if (controlManager.isTerminate(context)) {
                        return;
                    }
                    // [T-Up#INFO][COBIL00C.cbl, LINE #205] MOVE statement
                    container.getWsVariables().setWsErrFlg("Y");
                } else if ((CobStringUtils.compare(container.getCobil0ai()
                        .getConfirmi(), " ") == 0)
                        || (CobStringUtils.compare(container.getCobil0ai()
                                .getConfirmi(), StringUtils.repeat((char) 0x00,
                                1)) == 0)) {
                    // [T-Up#INFO][COBIL00C.cbl, LINE #208] PERFORM statement
                    controlManager.run(context, readAcctdatFile);
                    if (controlManager.isTerminate(context)) {
                        return;
                    }
                } else {
                    // [T-Up#INFO][COBIL00C.cbl, LINE #210] MOVE statement
                    container.getWsVariables().setWsErrFlg("Y");
                    // [T-Up#INFO][COBIL00C.cbl, LINE #211] MOVE statement
                    container.getWsVariables().setWsMessage(
                            "Invalid value. Valid values are (Y/N)...");
                    // [T-Up#INFO][COBIL00C.cbl, LINE #213] MOVE statement
                    container.getCobil0ai().setConfirml(-1);
                    // [T-Up#INFO][COBIL00C.cbl, LINE #214] PERFORM statement
                    controlManager.run(context, sendBillpayScreen);
                    if (controlManager.isTerminate(context)) {
                        return;
                    }
                }
                // [T-Up#INFO][COBIL00C.cbl, LINE #217] MOVE statement
                container.getWsVariables().setWsCurrBal(
                        container.getAccountRecord().getAcctCurrBal());
                // [T-Up#INFO][COBIL00C.cbl, LINE #218] MOVE statement
                container.getCobil0ai().setCurbali(
                        container.getWsVariables().getWsCurrBal());
            }
            // [T-Up#INFO][COBIL00C.cbl, LINE #221] IF statement
            if (!(CobStringUtils.compare(container.getWsVariables()
                    .getWsErrFlg(), ERR_FLG_ON) == 0)) {
                // [T-Up#INFO][COBIL00C.cbl, LINE #222] IF statement
                if (container.getAccountRecord().getAcctCurrBal()
                        .compareTo(BigDecimal.valueOf(0)) <= 0
                        && CobStringUtils.compare(container.getCobil0ai()
                                .getActidini(), StringUtils.repeat(' ', 11)) != 0
                        && CobStringUtils.compare(container.getCobil0ai()
                                .getActidini(), StringUtils.repeat((char) 0x00,
                                11)) != 0) {
                    // [T-Up#INFO][COBIL00C.cbl, LINE #224] MOVE statement
                    container.getWsVariables().setWsErrFlg("Y");
                    // [T-Up#INFO][COBIL00C.cbl, LINE #225] MOVE statement
                    container.getWsVariables().setWsMessage(
                            "You have nothing to pay...");
                    // [T-Up#INFO][COBIL00C.cbl, LINE #227] MOVE statement
                    container.getCobil0ai().setActidinl(-1);
                    // [T-Up#INFO][COBIL00C.cbl, LINE #228] PERFORM statement
                    controlManager.run(context, sendBillpayScreen);
                    if (controlManager.isTerminate(context)) {
                        return;
                    }
                }
            }
            // [T-Up#INFO][COBIL00C.cbl, LINE #232] IF statement
            if (!(CobStringUtils.compare(container.getWsVariables()
                    .getWsErrFlg(), ERR_FLG_ON) == 0)) {
                // [T-Up#INFO][COBIL00C.cbl, LINE #234] IF statement
                if (CobStringUtils.compare(container.getWsVariables()
                        .getWsConfPayFlg(), CONF_PAY_YES) == 0) {
                    // [T-Up#INFO][COBIL00C.cbl, LINE #235] PERFORM statement
                    controlManager.run(context, readCxacaixFile);
                    if (controlManager.isTerminate(context)) {
                        return;
                    }
                    // [T-Up#INFO][COBIL00C.cbl, LINE #236] MOVE statement
                    container.getTranRecord().setTranId(
                            StringUtils.repeat((char) 0xFF, 16));
                    // [T-Up#INFO][COBIL00C.cbl, LINE #237] PERFORM statement
                    controlManager.run(context, startbrTransactFile);
                    if (controlManager.isTerminate(context)) {
                        return;
                    }
                    // [T-Up#INFO][COBIL00C.cbl, LINE #238] PERFORM statement
                    controlManager.run(context, readprevTransactFile);
                    if (controlManager.isTerminate(context)) {
                        return;
                    }
                    // [T-Up#INFO][COBIL00C.cbl, LINE #239] PERFORM statement
                    controlManager.run(context, endbrTransactFile);
                    if (controlManager.isTerminate(context)) {
                        return;
                    }
                    // [T-Up#INFO][COBIL00C.cbl, LINE #240] MOVE statement
                    container.getWsVariables().setWsTranIdNum(
                            Long.parseLong(container.getTranRecord()
                                    .getTranId().trim()));
                    // [T-Up#INFO][COBIL00C.cbl, LINE #241] ADD statement
                    container.getWsVariables()
                            .setWsTranIdNum(
                                    (long) (container.getWsVariables()
                                            .getWsTranIdNum() + 1));
                    // [T-Up#INFO][COBIL00C.cbl, LINE #242] INITIALIZE statement
                    container.setTranRecord(Cobil00cTranRecord
                            .createDefaultValueInstance());
                    // [T-Up#INFO][COBIL00C.cbl, LINE #243] MOVE statement
                    container.getTranRecord().setTranId(
                            StringUtils.leftPad(String.valueOf(Math
                                    .abs(container.getWsVariables()
                                            .getWsTranIdNum())), 16, '0'));
                    // [T-Up#INFO][COBIL00C.cbl, LINE #244] MOVE statement
                    container.getTranRecord().setTranTypeCd("02");
                    // [T-Up#INFO][COBIL00C.cbl, LINE #245] MOVE statement
                    container.getTranRecord().setTranCatCd(2);
                    // [T-Up#INFO][COBIL00C.cbl, LINE #246] MOVE statement
                    container.getTranRecord().setTranSource("POS TERM");
                    // [T-Up#INFO][COBIL00C.cbl, LINE #247] MOVE statement
                    container.getTranRecord().setTranDesc(
                            "BILL PAYMENT - ONLINE");
                    // [T-Up#INFO][COBIL00C.cbl, LINE #248] MOVE statement
                    container.getTranRecord().setTranAmt(
                            container.getAccountRecord().getAcctCurrBal());
                    // [T-Up#INFO][COBIL00C.cbl, LINE #249] MOVE statement
                    container.getTranRecord().setTranCardNum(
                            container.getCardXrefRecord().getXrefCardNum());
                    // [T-Up#INFO][COBIL00C.cbl, LINE #250] MOVE statement
                    container.getTranRecord().setTranMerchantId(999999999);
                    // [T-Up#INFO][COBIL00C.cbl, LINE #251] MOVE statement
                    container.getTranRecord().setTranMerchantName(
                            "BILL PAYMENT");
                    // [T-Up#INFO][COBIL00C.cbl, LINE #252] MOVE statement
                    container.getTranRecord().setTranMerchantCity("N/A");
                    // [T-Up#INFO][COBIL00C.cbl, LINE #253] MOVE statement
                    container.getTranRecord().setTranMerchantZip("N/A");
                    // [T-Up#INFO][COBIL00C.cbl, LINE #254] PERFORM statement
                    controlManager.run(context, getCurrentTimestamp);
                    if (controlManager.isTerminate(context)) {
                        return;
                    }
                    // [T-Up#INFO][COBIL00C.cbl, LINE #255] MOVE statement
                    container.getTranRecord().setTranOrigTs(
                            container.getWsDateTime().getWsTimestamp().get());
                    container.getTranRecord().setTranProcTs(
                            container.getWsDateTime().getWsTimestamp().get());
                    // [T-Up#INFO][COBIL00C.cbl, LINE #257] PERFORM statement
                    controlManager.run(context, writeTransactFile);
                    if (controlManager.isTerminate(context)) {
                        return;
                    }
                    // [T-Up#INFO][COBIL00C.cbl, LINE #258] COMPUTE statement
                    container.getAccountRecord().setAcctCurrBal(
                            container
                                    .getAccountRecord()
                                    .getAcctCurrBal()
                                    .subtract(
                                            container.getTranRecord()
                                                    .getTranAmt()));
                    // [T-Up#INFO][COBIL00C.cbl, LINE #259] PERFORM statement
                    controlManager.run(context, updateAcctdatFile);
                    if (controlManager.isTerminate(context)) {
                        return;
                    }
                } else {
                    // [T-Up#INFO][COBIL00C.cbl, LINE #261] MOVE statement
                    container.getWsVariables().setWsMessage(
                            "Confirm to make a bill payment...");
                    // [T-Up#INFO][COBIL00C.cbl, LINE #263] MOVE statement
                    container.getCobil0ai().setConfirml(-1);
                }
                // [T-Up#INFO][COBIL00C.cbl, LINE #266] PERFORM statement
                controlManager.run(context, sendBillpayScreen);
                if (controlManager.isTerminate(context)) {
                    return;
                }
            }
        }
    }

    // *----------------------------------------------------------------*
    // *                      GET-CURRENT-TIMESTAMP                      
    // *----------------------------------------------------------------*

    void getCurrentTimestamp(OpenFrameContext context) {
        Cobil00cVariableContainer container = (Cobil00cVariableContainer) context
                .getProgramVariableContainer("Cobil00c");
        // [T-Up#INFO][COBIL00C.cbl, LINE #275] EXEC_CICS statement
        /*
                       EXEC CICS ASKTIME                                            
                         ABSTIME(WS-ABS-TIME)                                       
                       END-EXEC
         */
        container.getWsVariables().setWsAbsTime(time.getCurrentTime());
        // [T-Up#INFO][COBIL00C.cbl, LINE #279] EXEC_CICS statement
        /*
                       EXEC CICS FORMATTIME                                         
                         ABSTIME(WS-ABS-TIME)                                       
                         YYYYMMDD(WS-CUR-DATE-X10)                                  
                         DATESEP('-')                                               
                         TIME(WS-CUR-TIME-X08)                                      
                         TIMESEP(':')                                               
                       END-EXEC
         */
        container.getWsVariables().setWsCurDateX10(
                time.setTime(container.getWsVariables().getWsAbsTime())
                        .getYYYYMMDD("-"));
        container.getWsVariables().setWsCurTimeX08(
                time.setTime(container.getWsVariables().getWsAbsTime())
                        .getTime(":"));
        // [T-Up#INFO][COBIL00C.cbl, LINE #287] INITIALIZE statement
        container.getWsDateTime().setWsTimestamp(
                Cobil00cWsDateTime.Cobil00cWsTimestamp
                        .createDefaultValueInstance());
        // [T-Up#INFO][COBIL00C.cbl, LINE #288] MOVE statement
        container
                .getWsDateTime()
                .getWsTimestamp()
                .set(StringUtils.overlay(container.getWsDateTime()
                        .getWsTimestamp().get(), container.getWsVariables()
                        .getWsCurDateX10(), 0, 10));
        // [T-Up#INFO][COBIL00C.cbl, LINE #289] MOVE statement
        container
                .getWsDateTime()
                .getWsTimestamp()
                .set(StringUtils.overlay(container.getWsDateTime()
                        .getWsTimestamp().get(), container.getWsVariables()
                        .getWsCurTimeX08(), 11, 19));
        // [T-Up#INFO][COBIL00C.cbl, LINE #290] MOVE statement
        container.getWsDateTime().getWsTimestamp().setWsTimestampTmMs6(0);
    }

    // *----------------------------------------------------------------*
    // *                      RETURN-TO-PREV-SCREEN                      
    // *----------------------------------------------------------------*

    void returnToPrevScreen(OpenFrameContext context) {
    }

    // *     IF CDEMO-TO-PROGRAM = LOW-VALUES OR SPACES                  
    // *         MOVE 'COSGN00C' TO CDEMO-TO-PROGRAM                     
    // *     END-IF                                                      
    // *     MOVE WS-TRANID    TO CDEMO-FROM-TRANID                      
    // *     MOVE WS-PGMNAME   TO CDEMO-FROM-PROGRAM                     
    // *     MOVE ZEROS        TO CDEMO-PGM-CONTEXT                      
    // *     EXEC CICS                                                   
    // *         XCTL PROGRAM(CDEMO-TO-PROGRAM)                          
    // *         COMMAREA(CARDDEMO-COMMAREA)                             
    // *     END-EXEC.                                                   
    // *----------------------------------------------------------------*
    // *                      SEND-BILLPAY-SCREEN                        
    // *----------------------------------------------------------------*

    void sendBillpayScreen(OpenFrameContext context) {
        Cobil00cVariableContainer container = (Cobil00cVariableContainer) context
                .getProgramVariableContainer("Cobil00c");
        // [T-Up#INFO][COBIL00C.cbl, LINE #315] PERFORM statement
        controlManager.run(context, populateHeaderInfo);
        if (controlManager.isTerminate(context)) {
            return;
        }
        // [T-Up#INFO][COBIL00C.cbl, LINE #317] MOVE statement
        container.setErrmsgo(container.getWsVariables().getWsMessage());
        // [T-Up#INFO][COBIL00C.cbl, LINE #319] EXEC_CICS statement
        /*
                       EXEC CICS SEND                                               
                                 MAP('COBIL0A')                                     
                                 MAPSET('COBIL00')                                  
                                 FROM(COBIL0AO)                                     
                                 ERASE                                              
                                 CURSOR                                             
                       END-EXEC
         */
        ((Cobil00cOutputDto) task.getOutputDto())
                .setPageName("COBIL00_COBIL0A");
        ((Cobil00cOutputDto) task.getOutputDto()).setCobil0ao(container
                .getCobil0ao());
    }

    // *----------------------------------------------------------------*
    // *                      RECEIVE-BILLPAY-SCREEN                     
    // *----------------------------------------------------------------*

    void receiveBillpayScreen(OpenFrameContext context) {
        Cobil00cVariableContainer container = (Cobil00cVariableContainer) context
                .getProgramVariableContainer("Cobil00c");
        // [T-Up#INFO][COBIL00C.cbl, LINE #332] EXEC_CICS statement
        /*
                       EXEC CICS RECEIVE                                            
                                 MAP('COBIL0A')                                     
                                 MAPSET('COBIL00')                                  
                                 INTO(COBIL0AI)                                     
                                 RESP(WS-RESP-CD)                                   
                                 RESP2(WS-REAS-CD)                                  
                       END-EXEC
         */
        try {
            container.setCobil0ai(((Cobil00cInputDto) task.getInputDto())
                    .getCobil0ai());
        } catch (ConditionException e) {
        } finally {
            container.getWsVariables().setWsRespCd(task.getLastResp());
            container.getWsVariables().setWsReasCd(task.getLastResp2());
        }
    }

    // *----------------------------------------------------------------*
    // *                      POPULATE-HEADER-INFO                       
    // *----------------------------------------------------------------*

    void populateHeaderInfo(OpenFrameContext context) {
        Cobil00cVariableContainer container = (Cobil00cVariableContainer) context
                .getProgramVariableContainer("Cobil00c");
        // [T-Up#INFO][COBIL00C.cbl, LINE #345] MOVE statement
        container.getWsDateTime().getWsCurdateData()
                .set(IntrinsicFunction.functionCurrentDate());
        // [T-Up#INFO][COBIL00C.cbl, LINE #347] MOVE statement
        container.setTitle01o(container.getCcdaScreenTitle().getCcdaTitle01());
        // [T-Up#INFO][COBIL00C.cbl, LINE #348] MOVE statement
        container.setTitle02o(container.getCcdaScreenTitle().getCcdaTitle02());
        // [T-Up#INFO][COBIL00C.cbl, LINE #349] MOVE statement
        container.setTrnnameo(container.getWsVariables().getWsTranid());
        // [T-Up#INFO][COBIL00C.cbl, LINE #350] MOVE statement
        container.setPgmnameo(container.getWsVariables().getWsPgmname());
        // [T-Up#INFO][COBIL00C.cbl, LINE #352] MOVE statement
        container
                .getWsDateTime()
                .getWsCurdateMmDdYy()
                .setWsCurdateMm(
                        container.getWsDateTime().getWsCurdateData()
                                .getWsCurdate().getWsCurdateMonth());
        // [T-Up#INFO][COBIL00C.cbl, LINE #353] MOVE statement
        container
                .getWsDateTime()
                .getWsCurdateMmDdYy()
                .setWsCurdateDd(
                        container.getWsDateTime().getWsCurdateData()
                                .getWsCurdate().getWsCurdateDay());
        // [T-Up#INFO][COBIL00C.cbl, LINE #354] MOVE statement
        container
                .getWsDateTime()
                .getWsCurdateMmDdYy()
                .setWsCurdateYy(
                        Integer.parseInt(DataConverter
                                .convZonedLongToString(
                                        container.getWsDateTime()
                                                .getWsCurdateData()
                                                .getWsCurdate()
                                                .getWsCurdateYear(), 4)
                                .substring(2, 4).trim()));
        // [T-Up#INFO][COBIL00C.cbl, LINE #356] MOVE statement
        container.setCurdateo(container.getWsDateTime().getWsCurdateMmDdYy()
                .get());
        // [T-Up#INFO][COBIL00C.cbl, LINE #358] MOVE statement
        container
                .getWsDateTime()
                .getWsCurtimeHhMmSs()
                .setWsCurtimeHh(
                        container.getWsDateTime().getWsCurdateData()
                                .getWsCurtime().getWsCurtimeHours());
        // [T-Up#INFO][COBIL00C.cbl, LINE #359] MOVE statement
        container
                .getWsDateTime()
                .getWsCurtimeHhMmSs()
                .setWsCurtimeMm(
                        container.getWsDateTime().getWsCurdateData()
                                .getWsCurtime().getWsCurtimeMinute());
        // [T-Up#INFO][COBIL00C.cbl, LINE #360] MOVE statement
        container
                .getWsDateTime()
                .getWsCurtimeHhMmSs()
                .setWsCurtimeSs(
                        container.getWsDateTime().getWsCurdateData()
                                .getWsCurtime().getWsCurtimeSecond());
        // [T-Up#INFO][COBIL00C.cbl, LINE #362] MOVE statement
        container.setCurtimeo(container.getWsDateTime().getWsCurtimeHhMmSs()
                .get());
    }

    // *----------------------------------------------------------------*
    // *                      READ-ACCTDAT-FILE                          
    // *----------------------------------------------------------------*

    void readAcctdatFile(OpenFrameContext context) {
        Cobil00cVariableContainer container = (Cobil00cVariableContainer) context
                .getProgramVariableContainer("Cobil00c");
        // [T-Up#INFO][COBIL00C.cbl, LINE #369] EXEC_CICS statement
        /*
                       EXEC CICS READ                                               
                            DATASET   (WS-ACCTDAT-FILE)                             
                            INTO      (ACCOUNT-RECORD)                              
                            LENGTH    (LENGTH OF ACCOUNT-RECORD)                    
                            RIDFLD    (ACCT-ID)                                     
                            KEYLENGTH (LENGTH OF ACCT-ID)                           
                            UPDATE                                                  
                            RESP      (WS-RESP-CD)                                  
                            RESP2     (WS-REAS-CD)                                  
                       END-EXEC
         */
        try {
            AwsM2CarddemoAcctdataVsamKsdsDto awsM2CarddemoAcctdataVsamKsdsDto = recordKeyAccessor
                    .readForUpdate("awsM2CarddemoAcctdataVsamKsdsDao",
                            BigDecimal.valueOf(container.getAccountRecord()
                                    .getAcctId()));
            container
                    .setAccountRecord(Cobil00cAccountRecordToAwsM2CarddemoAcctdataVsamKsdsDto.INSTANCE
                            .toSource(awsM2CarddemoAcctdataVsamKsdsDto));
        } catch (ConditionException e) {
        } finally {
            container.getWsVariables().setWsRespCd(task.getLastResp());
            container.getWsVariables().setWsReasCd(task.getLastResp2());
        }
        // [T-Up#INFO][COBIL00C.cbl, LINE #380] EVALUATE statement
        if (container.getWsVariables().getWsRespCd() == 0) {
            // [T-Up#INFO][COBIL00C.cbl, LINE #382] CONTINUE statement
        } else if (container.getWsVariables().getWsRespCd() == 13) {
            // [T-Up#INFO][COBIL00C.cbl, LINE #384] MOVE statement
            container.getWsVariables().setWsErrFlg("Y");
            // [T-Up#INFO][COBIL00C.cbl, LINE #385] MOVE statement
            container.getWsVariables().setWsMessage("Account ID NOT found...");
            // [T-Up#INFO][COBIL00C.cbl, LINE #387] MOVE statement
            container.getCobil0ai().setActidinl(-1);
            // [T-Up#INFO][COBIL00C.cbl, LINE #388] PERFORM statement
            controlManager.run(context, sendBillpayScreen);
            if (controlManager.isTerminate(context)) {
                return;
            }
        } else {
            // [T-Up#INFO][COBIL00C.cbl, LINE #390] DISPLAY statement
            System.out.print("RESP:");
            System.out.print(container.getWsVariables().getWsRespCd());
            System.out.print("REAS:");
            System.out.println(container.getWsVariables().getWsReasCd());
            // [T-Up#INFO][COBIL00C.cbl, LINE #391] MOVE statement
            container.getWsVariables().setWsErrFlg("Y");
            // [T-Up#INFO][COBIL00C.cbl, LINE #392] MOVE statement
            container.getWsVariables().setWsMessage(
                    "Unable to lookup Account...");
            // [T-Up#INFO][COBIL00C.cbl, LINE #394] MOVE statement
            container.getCobil0ai().setActidinl(-1);
            // [T-Up#INFO][COBIL00C.cbl, LINE #395] PERFORM statement
            controlManager.run(context, sendBillpayScreen);
            if (controlManager.isTerminate(context)) {
                return;
            }
        }
    }

    // *----------------------------------------------------------------*
    // *                      UPDATE-ACCTDAT-FILE                        
    // *----------------------------------------------------------------*

    void updateAcctdatFile(OpenFrameContext context) {
        Cobil00cVariableContainer container = (Cobil00cVariableContainer) context
                .getProgramVariableContainer("Cobil00c");
        // [T-Up#INFO][COBIL00C.cbl, LINE #403] EXEC_CICS statement
        /*
                       EXEC CICS REWRITE                                            
                            DATASET   (WS-ACCTDAT-FILE)                             
                            FROM      (ACCOUNT-RECORD)                              
                            LENGTH    (LENGTH OF ACCOUNT-RECORD)                    
                            RESP      (WS-RESP-CD)                                  
                            RESP2     (WS-REAS-CD)                                  
                       END-EXEC
         */
        try {
            AwsM2CarddemoAcctdataVsamKsdsDto awsM2CarddemoAcctdataVsamKsdsDto = Cobil00cAccountRecordToAwsM2CarddemoAcctdataVsamKsdsDto.INSTANCE
                    .toTarget(container.getAccountRecord());
            recordKeyAccessor.updateLast("awsM2CarddemoAcctdataVsamKsdsDao",
                    awsM2CarddemoAcctdataVsamKsdsDto);
        } catch (ConditionException e) {
        } finally {
            container.getWsVariables().setWsRespCd(task.getLastResp());
            container.getWsVariables().setWsReasCd(task.getLastResp2());
        }
        // [T-Up#INFO][COBIL00C.cbl, LINE #411] EVALUATE statement
        if (container.getWsVariables().getWsRespCd() == 0) {
            // [T-Up#INFO][COBIL00C.cbl, LINE #413] CONTINUE statement
        } else if (container.getWsVariables().getWsRespCd() == 13) {
            // [T-Up#INFO][COBIL00C.cbl, LINE #415] MOVE statement
            container.getWsVariables().setWsErrFlg("Y");
            // [T-Up#INFO][COBIL00C.cbl, LINE #416] MOVE statement
            container.getWsVariables().setWsMessage("Account ID NOT found...");
            // [T-Up#INFO][COBIL00C.cbl, LINE #418] MOVE statement
            container.getCobil0ai().setActidinl(-1);
            // [T-Up#INFO][COBIL00C.cbl, LINE #419] PERFORM statement
            controlManager.run(context, sendBillpayScreen);
            if (controlManager.isTerminate(context)) {
                return;
            }
        } else {
            // [T-Up#INFO][COBIL00C.cbl, LINE #421] DISPLAY statement
            System.out.print("RESP:");
            System.out.print(container.getWsVariables().getWsRespCd());
            System.out.print("REAS:");
            System.out.println(container.getWsVariables().getWsReasCd());
            // [T-Up#INFO][COBIL00C.cbl, LINE #422] MOVE statement
            container.getWsVariables().setWsErrFlg("Y");
            // [T-Up#INFO][COBIL00C.cbl, LINE #423] MOVE statement
            container.getWsVariables().setWsMessage(
                    "Unable to Update Account...");
            // [T-Up#INFO][COBIL00C.cbl, LINE #425] MOVE statement
            container.getCobil0ai().setActidinl(-1);
            // [T-Up#INFO][COBIL00C.cbl, LINE #426] PERFORM statement
            controlManager.run(context, sendBillpayScreen);
            if (controlManager.isTerminate(context)) {
                return;
            }
        }
    }

    // *----------------------------------------------------------------*
    // *                      READ-CXACAIX-FILE                          
    // *----------------------------------------------------------------*

    void readCxacaixFile(OpenFrameContext context) {
        Cobil00cVariableContainer container = (Cobil00cVariableContainer) context
                .getProgramVariableContainer("Cobil00c");
        // [T-Up#INFO][COBIL00C.cbl, LINE #434] EXEC_CICS statement
        /*
                       EXEC CICS READ                                               
                            DATASET   (WS-CXACAIX-FILE)                             
                            INTO      (CARD-XREF-RECORD)                            
                            LENGTH    (LENGTH OF CARD-XREF-RECORD)                  
                            RIDFLD    (XREF-ACCT-ID)                                
                            KEYLENGTH (LENGTH OF XREF-ACCT-ID)                      
                            RESP      (WS-RESP-CD)                                  
                            RESP2     (WS-REAS-CD)                                  
                       END-EXEC
         */
        try {
            AwsM2CarddemoCardxrefVsamKsdsDto awsM2CarddemoCardxrefVsamKsdsDto = recordKeyAccessor
                    .alternateIndex().read(
                            "awsM2CarddemoCardxrefVsamKsdsDao",
                            "Aix10",
                            BigDecimal.valueOf(container.getCardXrefRecord()
                                    .getXrefAcctId()));
            container
                    .setCardXrefRecord(Cobil00cCardXrefRecordToAwsM2CarddemoCardxrefVsamKsdsDto.INSTANCE
                            .toSource(awsM2CarddemoCardxrefVsamKsdsDto));
        } catch (ConditionException e) {
        } finally {
            container.getWsVariables().setWsRespCd(task.getLastResp());
            container.getWsVariables().setWsReasCd(task.getLastResp2());
        }
        // [T-Up#INFO][COBIL00C.cbl, LINE #444] EVALUATE statement
        if (container.getWsVariables().getWsRespCd() == 0) {
            // [T-Up#INFO][COBIL00C.cbl, LINE #446] CONTINUE statement
        } else if (container.getWsVariables().getWsRespCd() == 13) {
            // [T-Up#INFO][COBIL00C.cbl, LINE #448] MOVE statement
            container.getWsVariables().setWsErrFlg("Y");
            // [T-Up#INFO][COBIL00C.cbl, LINE #449] MOVE statement
            container.getWsVariables().setWsMessage("Account ID NOT found...");
            // [T-Up#INFO][COBIL00C.cbl, LINE #451] MOVE statement
            container.getCobil0ai().setActidinl(-1);
            // [T-Up#INFO][COBIL00C.cbl, LINE #452] PERFORM statement
            controlManager.run(context, sendBillpayScreen);
            if (controlManager.isTerminate(context)) {
                return;
            }
        } else {
            // [T-Up#INFO][COBIL00C.cbl, LINE #454] DISPLAY statement
            System.out.print("RESP:");
            System.out.print(container.getWsVariables().getWsRespCd());
            System.out.print("REAS:");
            System.out.println(container.getWsVariables().getWsReasCd());
            // [T-Up#INFO][COBIL00C.cbl, LINE #455] MOVE statement
            container.getWsVariables().setWsErrFlg("Y");
            // [T-Up#INFO][COBIL00C.cbl, LINE #456] MOVE statement
            container.getWsVariables().setWsMessage(
                    "Unable to lookup XREF AIX file...");
            // [T-Up#INFO][COBIL00C.cbl, LINE #458] MOVE statement
            container.getCobil0ai().setActidinl(-1);
            // [T-Up#INFO][COBIL00C.cbl, LINE #459] PERFORM statement
            controlManager.run(context, sendBillpayScreen);
            if (controlManager.isTerminate(context)) {
                return;
            }
        }
    }

    // *----------------------------------------------------------------*
    // *                      STARTBR-TRANSACT-FILE                      
    // *----------------------------------------------------------------*

    void startbrTransactFile(OpenFrameContext context) {
        Cobil00cVariableContainer container = (Cobil00cVariableContainer) context
                .getProgramVariableContainer("Cobil00c");
        // [T-Up#INFO][COBIL00C.cbl, LINE #467] EXEC_CICS statement
        /*
                       EXEC CICS STARTBR                                            
                            DATASET   (WS-TRANSACT-FILE)                            
                            RIDFLD    (TRAN-ID)                                     
                            KEYLENGTH (LENGTH OF TRAN-ID)                           
                            RESP      (WS-RESP-CD)                                  
                            RESP2     (WS-REAS-CD)                                  
                       END-EXEC
         */
        try {
            ReadPoint readPoint = readPointManager
                    .declare(
                            "awsM2CarddemoTransactVsamKsdsDao",
                            0,
                            (AwsM2CarddemoTransactVsamKsdsDto awsM2CarddemoTransactVsamKsdsDto) -> {
                                return awsM2CarddemoTransactVsamKsdsDto
                                        .getTranId();
                            });
            AwsM2CarddemoTransactVsamKsdsDto awsM2CarddemoTransactVsamKsdsDto = readPointAccessor
                    .open(readPoint, container.getTranRecord().getTranId());
            container.getTranRecord().setTranId(
                    awsM2CarddemoTransactVsamKsdsDto.getTranId());
        } catch (ConditionException e) {
        } finally {
            container.getWsVariables().setWsRespCd(task.getLastResp());
            container.getWsVariables().setWsReasCd(task.getLastResp2());
        }
        // [T-Up#INFO][COBIL00C.cbl, LINE #475] EVALUATE statement
        if (container.getWsVariables().getWsRespCd() == 0) {
            // [T-Up#INFO][COBIL00C.cbl, LINE #477] CONTINUE statement
        } else if (container.getWsVariables().getWsRespCd() == 13) {
            // [T-Up#INFO][COBIL00C.cbl, LINE #479] MOVE statement
            container.getWsVariables().setWsErrFlg("Y");
            // [T-Up#INFO][COBIL00C.cbl, LINE #480] MOVE statement
            container.getWsVariables().setWsMessage(
                    "Transaction ID NOT found...");
            // [T-Up#INFO][COBIL00C.cbl, LINE #482] MOVE statement
            container.getCobil0ai().setActidinl(-1);
            // [T-Up#INFO][COBIL00C.cbl, LINE #483] PERFORM statement
            controlManager.run(context, sendBillpayScreen);
            if (controlManager.isTerminate(context)) {
                return;
            }
        } else {
            // [T-Up#INFO][COBIL00C.cbl, LINE #485] DISPLAY statement
            System.out.print("RESP:");
            System.out.print(container.getWsVariables().getWsRespCd());
            System.out.print("REAS:");
            System.out.println(container.getWsVariables().getWsReasCd());
            // [T-Up#INFO][COBIL00C.cbl, LINE #486] MOVE statement
            container.getWsVariables().setWsErrFlg("Y");
            // [T-Up#INFO][COBIL00C.cbl, LINE #487] MOVE statement
            container.getWsVariables().setWsMessage(
                    "Unable to lookup Transaction...");
            // [T-Up#INFO][COBIL00C.cbl, LINE #489] MOVE statement
            container.getCobil0ai().setActidinl(-1);
            // [T-Up#INFO][COBIL00C.cbl, LINE #490] PERFORM statement
            controlManager.run(context, sendBillpayScreen);
            if (controlManager.isTerminate(context)) {
                return;
            }
        }
    }

    // *----------------------------------------------------------------*
    // *                      READPREV-TRANSACT-FILE                     
    // *----------------------------------------------------------------*

    void readprevTransactFile(OpenFrameContext context) {
        Cobil00cVariableContainer container = (Cobil00cVariableContainer) context
                .getProgramVariableContainer("Cobil00c");
        // [T-Up#INFO][COBIL00C.cbl, LINE #498] EXEC_CICS statement
        /*
                       EXEC CICS READPREV                                           
                            DATASET   (WS-TRANSACT-FILE)                            
                            INTO      (TRAN-RECORD)                                 
                            LENGTH    (LENGTH OF TRAN-RECORD)                       
                            RIDFLD    (TRAN-ID)                                     
                            KEYLENGTH (LENGTH OF TRAN-ID)                           
                            RESP      (WS-RESP-CD)                                  
                            RESP2     (WS-REAS-CD)                                  
                       END-EXEC
         */
        try {
            ReadPoint readPoint = readPointManager.find(0);
            AwsM2CarddemoTransactVsamKsdsDto awsM2CarddemoTransactVsamKsdsDto = readPointAccessor
                    .readPrev(readPoint, container.getTranRecord().getTranId());
            container.getTranRecord().setTranId(
                    awsM2CarddemoTransactVsamKsdsDto.getTranId());
            container
                    .setTranRecord(Cobil00cTranRecordToAwsM2CarddemoTransactVsamKsdsDto.INSTANCE
                            .toSource(awsM2CarddemoTransactVsamKsdsDto));
        } catch (ConditionException e) {
        } finally {
            container.getWsVariables().setWsRespCd(task.getLastResp());
            container.getWsVariables().setWsReasCd(task.getLastResp2());
        }
        // [T-Up#INFO][COBIL00C.cbl, LINE #508] EVALUATE statement
        if (container.getWsVariables().getWsRespCd() == 0) {
            // [T-Up#INFO][COBIL00C.cbl, LINE #510] CONTINUE statement
        } else if (container.getWsVariables().getWsRespCd() == 20) {
            // [T-Up#INFO][COBIL00C.cbl, LINE #512] MOVE statement
            container.getTranRecord().setTranId(StringUtils.repeat('0', 16));
        } else {
            // [T-Up#INFO][COBIL00C.cbl, LINE #514] DISPLAY statement
            System.out.print("RESP:");
            System.out.print(container.getWsVariables().getWsRespCd());
            System.out.print("REAS:");
            System.out.println(container.getWsVariables().getWsReasCd());
            // [T-Up#INFO][COBIL00C.cbl, LINE #515] MOVE statement
            container.getWsVariables().setWsErrFlg("Y");
            // [T-Up#INFO][COBIL00C.cbl, LINE #516] MOVE statement
            container.getWsVariables().setWsMessage(
                    "Unable to lookup Transaction...");
            // [T-Up#INFO][COBIL00C.cbl, LINE #518] MOVE statement
            container.getCobil0ai().setActidinl(-1);
            // [T-Up#INFO][COBIL00C.cbl, LINE #519] PERFORM statement
            controlManager.run(context, sendBillpayScreen);
            if (controlManager.isTerminate(context)) {
                return;
            }
        }
    }

    // *----------------------------------------------------------------*
    // *                      ENDBR-TRANSACT-FILE                        
    // *----------------------------------------------------------------*

    void endbrTransactFile(OpenFrameContext context) {
        Cobil00cVariableContainer container = (Cobil00cVariableContainer) context
                .getProgramVariableContainer("Cobil00c");
        // [T-Up#INFO][COBIL00C.cbl, LINE #527] EXEC_CICS statement
        /*
                       EXEC CICS ENDBR                                              
                            DATASET   (WS-TRANSACT-FILE)                            
                       END-EXEC
         */
        ReadPoint readPoint = readPointManager.find(0);
        readPointAccessor.close(readPoint);
    }

    // *----------------------------------------------------------------*
    // *                      WRITE-TRANSACT-FILE                        
    // *----------------------------------------------------------------*

    void writeTransactFile(OpenFrameContext context) {
        StringBuilder tempStringBuilder1;
        StringBuilder tempStringBuilder2;
        Cobil00cVariableContainer container = (Cobil00cVariableContainer) context
                .getProgramVariableContainer("Cobil00c");
        // [T-Up#INFO][COBIL00C.cbl, LINE #536] EXEC_CICS statement
        /*
                       EXEC CICS WRITE                                              
                            DATASET   (WS-TRANSACT-FILE)                            
                            FROM      (TRAN-RECORD)                                 
                            LENGTH    (LENGTH OF TRAN-RECORD)                       
                            RIDFLD    (TRAN-ID)                                     
                            KEYLENGTH (LENGTH OF TRAN-ID)                           
                            RESP      (WS-RESP-CD)                                  
                            RESP2     (WS-REAS-CD)                                  
                       END-EXEC
         */
        try {
            AwsM2CarddemoTransactVsamKsdsDto awsM2CarddemoTransactVsamKsdsDto = Cobil00cTranRecordToAwsM2CarddemoTransactVsamKsdsDto.INSTANCE
                    .toTarget(container.getTranRecord());
            awsM2CarddemoTransactVsamKsdsDto.setTranId(container
                    .getTranRecord().getTranId());
            recordKeyAccessor.writeWithReturningId(
                    "awsM2CarddemoTransactVsamKsdsDao",
                    awsM2CarddemoTransactVsamKsdsDto);
        } catch (ConditionException e) {
        } finally {
            container.getWsVariables().setWsRespCd(task.getLastResp());
            container.getWsVariables().setWsReasCd(task.getLastResp2());
        }
        // [T-Up#INFO][COBIL00C.cbl, LINE #546] EVALUATE statement
        if (container.getWsVariables().getWsRespCd() == 0) {
            // [T-Up#INFO][COBIL00C.cbl, LINE #548] PERFORM statement
            controlManager.run(context, initializeAllFields);
            if (controlManager.isTerminate(context)) {
                return;
            }
            // [T-Up#INFO][COBIL00C.cbl, LINE #549] MOVE statement
            container.getWsVariables()
                    .setWsMessage(StringUtils.repeat(' ', 80));
            // [T-Up#INFO][COBIL00C.cbl, LINE #550] MOVE statement
            container.setErrmsgc(container.getDfhbmsca().getDfhgreen());
            // [T-Up#INFO][COBIL00C.cbl, LINE #551] STRING statement
            tempStringBuilder1 = new StringBuilder();
            tempStringBuilder2 = new StringBuilder(container.getWsVariables()
                    .getWsMessage());
            tempStringBuilder1
                    .append("Payment successful. ")
                    .append(" Your Transaction ID is ")
                    .append(container.getTranRecord().getTranId()
                            .split(Pattern.quote(" "))[0]).append(".");
            if (tempStringBuilder1.length() <= 80) {
                tempStringBuilder2.replace(0, tempStringBuilder1.length(),
                        tempStringBuilder1.toString());
                container.getWsVariables().setWsMessage(
                        tempStringBuilder2.toString());
            }
            // [T-Up#INFO][COBIL00C.cbl, LINE #556] PERFORM statement
            controlManager.run(context, sendBillpayScreen);
            if (controlManager.isTerminate(context)) {
                return;
            }
        } else if ((container.getWsVariables().getWsRespCd() == 15)
                || (container.getWsVariables().getWsRespCd() == 14)) {
            // [T-Up#INFO][COBIL00C.cbl, LINE #559] MOVE statement
            container.getWsVariables().setWsErrFlg("Y");
            // [T-Up#INFO][COBIL00C.cbl, LINE #560] MOVE statement
            container.getWsVariables().setWsMessage("Tran ID already exist...");
            // [T-Up#INFO][COBIL00C.cbl, LINE #562] MOVE statement
            container.getCobil0ai().setActidinl(-1);
            // [T-Up#INFO][COBIL00C.cbl, LINE #563] PERFORM statement
            controlManager.run(context, sendBillpayScreen);
            if (controlManager.isTerminate(context)) {
                return;
            }
        } else {
            // [T-Up#INFO][COBIL00C.cbl, LINE #565] DISPLAY statement
            System.out.print("RESP:");
            System.out.print(container.getWsVariables().getWsRespCd());
            System.out.print("REAS:");
            System.out.println(container.getWsVariables().getWsReasCd());
            // [T-Up#INFO][COBIL00C.cbl, LINE #566] MOVE statement
            container.getWsVariables().setWsErrFlg("Y");
            // [T-Up#INFO][COBIL00C.cbl, LINE #567] MOVE statement
            container.getWsVariables().setWsMessage(
                    "Unable to Add Bill pay Transaction...");
            // [T-Up#INFO][COBIL00C.cbl, LINE #569] MOVE statement
            container.getCobil0ai().setActidinl(-1);
            // [T-Up#INFO][COBIL00C.cbl, LINE #570] PERFORM statement
            controlManager.run(context, sendBillpayScreen);
            if (controlManager.isTerminate(context)) {
                return;
            }
        }
    }

    // *----------------------------------------------------------------*
    // *                      CLEAR-CURRENT-SCREEN                       
    // *----------------------------------------------------------------*

    void clearCurrentScreen(OpenFrameContext context) {
        // [T-Up#INFO][COBIL00C.cbl, LINE #578] PERFORM statement
        controlManager.run(context, initializeAllFields);
        if (controlManager.isTerminate(context)) {
            return;
        }
        // [T-Up#INFO][COBIL00C.cbl, LINE #579] PERFORM statement
        controlManager.run(context, sendBillpayScreen);
        if (controlManager.isTerminate(context)) {
            return;
        }
    }

    // *----------------------------------------------------------------*
    // *                      INITIALIZE-ALL-FIELDS                      
    // *----------------------------------------------------------------*

    void initializeAllFields(OpenFrameContext context) {
        Cobil00cVariableContainer container = (Cobil00cVariableContainer) context
                .getProgramVariableContainer("Cobil00c");
        // [T-Up#INFO][COBIL00C.cbl, LINE #586] MOVE statement
        container.getCobil0ai().setActidinl(-1);
        // [T-Up#INFO][COBIL00C.cbl, LINE #587] MOVE statement
        container.getCobil0ai().setActidini(StringUtils.repeat(' ', 11));
        container.getCobil0ai().setCurbali(StringUtils.repeat(' ', 14));
        container.getCobil0ai().setConfirmi(" ");
        container.getWsVariables().setWsMessage(StringUtils.repeat(' ', 80));
    }

    // *                                                                 
    // * Ver: CardDemo_v1.0-15-g27d6c6f-68 Date: 2022-07-19 23:12:32 CDT 
    // *                                                                 
}
